### ISSUE TITLE
Unbind single lsp keybinding

### ISSUE THREAD

**Issue by twiclo** [VonHeikemen/lsp-zero.nvim#100]
I want to keep all the other presets for the LSP when in a buffer that supports it. I Just want to ubind `K`. Is my only option to set `set_lsp_keymap` to false and rebind every keybinding?

**Comment by VonHeikemen** [comment]
I just updated `set_lsp_keymaps` option. You can now specify a list of keys you want to omit during setup.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.set_preferences({
  set_lsp_keymaps = {omit = {'K', 'gl'}}
})

lsp.setup()
```

**Comment by twiclo** [comment]
That works. Thanks for the quick response.
