### ISSUE TITLE
[Feature Request] Add a way to configure cmp_select_opts

### ISSUE THREAD

**Issue by dylanpjx** [VonHeikemen/lsp-zero.nvim#101]
It would be very helpful to have this as a top level configuration and not need to add mappings to override the select opts. Thanks!

**Comment by VonHeikemen** [comment]
There is a way. Change the preset to `lsp-compe`. Then you can configure nvim-cmp however you like. You can use the function [.defaults.cmp_config](https://github.com/VonHeikemen/lsp-zero.nvim#defaultscmp_configopts) to extend/change the defaults lsp-zero offers and pass that to nvim-cmp.

```lua
local lsp = require('lsp-zero')
lsp.preset('lsp-compe')

lsp.setup()

vim.opt.completeopt = {'menu', 'menuone', 'noselect'}

local cmp = require('cmp')
local cmp_config = lsp.defaults.cmp_config({
  ---
  -- nvim-cmp options go here
  ---
})

cmp.setup(cmp_config)
```

**Comment by VonHeikemen** [comment]
Wait. You mean the select behavior when you move between items?

**Comment by dylanpjx** [comment]
Afaik, that would still require one to re-add mappings and change/insert `cmp.SelectBehavior` per mapping manually right?

It would be great if lspzero had a global option that could be set at the top level.

**Comment by VonHeikemen** [comment]
It would be lovely if nvim-cmp had that feature.

Okay. I've added `select_behavior` option to `.setup_nvim_cmp`.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.setup_nvim_cmp({
  select_behavior = 'insert'
})

lsp.setup()
```

Is worth mention the default in lsp-zero is the first item gets "preselected", but it seems the text won't be inserted in this case. It'll only start putting text in the buffer when you start navigating between items.

If you disable the preselect you'll get something more consistent.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.setup_nvim_cmp({
  select_behavior = 'insert',
  preselect = 'none',
  completion = {
    completeopt = 'menu,menuone,noinsert,noselect'
  },
})

lsp.setup()
```

**Comment by dylanpjx** [comment]
Wow, thanks for the fast patch! :smile:

**Comment by VonHeikemen** [comment]
Global variables FTW!
