### ISSUE TITLE
`sumneko_lua` renaming results in "Language server couldn't provide rename result"

### ISSUE THREAD

**Issue by starptr** [VonHeikemen/lsp-zero.nvim#103]
Not sure if lsp-zero is causing this, but when invoking `vim.lsp.buf.rename`, sumneko_lua (I checkd that it is attached to the buffer) prints "Language server couldn't provide rename result".

**Comment by VonHeikemen** [comment]
You can test it without lsp-zero. Comment out the config for lsp-zero and try this one.

```lua
require('mason').setup({})
require('mason-lspconfig').setup({})

require('lspconfig').sumneko_lua.setup({
  on_attach = function(client, bufnr)
    vim.keymap.set('n', '<F2>', vim.lsp.buf.rename, {buffer = bufnr, desc = 'Rename var'})
  end,
})
```

**Comment by starptr** [comment]
It works after I commented out the config for lsp-zero and used your small example :(

**Comment by VonHeikemen** [comment]
Can you show me your config for lsp-zero?

**Comment by starptr** [comment]
Yes, the configuration relevant to lsp-zero is here https://github.com/starptr/nvim-config/blob/bc9f3da392a98f9625e4e02e989ca59adb3fd915/after/plugin/lsp-zero.lua

The keybind is assigned [in a different file](https://github.com/starptr/nvim-config/blob/bc9f3da392a98f9625e4e02e989ca59adb3fd915/after/plugin/which-key.lua#L58-L58), but I am almost certain that `vim.lsp.buf.rename` is correctly called (since the dressing vim-input popup appears)

**Comment by VonHeikemen** [comment]
I cloned your config, tried it, didn't get an error message when trying to rename a variable but it also didn't work out of the box.

I checked with the command `LspInfo` and saw the LSP server was running in "single file mode". I created a file called `.luarc.json` (with an empty object) in the root of the directory. This way the LSP server can recognize the project. I tried the rename function again and it worked.

A side note unrelated to the bug: since you are configuring nvim-cmp manually you should change `  manage_nvim_cmp` to `false`.

**Comment by starptr** [comment]
Thanks, somehow I ended up with `.luarc.json` being inside `lua/`, which caused the lsp to run in single file mode. After moving it to the root directory, rename seems to work correctly.

Orthogonal, but what does `.nvim_workspace {}` actually do? If I understand the docs correctly, does it add lsp completion for the global `vim` lua variable? I also originally added the `library = vim.api.nvim_get_runtime_file('', true)` line because I thought this would add completion for plugin variables that are `require`d.

**Comment by VonHeikemen** [comment]
`.nvim_workspace` configures "source" for nvim-cmp that autocompletes the neovim api. And adds these settings to sumneko_lua.

```lua
local runtime_path = vim.split(package.path, ';')
table.insert(runtime_path, 'lua/?.lua')
table.insert(runtime_path, 'lua/?/init.lua')

{
  settings = {
    Lua = {
      -- Disable telemetry
      telemetry = {enable = false},
      runtime = {
        -- Tell the language server which version of Lua you're using
        version = 'LuaJIT',
        path = runtime_path,
      },
      diagnostics = {
        -- Get the language server to recognize the `vim` global
        globals = {'vim'}
      },
      workspace = {
        library = {
          -- Make the server aware of Neovim runtime files
          vim.fn.expand('$VIMRUNTIME/lua'),
          vim.fn.stdpath('config') .. '/lua'
        }
      }
    }
  }
}
```
