### ISSUE TITLE
Suggest LSP Servers is cool feature; consider making it its own plugin

### ISSUE THREAD

**Issue by Aaronik** [VonHeikemen/lsp-zero.nvim#104]
Hello,

Your feature for suggesting lsp servers is great. Is there any chance you might turn it into its own plugin? Or do you know of any plugins that do it already?

**Comment by VonHeikemen** [comment]
The actual suggestions come from `mason-lspconfig.nvim`. If you execute the command `LspInstall` it'll show you the menu with the suggestions. What lsp-zero does is keep track of the "new" filetypes and ask the first question.

**Comment by Aaronik** [comment]
Oh yeah, cool thank you!
