### ISSUE TITLE
explain in "under the hood" what lsp.setup() does.

### ISSUE THREAD

**Issue by matu3ba** [VonHeikemen/lsp-zero.nvim#105]
Background: I dont know why my language server `zls` not installed via `mason` does not work.
It is in `PATH` and it used the default configuration before I switched to lsp-zero: `require('lspconfig').zls.setup {}`.

The `:LspLog` also shows no entries on zls, so it looks like it is not even started.

**Comment by VonHeikemen** [comment]
`.setup()` does a lot of things. But I guess you are only  interested in what it does to call LSP servers. Basically is this.

```lua
require('mason').setup({})
require('mason-lspconfig').setup({})

require('mason-lspconfig').setup_handlers({
  function(server_name)
    require('lspconfig')[server_name].setup({
      on_attach = lsp_attach,
      capabilities = require('cmp_nvim_lsp').default_capabilities(),
    })
  end
})
```

If you are using the `recommended` preset only the servers installed with `mason.nvim` will be called.

Now, you can still call LSP servers installed globally but you need to be explicit. Use the function `.configure` and enable the option `force_setup`.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.configure('zls', {force_setup = true})

lsp.setup()
```

If you have more than one LSP server installed globally you can also use `.setup_servers` and enable the `force` option.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.setup_servers({'zls', 'dartls', force = true})

lsp.setup()
```

**Comment by matu3ba** [comment]
Ah, I should have tried https://github.com/VonHeikemen/lsp-zero.nvim#configurename-opts. 
The phrasing `have a server installed globally you can use the option force_setup to skip any internal check.` is unclear on what internal checks are for and why it is not working.

**Comment by VonHeikemen** [comment]
It checks if your server is installed with `mason.nvim`. When using `force_setup` you skip all that, you basically call lspconfig right away.

**Comment by matu3ba** [comment]
I think the phrase `globally` is abit misleading, because extending PATH does not make things global per se: https://unix.stackexchange.com/questions/104727/add-a-path-in-path-globally-for-every-user

**Comment by VonHeikemen** [comment]
I just think about it as the opposite of `local`. If I install something with mason.nvim that is "local" to neovim. 

If I install `tsserver` using mason then the command `typescript-language-server` will only work inside neovim. Typing that command once I exit neovim will not work.

If I can execute `typescript-language-server` when neovim is closed then to me that is "global".

**Comment by matu3ba** [comment]
Ah, I think its fine then for now and if other users are confused, this can be reopened.

Closing.
