### ISSUE TITLE
Use folke/trouble.nvim (nvim-web-devicons) sign_icons instead of default ones

### ISSUE THREAD

**Issue by steakhutzeee** [VonHeikemen/lsp-zero.nvim#113]
Hello,

i would like to use the [folke/trouble.nvim](https://github.com/folke/trouble.nvim) (nvim-web-devicons) icons for errors, warnings etc. instead of the default ones.

Tried with this config to reset the sign icons but it's not working.

```
--[lsp/mason]--
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.ensure_installed({
  'pyright',
  'sumneko_lua',
})

lsp.set_preferences({
  sign_icons = {
    error = ' ',
    warn = ' ',
    hint = ' ',
    info = ' ',
  }
})

Thank you in advance.

lsp.setup()
```

**Comment by VonHeikemen** [comment]
Update lsp-zero then set `sign_icons = false`. That will make lsp-zero skip the configuration of icons.

**Comment by steakhutzeee** [comment]
> Update lsp-zero then set `sign_icons = false`. That will make lsp-zero skip the configuration of icons.
> 
> Edit: I suggest you move `.set_preferences()` up, put it right after `.preset()`.

Updated lsp-zero and set:

```
--[lsp/mason]--
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.set_preferences({
  sign_icons = false,
})

lsp.ensure_installed({
  'pyright',
  'sumneko_lua',
})

lsp.setup()
```

But now the symbols are replaced by I/E/H.

**Comment by VonHeikemen** [comment]
Oh. I thought `trouble.nvim` configured the icons for diagnostics.

Okay. Then just copy their icons.

```lua
sign_icons = {
  error = "",
  warn = "",
  hint = "",
  info = "",
}
```

**Comment by steakhutzeee** [comment]
> Oh. I thought `trouble.nvim` configured the icons for diagnostics.
> 
> Okay. Then just copy their icons.
> 
> ```lua
> sign_icons = {
>   error = "",
>   warn = "",
>   hint = "",
>   info = "",
> }
> ```

Yup, this works, thanks!

Little question, don't know if this can be resolved in lsp-zero config. Can i move the signs horizontally? Actually they are just next the left border. Maybe they can be centered?

**Comment by VonHeikemen** [comment]
Pretty sure the only  thing you can do add whitespace character to the right or left.

**Comment by steakhutzeee** [comment]
Yup, that did the trick, thanks!
