### ISSUE TITLE
Unable to install sumneko_lua

### ISSUE THREAD

**Issue by steakhutzeee** [VonHeikemen/lsp-zero.nvim#114]
Hello,

i setup lsp-zero this way:

```
use {
  'VonHeikemen/lsp-zero.nvim',
  requires = {
    -- LSP Support
    {'neovim/nvim-lspconfig'},
    {'williamboman/mason.nvim'},
    {'williamboman/mason-lspconfig.nvim'},

    -- Autocompletion
    {'hrsh7th/nvim-cmp'},
    {'hrsh7th/cmp-buffer'},
    {'hrsh7th/cmp-path'},
    {'saadparwaiz1/cmp_luasnip'},
    {'hrsh7th/cmp-nvim-lsp'},
    {'hrsh7th/cmp-nvim-lua'},

    -- Snippets
    {'L3MON4D3/LuaSnip'},
    {'rafamadriz/friendly-snippets'},
  }
}

--[lsp/mason]--
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.set_preferences({
  sign_icons = false,
})

lsp.ensure_installed({
  'pyright',
  'sumneko_lua',
})

lsp.setup()
```

Pyright has been installed successfully but from mason logs i see that lua-language-server is not installed because:

error=spawn: unzip failed with exit code - and signal -. unzip is not executable.

Thank you in advance.

**Comment by VonHeikemen** [comment]
Try installing `unzip`  in your system. Use whatever package manager your OS has.

**Comment by steakhutzeee** [comment]
> Try installing `unzip` in your system. Use whatever package manager your OS has.

Yep, that made it. It installed successfully. Anyway i have errors opening a lua file, but maybe i should address this in the 'treesitter' repo?

![nvim_lua_errors](https://user-images.githubusercontent.com/57228102/211057560-258cf4cb-aaaa-47f6-8fbc-cb3c315890f4.JPG)

**Comment by steakhutzeee** [comment]
Thank you! Installing unzip solved the issue.
