### ISSUE TITLE
Adding an additional extension to Lua language

### ISSUE THREAD

**Issue by MostHated** [VonHeikemen/lsp-zero.nvim#115]
Hey there,
    Forgive me if this is a silly question, but I am in my first week of using neovim in general, so I am still trying to get all my ducks in a row and figuring everything out. 

My question is, if I have a file which is based on lua, but uses a different file extension, can I just add its extension to a config to get at least basic highlighting and such?

I have this config I put together, but when I open a file with the new extension, the file is not getting any sort of highlighting or showing any indication that the new extension is being used/added as part of the lsp's recognized types.

<details>
<summary>after/plugin/lspzero.lua</summary>

```lua
if vim.g.vscode then
  return
end

vim.opt.signcolumn = 'yes' -- Reserve space for diagnostic icons

local lsp = require('lsp-zero')
lsp.preset('recommended')
lsp.setup()

require('lspconfig')['sumneko_lua'].setup{
      filetypes = { "hwk" }
}
```

</details>

I am guessing that there is probably something silly that I am missing, as I am not getting any errors or anything, it simply does nothing for the extension. If anything could be recommended, I would greatly appreciate it.
Thanks,
-MH

**Comment by VonHeikemen** [comment]
You can add a filetype using a function called [vim.filetype.add](https://neovim.io/doc/user/lua.html#vim.filetype.add()). This a neovim function that is fairly new, think it was added in v0.7.

You can do this:

```lua
vim.filetype.add({
  extension = {
    hwk = 'lua'
  }
})
```

Then the files with the extension `hwk` will be treated as lua files. So the language server for lua and the syntax highlight should work.

The other thing. Calling `lspconfig` like that, after the lsp-zero setup, will remove the configuration lsp-zero sends to the language server. You probably don't want that, a lot of keybindings and commands will stop working.

If you need to configure a language server use the function [.configure()](https://github.com/VonHeikemen/lsp-zero.nvim#configurename-opts).

```lua
vim.opt.signcolumn = 'yes' -- Reserve space for diagnostic icons

local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.configure('sumneko_lua', {
  filestypes = {'hwk', 'lua'}
})

lsp.setup()
```

Is also worth mention that language servers look for particular files to detect the "root dir" of the project. `sumneko_lua` looks for a file `.luarc.json`, its probably  a good idea to add that file to your projects.

**Comment by MostHated** [comment]
Ah, that definitely makes sense about the config order. I will definitely keep that in mind going forward. That seems to have done the trick! 

Thanks for the info about the root rc as well. I added that to my notes. I will try and build up a list of them for my usual languages so I do not forget.
Thanks a bunch for all the useful info, it has been quite helpful. :+1:
