### ISSUE TITLE
Disable highlighting for diagnostics in the background and set undercurl instead of underline

### ISSUE THREAD

**Issue by steakhutzeee** [VonHeikemen/lsp-zero.nvim#116]
Hi, i actually have highlights as per image. What i'm trying to accomplish is to disable any type of highlighting color _in the background_ and only have a red undercurl (if possible) and not an underline under every error/warning etc.
I'm ok with the colors set by treesitter, just do not want the symbols colored in the background.

![highlight](https://user-images.githubusercontent.com/57228102/211176269-e9843475-8e89-47fc-8e43-92cc32387d39.JPG)

This is what i'm trying to do:

![vscode](https://user-images.githubusercontent.com/57228102/211176271-a9ecec8b-ab98-441d-9705-fb07594f9124.JPG)

![if](https://user-images.githubusercontent.com/57228102/211176715-c840ba53-cb22-4374-bb0c-ef9bd03ccb83.JPG)

My current config is:

```
--[lsp/mason]--
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.set_preferences({
  sign_icons = false
})

lsp.ensure_installed({
  'pyright',
  'sumneko_lua',
})

lsp.setup()

--[null-ls/mason-null-ls]--
local null_ls = require("null-ls")

null_ls.setup({
	debug = true,
    sources = {
        null_ls.builtins.formatting.black.with({
          filetypes = {"python"},
        }),
        null_ls.builtins.formatting.isort.with({
          filetypes = {"python"},
          extra_args = {'--profile', 'black', '--skip-gitignore'},
        }),
        null_ls.builtins.diagnostics.flake8.with({
          filetypes = {"python"},
          extra_args = {'--max-line-length', 88, '--select=C,C4,E,E8,F,W,B,B902,B950,N8,A', '--extend-ignore=E203,E501,E722,W503', '--max-complexity', '10'}
        }),
    },
})

require("mason-null-ls").setup({
    ensure_installed = nil,
    automatic_installation = true,
    automatic_setup = false,
})

--[treesitter]--
require'nvim-treesitter.configs'.setup {
  -- A list of parser names, or "all"
  ensure_installed = {"python", "lua", "vim"},
  -- Automatically install missing parsers when entering buffer
  -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
  auto_install = false,
  highlight = {
    enable = true,
  },
}
```

I tried the following without success:

```
vim.api.nvim_set_hl(0,'DiagnosticHint', {})
vim.api.nvim_set_hl(0,'DiagnosticError', {})
vim.api.nvim_set_hl(0,'DiagnosticWarn', {})
vim.api.nvim_set_hl(0,'DiagnosticInfo', {})
```

What could i check?
Thank you!!

**Comment by VonHeikemen** [comment]
I think these are the highlights you want to override.

```
DiagnosticUnderlineError
DiagnosticUnderlineWarn
DiagnosticUnderlineInfo
DiagnosticUnderlineHint
```

**Comment by steakhutzeee** [comment]
> I think these are the highlights you want to override.
> 
> ```
> DiagnosticUnderlineError
> DiagnosticUnderlineWarn
> DiagnosticUnderlineInfo
> DiagnosticUnderlineHint
> ```

Afaik these are just for the underline (no idea how to set an undercurl there).

Where should I disable the colored background for errored etc. symbols?

**Comment by VonHeikemen** [comment]
Underline and undercurl are properties of highlight groups. So you can do this.

```lua
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', {underline = false, undercurl = true})
```

I have no idea if you can actually have different colors for the text and the underline/undercurl.

**Comment by steakhutzeee** [comment]
> ```lua
> vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', {fg = '#73DACA', underline = false, undercurl = true})
> ```

Unfortunately this is not working, i see the same as before. Disabling underline via `vim.diagnostic.config` does not help of course because that disables the underline completely.

**Comment by steakhutzeee** [comment]
I'm almost there, found out that i need to set these in my theme directly or they are overwritten:

```
--[github-theme]--
require('github-theme').setup({
  theme_style = "dark_default",
  --sidebars = {"qf", "vista_kind", "terminal", "packer"},
  dark_sidebar = false,
  comment_style = "NONE",
  overrides = function(c)
    return {
	DiagnosticUnderlineError = {style = "undercurl"},
	DiagnosticUnderlineWarn = {style = "undercurl"},
	DiagnosticUnderlineInfo = {style = "undercurl"},
	DiagnosticUnderlineHint = {style = "undercurl"},
	}
  end
})

I just can't get the undercurl, i still have the underline. But at this point i suppose this discussion should continue on the theme thread.
```

**Comment by VonHeikemen** [comment]
Yes, that might be a terminal thing. I use kitty in linux, undercurl works fine there.
