### ISSUE TITLE
Consider adding mason opt-in to "You might not need lsp-zero"

### ISSUE THREAD

**Issue by itsdeadguy** [VonHeikemen/lsp-zero.nvim#117]
Hi, thank you for creating this project.

In the readme it states that mason is now opt-in. Would it be possible to have a "masonless" example in the section mentioned in the title?

**Comment by VonHeikemen** [comment]
Think I might add it to `Quickstart`. The section "You might not need lsp-zero" is about mason.nvim.

Funny thing is mason.nvim was always opt-in. Just have to choose the preset called `system-lsp`.

**Comment by VonHeikemen** [comment]
Okay. I got something. Is this what you have in mind?

```lua
--- This requires Neovim v0.8 or greater

local lspconfig = require('lspconfig')
local lsp_defaults = lspconfig.util.default_config

-- Add nvim-cmp's capabilities to lspconfig
lsp_defaults.capabilities = vim.tbl_deep_extend(
  'force',
  lsp_defaults.capabilities,
  require('cmp_nvim_lsp').default_capabilities()
)

-- Add a global "On Attach" hook
local lsp_cmds = vim.api.nvim_create_augroup('lsp_cmds', {clear = true})
vim.api.nvim_create_autocmd('LspAttach', {
  desc = 'LSP actions',
  group = lsp_cmds,
  callback = function(event)
    -- Get access to client (if you need it)
    local client = vim.lsp.get_client_by_id(event.data.client_id)

    -- Add your keybindings here...
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, {buffer = event.buf})
  end
})

-- Configure LSP servers
lspconfig.tsserver.setup({})
lspconfig.rust_analyzer.setup({})
```

For the record, this is the kind of boilerplate `lsp-zero` does for you.

**Comment by VonHeikemen** [comment]
That's not exactly what I meant. There's people out there who are basically overriding every single piece of configuration `lsp-zero` sets. They are effectively just using the automatic setup, and they don't know that.

Anyway, I updated the snippet in [LSP section](https://github.com/VonHeikemen/lsp-zero.nvim#lsp) so it shows what happens at the heart of lsp-zero.
