### ISSUE TITLE
Spawning language server fails

### ISSUE THREAD

**Issue by Amparose** [VonHeikemen/lsp-zero.nvim#12]
I have just installed with vim-plug, using "recommended" on Neviom 0.7. After being asked if I want to install a vim LSP when opening my config, I selected yes. When I relaunch and open a vim file I get a console message:

```
Spawning language server with cmd: `vim-language-server` failed. The language server is either not installed, missing from PATH, or not executable.
```

Isn't this plugin meant to manage all of this? Not sure how to fix this.

**Comment by VonHeikemen** [comment]
That was fun... it's a very weird bug. Good news is I think I found the cause... bad news is probably need to reinstall `vimls`.

So, after you get the error message uninstall `vimls` with this.

```vim
:LspUninstall --sync vimls
```

Update `lsp-zero` to download the recent commit ([7f0d541](https://github.com/VonHeikemen/lsp-zero.nvim/commit/7f0d5412747deded419a3a45ee859250b3591085)) and restart neovim. Install `vimls`:

```vim
:LspInstall --sync vimls
```

Hopefully this will download `vimls` with the "right state". At this point you can either start the server manually with:

```vim
:LspZeroSetupServers vimls
```

Or restart  neovim.

**Comment by Amparose** [comment]
Just tried it @VonHeikemen and looks like that fixes the issue. Awesome work and thank you for the fix!
