### ISSUE TITLE
advance-usage tip for mason-null-ls missing a step

### ISSUE THREAD

**Issue by nichtsam** [VonHeikemen/lsp-zero.nvim#123]
https://github.com/VonHeikemen/lsp-zero.nvim/blob/8d12a5057ff116f0a2f1e166a70e62287c901a6f/advance-usage.md?plain=1#L461-L493

According to [`mason-null-ls.nvim`'s document](https://github.com/jay-babu/mason-null-ls.nvim#primary-source-of-truth-is-mason-null-ls),  
I think the code is missing a step ```require 'mason-null-ls'.setup_handlers() -- If `automatic_setup` is true.```
I tested it out and without this line it didn't work properly.

**Comment by VonHeikemen** [comment]
So I added more sections. One `Automatic install` and another for `Automatic setup`.

Automatic install is about making `mason.nvim` install the tools listed in the `sources` option of `null-ls`.

Automatic setup is about making sure `null-ls` knows about the tools you installed with `mason.nvim`.

**Comment by nichtsam** [comment]
Ah, I didn't notice automatic_setup was set to false.

Thanks a lot for the thorough documentation for this part.
