### ISSUE TITLE
Inability to customize nvim-cmp completion window

### ISSUE THREAD

**Issue by neg4n** [VonHeikemen/lsp-zero.nvim#125]
Hey! First of all thanks for creating this plugin! I'm using it in my new _(probably final 😅)_ neovim configuration. 

### The problem

During setting up the `nvim-cmp` i struggled with setting the `window.completion` options. I followed the steps as with `window.documentation` described [here](https://github.com/VonHeikemen/lsp-zero.nvim/blob/main/advance-usage.md#documentation-window) _(which is working fine)_ but it didn't seem to work. I tried some other approaches but still no result.

### The solution

`window.documentation` is set this way:

https://github.com/VonHeikemen/lsp-zero.nvim/blob/8d12a5057ff116f0a2f1e166a70e62287c901a6f/lua/lsp-zero/nvim-cmp-setup.lua#L174-L181

but `window.completion` has missing `.window` in dot notation

https://github.com/VonHeikemen/lsp-zero.nvim/blob/8d12a5057ff116f0a2f1e166a70e62287c901a6f/lua/lsp-zero/nvim-cmp-setup.lua#L183-L185

I'll create a pull request for this soon 🚀

**Comment by VonHeikemen** [comment]
I appreciate the PR, but it's not necessary. When people want to customize nvim-cmp I suggest changing the preset to `lsp-compe` and do this:

```lua
local lsp = require('lsp-zero')
lsp.preset('lsp-compe')

lsp.setup()

vim.opt.completeopt = {'menu', 'menuone', 'noselect'}

local cmp = require('cmp')
local cmp_config = lsp.defaults.cmp_config({
  window = {
    completion = cmp.config.window.bordered()
  }
})

cmp.setup(cmp_config)
```

Now you have control over `cmp`.

**Comment by neg4n** [comment]
Yes it is the way to go. Thanks for help @VonHeikemen and sorry for overlooking this in the docs 🙈
