### ISSUE TITLE
Add a function to call configure on multiple servers with individual configs

### ISSUE THREAD

**Issue by ModProg** [VonHeikemen/lsp-zero.nvim#129]
I imagined something like:
```lua
configure({
  ["first"] = { some_setting = true},
  ["second"] = {another_setting = false}
})
```

**Comment by VonHeikemen** [comment]
I don't see the benefit there.

**Comment by ModProg** [comment]
> I don't see the benefit there.

yeah thinking about it it is probably just my very own preference of being able to set up all servers with a single call instead of needing to call `configure` for every one where I want to change the setting.

I can simply define that function my self it's probably just 5 lines or something like that

**Comment by VonHeikemen** [comment]
Yeah. I'm gonna leave the snippet here, in case someone else is interested.

```lua
local function lsp_configure(list)
  for server_name, opts in pairs(list) do
    require('lsp-zero').configure(server_name, opts)
  end
end
```
