### ISSUE TITLE
Is this correct behavior

### ISSUE THREAD

**Issue by mrheinen** [VonHeikemen/lsp-zero.nvim#131]
I followed the instructions and installed and setup everything. I'm testing using a go or python file, I get the following behavior:

I type "fmt." and get suggestions but if I continue typing the suggestions aren't narrowed down. E.g. Id expect if I type "fmt.A" that I see Append, AppendAll etc.  However when I continue typing I do end up with an append suggestion but only when I type till "fmt.App"

Is this expected behavior or is there perhaps something I need to tweak.
Cheers!

**Comment by VonHeikemen** [comment]
Yes. It is. Each "completion source" triggers after you type a certain amount of characters. You can override this behavior using the `.setup_nvim_cmp()` function.

Here is a snippet that shows the current settings.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.setup_nvim_cmp({
  sources = {
    {name = 'path'},
    {name = 'nvim_lsp', keyword_length = 3},
    {name = 'buffer', keyword_length = 3},
    {name = 'luasnip', keyword_length = 2},
  }
})

lsp.setup()
```

**Comment by mrheinen** [comment]
Sorry for the late reply. Thanks for getting back at me and showing me the configs.

**Comment by igniscyan** [comment]
@VonHeikemen Does specifying a source override all sources? Noticing if I modify a sources keyword length, CMP stops working entirely.
