### ISSUE TITLE
copilot autocomplete not showing when using lsp zero

### ISSUE THREAD

**Issue by baesslerpa** [VonHeikemen/lsp-zero.nvim#137]
i’ve switched recently from manual lsp config to lsp zero default. since then the copilot plugin seems to had stoped working, there are no virtual text suggestions.

**Comment by VonHeikemen** [comment]
If you are using [zbirenbaum/copilot.lua](https://github.com/zbirenbaum/copilot.lua), you can check the solution on this issue: https://github.com/VonHeikemen/lsp-zero.nvim/issues/57

**Comment by brunobmello25** [comment]
If you are using github/copilot.vim and it's not doing inline completion, try running `:Copilot status`. If it says that `<Tab> map has been disabled or is claimed by another plugin` then you should add these lines on your config after the plugin loads:

```
    vim.g.copilot_assume_mapped = true
    vim.g.copilot_no_tab_map = true
```

Then configure a keymap to accept suggestion. In my case I configure <C-u>:

```
    vim.api.nvim_set_keymap("i", "<C-u>", 'copilot#Accept("<CR>")', {
      silent = true,
      expr = true
    })
```

**Comment by baesslerpa** [comment]
@brunobmello25 thx, I think this fixes the issue. i found a similar post, not mentioning the `vim.g.copilot_assume_mapped = true` option
