### ISSUE TITLE
Root directory: Not found. For `eslint` language server

### ISSUE THREAD

**Issue by novito** [VonHeikemen/lsp-zero.nvim#139]
I am having trouble running the `eslint` language server on my project. My project consists of multiple packages, and each package has a `package.json` with a `eslintConfig` key / value.

My LSP zero config is as follows:

```lua
local lsp = require("lsp-zero")

lsp.preset("recommended")

lsp.ensure_installed({
  'tsserver',
  'eslint',
  'sumneko_lua',
})

-- Fix Undefined global 'vim'
lsp.configure('sumneko_lua', {
    settings = {
        Lua = {
            diagnostics = {
                globals = { 'vim' }
            }
        }
    }
})

lsp.set_preferences({
    suggest_lsp_servers = false,
    sign_icons = {
        error = 'E',
        warn = 'W',
        hint = 'H',
        info = 'I'
    }
})

vim.diagnostic.config({
    virtual_text = true,
})

-- See :help lsp-zero-preferences
lsp.set_preferences({
  set_lsp_keymaps = true, -- set to false if you want to configure your own keybindings
  manage_nvim_cmp = true, -- set to false if you want to configure nvim-cmp on your own
})

lsp.setup()
```

And I've also tried with a minimized version;

```lsp
-- Learn the keybindings, see :help lsp-zero-keybindings
-- Learn to configure LSP servers, see :help lsp-zero-api-showcase
local lsp = require('lsp-zero')
lsp.preset('recommended')

-- See :help lsp-zero-preferences
lsp.set_preferences({
  set_lsp_keymaps = true, -- set to false if you want to configure your own keybindings
  manage_nvim_cmp = true, -- set to false if you want to configure nvim-cmp on your own
})

-- (Optional) Configure lua language server for neovim
-- lsp.nvim_workspace()

lsp.setup()
```

The `:LspInfo` shows this:

```lua
 Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: /Users/novito/.local/state/nvim/lsp.log
 Detected filetype:   typescriptreact
 
 1 client(s) attached to this buffer: 
 
 Client: tsserver (id: 1, bufnr: [8])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /Users/novito/Code/myproject/packages/test/test-web
 	cmd:             typescript-language-server --stdio
 
 Other clients that match the filetype: typescriptreact
 
 Config: eslint
 	Refer to :h lspconfig-root-detection for help.
 	filetypes:         javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx, vue, svelte, astro
 	root directory:    Not found.
 	cmd:               vscode-eslint-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   eslint/probeFailed, eslint/openDoc, eslint/noLibrary, eslint/confirmESLintExecution
 
 Configured servers list: sumneko_lua, tsserver, eslint
```

On the other hand, if I add a `.eslintrc.js` file in the directory of the file I'm editing, it properly finds the root directory. So, it seems the problem is with finding the eslint configuration in the `package.json`. 

Lastly, if I start `nvim` from one of the specific packages, the root directory gets properly set, but If I start it from the very top root directory (where all the packages are children), the root directory can't be found. So, it looks to me like the root_directory is set up ONCE on initialization, and if I've started nvim at the top level of the project, then even if later open a file at a deeper package, that root directory is not updated. 

Is this an expected behavior? Shouldn't the root directory keep updating depending on the file that is currently opened?

**Comment by VonHeikemen** [comment]
> So, it seems the problem is with finding the eslint configuration in the package.json.

It should find it. In fact, it runs this function.

```lua
require('lspconfig').util.find_package_json_ancestor(vim.fn.expand('%:p:h'))
```

If that returns a path it'll try to read the package.json located there.

> Shouldn't the root directory keep updating depending on the file that is currently opened?

No. Is always the same.

**Comment by novito** [comment]
@VonHeikemen is not finding it. I ended up downloading the `nvim-lspconfig` and modifying its code so that it can properly find it.

**Comment by novito** [comment]
@VonHeikemen I see the issue. I am working on a multi-module app, which has multiple projects with different package.json. When I navigate around the projects, it seems that the language server root directory doesn't get updated. I will research if this is expected or not.

**Comment by VonHeikemen** [comment]
> When I navigate around the projects, it seems that the language server root directory doesn't get updated. I will research if this is expected or not.

That is the expected behavior. The root directory does not update.
