### ISSUE TITLE
How to check if Overridden Settings of Server are Working

### ISSUE THREAD

**Issue by jollySleeper** [VonHeikemen/lsp-zero.nvim#141]
Hi @VonHeikemen,

I was trying to disable the "Undefined Global Vim" Diagnostic using lua-language-server. But it doesn't seem to work for some reason.
Could you help?

![image](https://user-images.githubusercontent.com/87367804/216078032-6bd6624c-f627-42c3-9fd7-1b67c11a79f2.png)

Here is the snippet of code I'm using.

**Comment by jollySleeper** [comment]
Also, the Print statement doesn't seem to work but it was working with Intelephense.

**Comment by VonHeikemen** [comment]
The server name must match one of this list: [server configurations](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#configurations).

For lua is `sumneko_lua`. And actually in lsp-zero there is a function called `.nvim_workspace`, it configures that server for you.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.nvim_workspace()

lsp.setup()
```

**Comment by jollySleeper** [comment]
Ahh, My bad.
Sorry & Thank You.

I used "lua-language-server" as it was stated like that in Mason. But thanks for the clarification :+1: 

One More thing which is not related to this issue but using `lsp.configure()` can we append to a variable instead of overriding it?

**Comment by jollySleeper** [comment]
```
local lsp = require('lsp-zero')
lsp.preset('recommended')

local custom_conf = {
    -- Configuring PHP Intelephense
    ["intelephense"] = {
        settings = {
            intelephense = {
                -- Writing Whole Stubs as configure() function Overrides default values :(
                -- Need to Add Stub for Flawless Integration of Intelephense in Plugin Folder
                stubs = {
                    "apache", "bcmath", "bz2", "calendar", "com_dotnet", "Core", "ctype", "curl",
                    "date", "dba", "dom", "enchant", "exif", "FFI", "fileinfo", "filter", "fpm", "ftp",
                    "gd", "gettext", "gmp", "hash", "iconv", "imap", "intl", "json", "ldap", "libxml",
                    "mbstring", "meta", "mysqli", "oci8", "odbc", "openssl", "pcntl", "pcre", "PDO",
                    "pdo_ibm", "pdo_mysql", "pdo_pgsql", "pdo_sqlite", "pgsql", "Phar", "posix",
                    "pspell", "random", "readline", "Reflection", "session", "shmop", "SimpleXML",
                    "snmp", "soap", "sockets", "sodium", "SPL", "sqlite3", "standard", "superglobals",
                    "sysvmsg", "sysvsem", "sysvshm", "tidy", "tokenizer", "xml", "xmlreader",
                    "xmlrpc", "xmlwriter", "xsl", "Zend OPcache", "zip", "zlib",
                    -- Custom Stub
                    "/var/www/html/test/ap.infogalore.net/", -- For ArbPlugin
                }
            }
        }
    },
};

local function lsp_configure(list)
  for server_name, opts in pairs(list) do
    lsp.configure(server_name, opts);
  end
end

lsp_configure(custom_conf)

lsp.setup();
```

For adding my custom stub I'm required to copy all the default stubs provided by Intelephense and add my custom stub to it.

So, is there anyway to apped to `intelephense.settinngs.intelephense.stub` instead of over-riding the default value?

**Comment by jollySleeper** [comment]
Didn't get you but there isn't a way to append right?

Are you saying that there are no defaults provided to Settings?

**Comment by VonHeikemen** [comment]
Maybe that's the default in the server's implementation.

This is the default the `nvim-lspconfig` uses: https://github.com/neovim/nvim-lspconfig/blob/700eda91316a876757bf306fd709fde75aadb36a/lua/lspconfig/server_configurations/intelephense.lua#L11

**Comment by jollySleeper** [comment]
> Maybe that's the default in the server's implementation.
> 
> This is the default the `nvim-lspconfig` uses: https://github.com/neovim/nvim-lspconfig/blob/700eda91316a876757bf306fd709fde75aadb36a/lua/lspconfig/server_configurations/intelephense.lua#L11

Yep, that maybe the default in the server's implementation. So, is there any way to append to that list or no?

**Comment by VonHeikemen** [comment]
You'll need to read the server's documentation to figure that out.

I can't think of anything.

**Comment by jollySleeper** [comment]
Okay, no problem.
Thank You So Much 

Your Plugin is much appreciated :heart:
