### ISSUE TITLE
Option to define LSP methods with telescope

### ISSUE THREAD

**Issue by otavioschwanck** [VonHeikemen/lsp-zero.nvim#144]
Would be awesome to have the telescope lsp actions with easy configuration like:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/9551316/216737151-20475bee-5ba0-4015-a971-0c0d833e73d1.png">

**Comment by VonHeikemen** [comment]
I don't understand. I mean, you can create normal keybindings.

```lua
vim.keymap.set('n', '<leader>li', '<cmd>Telescope lsp_implementations<cr>')
```

**Comment by otavioschwanck** [comment]
> I don't understand. I mean, you can create normal keybindings.
> 
> ```lua
> vim.keymap.set('n', '<leader>li', '<cmd>Telescope lsp_implementations<cr>')
> ```

the lsp zero plugin defines on_attach commands such as gd, gr, etc..  But it uses the default LSP functions.

would be awesome to define that on_attach, it defines the telescope alternatives instead the default LSP functions

**Comment by VonHeikemen** [comment]
This should work.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.on_attach(function(client, bufnr)
  local opts = {buffer = bufnr}

  vim.keymap.set('n', 'gi', '<cmd>Telescope lsp_implementations<cr>', opts)
end)

lsp.setup()
```

**Comment by otavioschwanck** [comment]
Worked, thanks
