### ISSUE TITLE
Is it possible to register events in cmp?

### ISSUE THREAD

**Issue by gambonny** [VonHeikemen/lsp-zero.nvim#145]
Can `nvim-cmp` events be registered (https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L221) using `lsp-zero`?, I need this bc I want to automatically add a set of parenthesis if option selected is a method.

This can be done with the help of the [nvim-autopairs](https://github.com/windwp/nvim-autopairs) plugin like this:
```lua
-- If you want insert `(` after select function or method item
    local cmp_autopairs = require('nvim-autopairs.completion.cmp')
    local cmp = require('cmp')
    cmp.event:on(
      'confirm_done',
      cmp_autopairs.on_confirm_done()
    )
```

I tried to make it work by using the "lsp-compe" preset and adding the event but it didn't work.

```lua
local cmp = require('cmp')

local cmp_config = lsp.defaults.cmp_config({
  sources = {
    { name = 'path' },
    { name = 'nvim_lsp', keyword_length = 3 },
    { name = 'buffer', keyword_length = 3 },
    { name = 'luasnip', keyword_length = 2 },
  },
})

local cmp_autopairs = require('nvim-autopairs.completion.cmp')
cmp.event:on('confirm_done', cmp_autopairs.on_confirm_done())

cmp.setup(cmp_config)
```

pdt: thanks for this wonderful plugin.

**Comment by VonHeikemen** [comment]
Yes, events work fine. I would recommend doing it after lsp-zero.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.setup()

local cmp = require('cmp')

vim.g.testing_cmp_event = 'NOP'

cmp.event:on('confirm_done', function(evt)
  if evt.entry then
    vim.g.testing_cmp_event = 'IT WORKS'
  else
    vim.g.testing_cmp_event = 'Yes. Everything is good'
  end
end)
```

After you confirm any entry you should be able to print the content of the variable `testing_cmp_event`.

```vim
:echo testing_cmp_event
```

**Comment by gambonny** [comment]
yes, they work just fine, autopairs is still not working for me but at least now I know that it's not because of this. Thanks for the answer.
