### ISSUE TITLE
[Noob Question] Is it possible to use Coc.nvim with lsp-zero vs nvim-cmp?

### ISSUE THREAD

**Issue by igniscyan** [VonHeikemen/lsp-zero.nvim#152]
I've been having a lot of issues with nvim-cmp and the Tailwindcss language server. It seems as though it's a known issue right now that using the language server without heavily modifying the settings (and honestly, gimping its usefulness quite a bit) will lead to quite a large amount of stuttering within nvim.

After spending way too much time trying to resolve it, I think I'm just going to switch over to Coc.nvim which provides a less hair-pulling experience out of the box. Is it possible to configure Lsp-Zero to use Coc for its completion vs nvim-cmp? If so, how would I go about doing that?

I apologize if this isn't the appropriate place to post this. I'm just making the switch over to Nvim this week and trying to get my setup to be a little more productive.

**Comment by VonHeikemen** [comment]
Not that I know of.
