### ISSUE TITLE
LSP-Kind

### ISSUE THREAD

**Issue by paulfrische** [VonHeikemen/lsp-zero.nvim#153]
Hello there,
first of all: thank you for building this nice plugin which made my config much cleaner!
I use LSP-Kind to make cmp more appealing and thought that integrating it into lsp-zero would be a nice idea to enable more people to use it. But before starting to work on it and make a PR I wanted to know if this is something you would merge.
I would suggest to make it opt-in because it will introduce lsp-kind as a new dependency which would break peoples config if it was enabled by default.
Have a Great Day and Happy Hacking!

**Comment by VonHeikemen** [comment]
I wouldn't merge. But you can add a section in [advance usage](https://github.com/VonHeikemen/lsp-zero.nvim/blob/main/advance-usage.md) showing how to integrate them.

**Comment by paulfrische** [comment]
May I ask why?
(No worries, I don't want to start a discussion about it. After all it's your project.)

**Comment by VonHeikemen** [comment]
Don't want to add more dependencies. I'm actually trying to find ways to reduce them without breaking people's config.
