### ISSUE TITLE
Unable to configure CMP sources

### ISSUE THREAD

**Issue by igniscyan** [VonHeikemen/lsp-zero.nvim#154]
When using setup_nvim_cmp() and defining sources, I am getting issues when trying to redefine keyword length. 

Screenshot of the configuration
![image](https://user-images.githubusercontent.com/26984470/218516969-d7e94215-f472-4b1d-bca8-97ed4d959ba0.png)

CmpStatus output
![image](https://user-images.githubusercontent.com/26984470/218516038-2c17a0bb-7f41-40c3-9947-c38582747688.png)

However, if I leave the sources field empty, this happens:
![image](https://user-images.githubusercontent.com/26984470/218516717-f0d768bb-5140-455d-b2c1-3702f6f90e39.png)

Trying to specify nvim_lsp:tailwindcss results in it not being found.

Any idea what is going on here?

**Comment by VonHeikemen** [comment]
All the sources you define in `.setup_nvim_cmp` are plugins. Now, do you have a source installed for tailwindcss?

**Comment by igniscyan** [comment]
I do, I installed it using LspInstall. Mason shows it as being an installed LS

![image](https://user-images.githubusercontent.com/26984470/218520668-9c7be0c3-62be-477e-897a-d191e85b8e09.png)


If I don't include any sources in the setup, it loads correctly. If I use the default source listing provided (path, nvim_lsp, buffer, luasnip), it ceases to load.

**Comment by VonHeikemen** [comment]
No. That's a language server. I meant a plugin like [cmp-buffer](https://github.com/hrsh7th/cmp-buffer).

What you see there that says `nvim_lsp:tailwindcss` is just [cmp-nvim-lsp](https://github.com/hrsh7th/cmp-nvim-lsp). And that source is this one:

```lua
{name = 'nvim_lsp', keyword_length = 3}
```

**Comment by igniscyan** [comment]
> No. That's a language server. I meant a plugin like [cmp-buffer](https://github.com/hrsh7th/cmp-buffer).
> 
> What you see there that says `nvim_lsp:tailwindcss` is just [cmp-nvim-lsp](https://github.com/hrsh7th/cmp-nvim-lsp). And that source is this one:
> 
> ```lua
> {name = 'nvim_lsp', keyword_length = 3}
> ```

Ah... I see now. As you can tell, I'm pretty awful at this stuff. Thank you for the information.

Is there a way to modify the `keyword_length` _just_ for Tailwindcss? I'm assuming that would require cmp-nvim-lsp directly?

**Comment by VonHeikemen** [comment]
I don't think is possible. The documentation for `cmp-nvim-lsp` doesn't have anything to configure that per server.

**Comment by igniscyan** [comment]
> I don't think is possible. The documentation for `cmp-nvim-lsp` doesn't have anything to configure that per server.

Looked into it more and you're correct. I've seen examples of this in people's dotfiles but it actually does nothing. I appreciate your help, sorry for the issues.
