### ISSUE TITLE
Seems like this commit broke lsp keybindings on my config [40819a6]

### ISSUE THREAD

**Issue by elvisgastelum** [VonHeikemen/lsp-zero.nvim#155]
Hello, since yesterday i noticed a lot of keybindings for lsp was not working on my config and idk why, so i research what part of my config was doing this, and finally for some reason this commit ```40819a6b1cc6b0fa9c936fd2e91c625e6d15f791``` is doing that.

I'm using lazy nvim as a package manager so i just point to one commit before ```494cff89ded409265c867411ee18f09673601873``` and everything begin to work again

lsp-zero.lua file
```lua
return {
	'VonHeikemen/lsp-zero.nvim',
	commit = '494cff89ded409265c867411ee18f09673601873',
	dependencies = {
		-- LSP Support
		{ 'neovim/nvim-lspconfig' }, -- Required
		{ 'williamboman/mason.nvim' }, -- Optional
		{ 'williamboman/mason-lspconfig.nvim' }, -- Optional

		-- Autocompletion
		{ 'hrsh7th/nvim-cmp' }, -- Required
		{ 'hrsh7th/cmp-nvim-lsp' }, -- Required
		{ 'hrsh7th/cmp-buffer' }, -- Optional
		{ 'hrsh7th/cmp-path' }, -- Optional
		{ 'saadparwaiz1/cmp_luasnip' }, -- Optional
		{ 'hrsh7th/cmp-nvim-lua' }, -- Optional

		-- Snippets
		{ 'L3MON4D3/LuaSnip' }, -- Required
		{ 'rafamadriz/friendly-snippets' }, -- Optional
	},
	config = function()
		vim.opt.signcolumn = 'yes'

		-- Learn the keybindings, see :help lsp-zero-keybindings
		-- Learn to configure LSP servers, see :help lsp-zero-api-showcase
		local lsp = require('lsp-zero')
		lsp.preset('recommended')

		-- (Optional) Configure lua language server for neovim
		lsp.nvim_workspace()

		lsp.setup()
	end
}
```

OS: MacOS Ventura 13.0
NVIM v0.9.0-dev-2090+ge1f03c481-dirty
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by VonHeikemen** [comment]
What happens in that commit is the lsp keybindings in lsp-zero no longer override your keybindings.

**Comment by VonHeikemen** [comment]
Did you inspect the keybinding? This command `:map gd` should show:

```lua
n  gd          *@<Cmd>lua vim.lsp.buf.definition()<CR>
```

**Comment by VonHeikemen** [comment]
Oh, it could which-key adding keybindings for `g`.

**Comment by VonHeikemen** [comment]
I've added the option `preserve_mappings`. You can do this.

```lua
local lsp = require('lsp-zero').preset({
  name = 'recommended',
  set_lsp_keymaps = {preserve_mappings = false}
})

lsp.nvim_workspace()

lsp.setup()
```

**Comment by Jendker** [comment]
> I've added the option `preserve_mappings`. You can do this.
> 
> ```lua
> local lsp = require('lsp-zero').preset({
>   name = 'recommended',
>   set_lsp_keymaps = {preserve_mappings = false}
> })
> 
> lsp.nvim_workspace()
> 
> lsp.setup()
> ```
This also fixes lsp-zero.nvim not working together with which-key.nvim. Thank you!

**Comment by xTayEx** [comment]
> I've added the option `preserve_mappings`. You can do this.
> 
> ```lua
> local lsp = require('lsp-zero').preset({
>   name = 'recommended',
>   set_lsp_keymaps = {preserve_mappings = false}
> })
> 
> lsp.nvim_workspace()
> 
> lsp.setup()
> ```

This works well for me! Thank you!
