### ISSUE TITLE
Override default mapping not applied with argument

### ISSUE THREAD

**Issue by willswats** [VonHeikemen/lsp-zero.nvim#156]
In the `v.1x` branch, when attempting to override the default mapping to make `cmp` only confirm explicitly selected items, it's not applied.

To reproduce:
1. Add the below snippet.
2. Type something to make `cmp` appear.
3. Press enter.

```lua
lsp.setup_nvim_cmp({
  mapping = lsp.defaults.cmp_mappings({
    ['<CR>'] = cmp.mapping.confirm({ select = false }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
  })
})
```

This occurs with `cmp.mapping.preset.insert` as well:

```lua
lsp.setup_nvim_cmp({
  mapping = cmp.mapping.preset.insert({
    ['<CR>'] = cmp.mapping.confirm({ select = false }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
  })
})
```

**Comment by VonHeikemen** [comment]
The first item is always preselected, that's why it confirms when `select = false`.

To make the selection manually you have to do this.

```lua
lsp.setup_nvim_cmp({
  preselect = 'none',
  completion = {
    completeopt = 'menu,menuone,noinsert,noselect'
  },
})
```

**Comment by willswats** [comment]
That works, thank you. Perhaps add that to the [Autocompletion](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v1.x/doc/md/autocomplete.md) docs?
