### ISSUE TITLE
Type annotation

### ISSUE THREAD

**Issue by toondaey** [VonHeikemen/lsp-zero.nvim#157]
I just recently migrated to neovim from VSCode and I was wondering if it is possible to get the automated type annotations as in VSCode with rust lang?

**Comment by VonHeikemen** [comment]
I've never used VSCode with rust. Can you explain with more details?

**Comment by toondaey** [comment]
Something like what we have here.
<img width="676" alt="Screenshot 2023-02-15 at 13 07 29" src="https://user-images.githubusercontent.com/17554487/219023598-d21aa6e4-aa6d-4c69-b7de-fce0d6fd2795.png">

**Comment by VonHeikemen** [comment]
Ok. Neovim calls them "inlay hints". I think you have to configure them on a per server basis. You'll need to figure out which server has support for them. And even then you can't have it exactly like that (yet). Right now you can only see the types at the end of the line.

**Comment by toondaey** [comment]
Ok. I'm not sure how to configure it but could you share a guide on how to go about this?

**Comment by VonHeikemen** [comment]
Probably need this: [inlay-hints.nvim](https://github.com/simrat39/inlay-hints.nvim)

**Comment by toondaey** [comment]
Thanks! I'll take a look at that.

**Comment by toondaey** [comment]
I've got it working. Thanks for the assist.
