### ISSUE TITLE
After update hotkeys stoped working

### ISSUE THREAD

**Issue by held-m** [VonHeikemen/lsp-zero.nvim#158]
Hi. Thank you for the plugin.

I use mason and config from README

It looks like lsp-zero works except for hotkeys. 

NVIM v0.8.1
Build type: MinSizeRel
LuaJIT 2.1.0-beta3

For now, I add in my "keybinds.lua" hotkeys from https://github.com/VonHeikemen/lsp-zero.nvim/blob/main/lua/lsp-zero/server.lua (255:269) with "lsp" and "diagnostic" variables and it works. 

And I'm not sure the reason is to update nvim. Maybe another plugin was updated and broke something. 
My configs are here https://github.com/held-m/nvim-golang/tree/dev

**Comment by VonHeikemen** [comment]
In a recent update I made it so lsp-zero respect the user's keybindings. If a particular shorcut is "taken" lsp-zero will not override it.

It looks like some keybindings don't work because `which-key` sets them up at startup. So you can try this.

```lua
local lsp = require('lsp-zero').preset({
  name = 'minimal',
  manage_nvim_cmp = true,
  suggest_lsp_servers = false,
  set_lsp_keymaps = {preserve_mappings = false},
})

lsp.nvim_workspace()

lsp.setup()
```

**Comment by held-m** [comment]
Thank you. It worked.
