### ISSUE TITLE
Mason not working

### ISSUE THREAD

**Issue by samuel-cavalcanti** [VonHeikemen/lsp-zero.nvim#159]
Hi, I have this error when the Lsp-zero is trying to install a new  lsp server:

![image](https://user-images.githubusercontent.com/24573157/219472745-1d828649-ce63-454f-9d09-4224a97e0291.png)

my packer config:
![image](https://user-images.githubusercontent.com/24573157/219474792-9561fc9c-a070-4fcd-ad95-b8c92917ab92.png)

this is my config:

![image](https://user-images.githubusercontent.com/24573157/219473441-c9a5e37d-0ab9-4b88-98ff-a97edccc61f7.png)

I was able to install manually, but  for some reason  the server isn't configured 

![image](https://user-images.githubusercontent.com/24573157/219473775-783fe984-dd6b-4b14-beab-66829f8bb531.png)

**Comment by VonHeikemen** [comment]
Check that mason.nvim knows about the server. Execute this command.

```lua
:lua = require('mason-lspconfig').get_installed_servers()
```

It should list every server installed using mason.nvim.

**Comment by samuel-cavalcanti** [comment]
> Check that mason.nvim knows about the server. Execute this command.
> 
> ```lua
> :lua = require('mason-lspconfig').get_installed_servers()
> ```
> 
> It should list every server installed using mason.nvim.
![image](https://user-images.githubusercontent.com/24573157/219514033-b6d1af82-a323-4135-b6d6-57485c619721.png)

I have installed the lsp servers, but for some reason the lsp-zero doesn't  configure  the servers. 

these are my  nvim config files: https://github.com/samuel-cavalcanti/neovim_config/
and these are the configuration files that it uses the lsp-zero: 
- [plugin/lsp.lua](https://github.com/samuel-cavalcanti/neovim_config/blob/main/after/plugin/lsp.lua)
- [plugin/rust-tools.lua](https://github.com/samuel-cavalcanti/neovim_config/blob/main/after/plugin/rust-tools.lua)
- [plugin/flutter.lua](https://github.com/samuel-cavalcanti/neovim_config/blob/main/after/plugin/flutter.lua)
- [plugin/packer.lua](https://github.com/samuel-cavalcanti/neovim_config/blob/main/lua/startup/packer.lua#L34)

I'm sure that my packer config is the same of the readme,  and flutter, rust are on  __skip_server_setup__.
One more thing, for some reason the lsp-zero doesn't  setup mason, so  I  create this configuration: [plugin/mason.lua](https://github.com/samuel-cavalcanti/neovim_config/blob/main/after/plugin/mason.lua)
```lua
-- mason.lua
require("mason").setup()
require("mason-lspconfig").setup()
```

I added pyright to __setup_servers__ and now the pyright  is configured
```lua
-- ignore rust and dart servers
lsp_zero.skip_server_setup({ 'rust_analyzer', 'dartls' })
-- now works
lsp_zero.setup_servers({ 'pyright' })
```

**Comment by VonHeikemen** [comment]
I cloned your config, deleted the mason config, added the `ensure_installed` function with pyright and... everything worked fine.

I think maybe mason is not loading properly or there are some weird caching issues.

Delete or comment out the mason setup calls in `mason.lua`. Then add this line before you require lsp-zero.

```lua
vim.pretty_print(package.loaded['mason.api.command'])
```

It should print `nil`.

**Comment by samuel-cavalcanti** [comment]
> I cloned your config, deleted the mason config, added the `ensure_installed` function with pyright and... everything worked fine.
> 
> I think maybe mason is not loading properly or there are some weird caching issues.
> 
> Delete or comment out the mason setup calls in `mason.lua`. Then add this line before you require lsp-zero.
> 
> ```lua
> vim.pretty_print(package.loaded['mason.api.command'])
> ```
> 
> It should print `nil`.
![image](https://user-images.githubusercontent.com/24573157/219621391-7ee4e5d9-9287-4fa2-8598-1d5ddf3da489.png)

how to clean the cache ?

**Comment by samuel-cavalcanti** [comment]
I deleted my .local/share/nvim   and  plugin/packer_compiled.lua . 
After install the packer e run PackerSync, I have the same bug.
lsp-zero didn't find the mason and  now cannot  configure  the lua server  
![image](https://user-images.githubusercontent.com/24573157/219627277-917de659-8c7a-4350-88de-2eb796c8de76.png)

**Comment by VonHeikemen** [comment]
I think I figure out the problem. I changed the defaults so now lsp-zero will try to load mason.nvim if you have it installed.

**Comment by samuel-cavalcanti** [comment]
> I think I figure out the problem. I changed the defaults so now lsp-zero will try to load mason.nvim if you have it installed.
Now it works  !
