### ISSUE TITLE
Status line

### ISSUE THREAD

**Issue by mightyiam** [VonHeikemen/lsp-zero.nvim#16]
I've looked into what it would take to have lsp related info such as server status and diagnostics in a status line and it seems like a lot of hooking up work. Perhaps another task for lsp-zero?

**Comment by VonHeikemen** [comment]
I believe [lsp-status.nvim](https://github.com/nvim-lua/lsp-status.nvim) should help you with this. It has like a bunch of helper functions that query the language server. You can make it work even without a statusline plugin.

```lua
---
-- LSP
---
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.on_attach(function(client, bufnr)
  vim.b.lsp_attached = true
end)

lsp.setup()

---
-- Statusline
---
local lsp_status = require('lsp-status')
lsp_status.config({
  status_symbol = '',
  indicator_errors = '✘',
  indicator_warnings = '▲',
  indicator_info = '',
  indicator_hint = '⚑',
  indicator_ok = '',
})

function LspStatus()
  if vim.b.lsp_attached then
    return lsp_status.status()
  end

  return ''
end

vim.opt.statusline = '%=%{v:lua.LspStatus()}%r%m %l:%c %p%% %y '
```

To see notification reports of the server status I use [fidget.nvim](https://github.com/j-hui/fidget.nvim). This one has good defaults (for the server I have used), so I only add this.

```lua
require('fidget').setup({})
```

**Comment by mightyiam** [comment]
Thank you, @VonHeikemen . I ended up using fidget-nvim only.
