### ISSUE TITLE
Setting pyright extraPaths does not work

### ISSUE THREAD

**Issue by delijati** [VonHeikemen/lsp-zero.nvim#160]
Hi,

i followed your example and tried to set the `extraPaths` variable [1]. Unfortunately pyright seams to not pick up this path aka completions does not work. But if i set it via `pyproject.toml` [2] the completion does work.

[1]
```
local lsp = require('lsp-zero')

lsp.use('pyright', {
  settings = {
    python = {
      analysis = {
        extraPaths = {'/path/to/my/dependencies/src'},
      }
    }
  }
})
```

[2]
```
❯ cat pyproject.toml 
[tool.pyright]
extraPaths = ["/path/to/my/dependencies/src", ]
```

**Comment by VonHeikemen** [comment]
There was problem with the setup in lsp-zero. Hopefully the update can fix your issue.

**Comment by delijati** [comment]
I updated but the error persists. is there a way to get debug messages? Also is it possible to set the extraPaths on runtime?

**Comment by VonHeikemen** [comment]
I've added a new function to inspect the settings of a language server.

Try this command in a python file after the server is attached to a buffer.

```lua
:lua require('lsp-zero.check').inspect_settings('pyright')
```

To check the logs use the command `:LspLog`
