### ISSUE TITLE
Is there a way to remove every border

### ISSUE THREAD

**Issue by Meilky** [VonHeikemen/lsp-zero.nvim#165]
I would like took remove every border style.
I was able to remove border for diagnostic and for cmp documentation, but not for hover doc and function signature help.

Is it possible to overwrite or remove every border style?

PS: I'm blocked here :
https://github.com/VonHeikemen/lsp-zero.nvim/blob/64c065a455f9e0d4e7d0ab263ae01be2855b4590/lua/lsp-zero/server.lua#L192-L202

**Comment by VonHeikemen** [comment]
Never thought I'd see the day.... 

Anyway, right now what you can do is override these settings after the lsp-zero's setup. 

```lua
vim.lsp.handlers['textDocument/hover'] = vim.lsp.with( 
  vim.lsp.handlers.hover, 
  {border = 'none'} 
) 

vim.lsp.handlers['textDocument/signatureHelp'] = vim.lsp.with( 
  vim.lsp.handlers.signature_help, 
  {border = 'none'} 
)
```
