### ISSUE TITLE
luasnip auto expand snippet not working with lsp-zero

### ISSUE THREAD

**Issue by sho-87** [VonHeikemen/lsp-zero.nvim#168]
I have lsp-zero set up to handle primarily the lsp side of things, and split luasnip and nvim-cmp off to different files and configured separately. config files:

- lsp-zero: https://github.com/sho-87/dotfiles/blob/master/nvim/lua/plugins/modules/lsp-zero.lua
- nvim-cmp: https://github.com/sho-87/dotfiles/blob/master/nvim/lua/plugins/modules/nvim-cmp.lua
- luasnip: https://github.com/sho-87/dotfiles/blob/master/nvim/lua/plugins/modules/luasnip.lua

everything is working, but I cannot get autosnippets to expand automatically. I have `enable_autosnippets = true` set in my luasnip config, and I have them set up temporarily to show up in the completion list (which they do). The only problem is that theyre not auto expanding when I finish writing the text

when I turn off lsp-zero, and leave the rest of my configs as they are, autoexpansion works fine.

I'm guessing either lsp-zero is setting some defaults for luasnip that somehow disables auto expand, or I'm not correctly setting the options for luasnip when lsp-zero is involved 

thoughts?

**Comment by VonHeikemen** [comment]
That will be my guess too, lsp-zero is overriding your config for luasnip.

I've added a new option: `manage_luasnip`. If you set that to false, lsp-zero will not setup luasnip.

**Comment by sho-87** [comment]
works perfectly, thanks!
