### ISSUE TITLE
snippet is added at the end of char instead of replace it.

### ISSUE THREAD

**Issue by NateCC0902** [VonHeikemen/lsp-zero.nvim#169]
When I type `so` and Enter

Expected: System.out.println();

But got: **so**System.out.println();

(my setup: https://github.com/NateCC0902/nvim/blob/main/after/plugin/lsp.lua)

**Comment by rawat-sahil** [comment]
@NateCC0902 did you manage to fix this issue. I am having the same issue :smiling_face_with_tear:
