### ISSUE TITLE
Resetting the status of a language auto-install?

### ISSUE THREAD

**Issue by MostHated** [VonHeikemen/lsp-zero.nvim#170]
Hey there, I am not sure exactly who the best team to ask about this happens to be. If I opened a file for a language in which I had not yet installed and was prompted to install the language server for it, but didn't notice and accidentally closed the prompt, is there a way to reset the status of this so that I can have it shown again so I can see the list of available language servers again? 

I was not sure if that actual detection was done by Mason, Treesitter, etc, so I am not quite sure who to ask, unfortunately. If you happen to know, or might be able to point me in the right direction, I would greatly appreciate it.

Thanks,
-MH

**Comment by VonHeikemen** [comment]
Those suggestions are a feature of [mason-lspconfig](https://github.com/williamboman/mason-lspconfig.nvim). To see them again just execute the command `:LspInstall`.

The only thing lsp-zero does is ask the first question, the one that says "would you like to install a server...."

**Comment by MostHated** [comment]
Ok thanks, I do appreciate it. That got me squared away. :+1:
