### ISSUE TITLE
2.x preset documentation

### ISSUE THREAD

**Issue by Jendker** [VonHeikemen/lsp-zero.nvim#173]
2.x branch preset [documentation](https://github.com/VonHeikemen/lsp-zero.nvim/blob/ce7ee141e9a1a374dd25a999ad1e6b2f868c0e66/doc/md/autocomplete.md?plain=1#L38-L46) mentions plugins which are not listed in the installation snippets. Maybe it would make sense to list them at least as optional?

**Comment by VonHeikemen** [comment]
It does make sense to add them in the readme, but install alone won't make them work. They require extra configuration code. Let me think how can I add them.
