### ISSUE TITLE
Could the docs explain how to call a language-server specific method?

### ISSUE THREAD

**Issue by githorse** [VonHeikemen/lsp-zero.nvim#179]
I'd like to map [`tsserver`'s organize imports method](https://github.com/typescript-language-server/typescript-language-server#organize-imports) to a keybinding, but after reading the docs I'm still not sure how to go about that. Could the docs be augmented with an example of a keybinding back to a specific server method like that (ideally, a keybinding that applies only when `tsserver` is active)? 

```
lsp.on_attach(function(client, bufnr)
  local opts = {buffer = bufnr, remap = false}

  vim.keymap.set("n", "gd", function() vim.lsp.buf.definition() end, opts)
  ...
  
  -- *** new keymap here (does not work) ***
  vim.keymap.set("n", "<C-i>", function() vim.lsp.buf.organize_imports() end, opts)
end)
```

Seems like this might be pretty broadly useful documentation. (Apologies if I it's there already and I missed it.)

**Comment by VonHeikemen** [comment]
That's a fairly advance topic, I'm not sure if every command can be handled in a generic way.

In this case it's better to use [typescript.nvim](https://github.com/jose-elias-alvarez/typescript.nvim), they handle the request for those commands.

Here is an example config.

```lua
local lsp = require('lsp-zero').preset({
  name = 'minimal',
  set_lsp_keymaps = true,
  manage_nvim_cmp = true,
  suggest_lsp_servers = false,
})

-- Ignore tsserver, it will be configured by typescript.nvim
lsp.skip_server_setup({'tsserver'})

lsp.setup()

require('typescript').setup({
  server = {
    on_attach = function(client, bufnr)
      -- You can find more commands in the documentation:
      -- https://github.com/jose-elias-alvarez/typescript.nvim#commands

      vim.keymap.set('n', '<leader>ci', '<cmd>TypescriptOrganizeImports<cr>', {buffer = bufnr})
    end
  }
})
```
