### ISSUE TITLE
Problems with tsserver

### ISSUE THREAD

**Issue by kuchejak** [VonHeikemen/lsp-zero.nvim#184]
Hello,
I'm not really sure if this is lsp-zero problem; if it is not, feel free to close the issue. I'm a nvim beginner, so things are quite confusing for me. 

I'm trying to setup nvim for React Native development, and I'm currently using lsp-zero (from main branch) for lsp setup. `tsserver` seems to work, but I have two problems with it:

## 1. No suggestions from external libraries

I have added some external libraries (using npm) to the project, but they are not being suggested when typing. I have checked VS Code and the suggestions work just fine (see pictures)
VS Code (expected behavior):
![code](https://user-images.githubusercontent.com/94016085/225865443-279a0ba9-4251-4d5f-b4ef-a36f1f641d17.png)
nvim:
![nvim](https://user-images.githubusercontent.com/94016085/225865417-6b847d08-9150-4261-87fb-74fc58c09bac.png)
![lspinfo](https://user-images.githubusercontent.com/94016085/225865461-79b2982c-dfdc-4654-8fd2-8ef26a5691e0.png)

## 2. No error highlighting

In the code bellow there is a syntax error, but nvim does not pick it up, VS Code does. 
![WindowsTerminal_jjD6pDJBFL](https://user-images.githubusercontent.com/94016085/225866148-41f3d682-7226-478d-aa72-af530bf395f5.png)
![Code_VrDJ42KWaQ](https://user-images.githubusercontent.com/94016085/225866168-f3f1bd1a-efa2-4212-827b-e30314ea25c0.png)

I have updated `tsserver` to the newest version (3.3.0), but it did not help.

## My nvim setup 
lsp-zero is set up in after/plugins/lsp.lua
[nvim.zip](https://github.com/VonHeikemen/lsp-zero.nvim/files/10999830/nvim.zip)

## Project files (see App.js)
run `npm install` to download dependecies
[project.zip](https://github.com/VonHeikemen/lsp-zero.nvim/files/10999957/project.zip)

**Comment by VonHeikemen** [comment]
I tried with your project. I don't know what components `@react-navigation/native` has but when I tried the autocomplete `NavigationContainer` did show up as a suggestion.

And the server did notify me about the syntax error.

Do you have a recent version of node active in your project?

**Comment by kuchejak** [comment]
That sounds promising, thank you for testing it! 

> Do you have a recent version of node active in your project?

I've updated Node and now when I run `node -v` in the project folder, I get `v18.15.0`, which should be the latest LTS version, but the problems still persist. I'm dnt sure if it's important, but I'm using Ubuntu through WSL.

**Comment by kuchejak** [comment]
I've now tried the project on a "real" Ubuntu 22.04 and it works fine, I'll probably reinstall the WSL Ubuntu and try again, hopefully it will help.

**Comment by kuchejak** [comment]
So I have reinstalled the WSL Ubuntu, but sadly, it did not fix the problem. 

I guess this is not really an lsp-zero problem, do you know where I should ask for help? 

Btw. I must say that lsp-zero is an awesome project, thank you for that! Without it, I'm not sure I'd even use nvim because setting up lsp for new users is really difficult and painful.

**Comment by VonHeikemen** [comment]
When looking for help in other places I recommend you show a minimal config without lsp-zero, it'll increase your chances of getting support. I have a section about it in the docs: [Testing a server in isolation](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v1.x/doc/md/lsp.md#testing-a-server-in-isolation).

You can ask for help in [Neovim's discourse](https://neovim.discourse.group/) or [matrix space](https://matrix.to/#/#neovim:matrix.org).
