### ISSUE TITLE
Making Error Bar persistent

### ISSUE THREAD

**Issue by PhilVoel** [VonHeikemen/lsp-zero.nvim#189]
There is this issue I have with the bar on the left which indicates which lines have errors, warnings, etc. However, when there are no errors to display, the entire panel "disappears" which moves everything else to the left. And as soon as there is a new error, everything is moved to the right. Is there a way to make it stay there and just have an empty space at the beginning because that shifting get really annoying.
![image](https://user-images.githubusercontent.com/56931301/226785025-60a550c5-2f55-4951-9ffc-925f1eb4e7c7.png)
![image](https://user-images.githubusercontent.com/56931301/226785130-90d4fcf7-27c6-4533-a465-e765135687ad.png)

**Comment by mrtnvgr** [comment]
```lua
vim.opt.signcolumn = "yes"
```

**Comment by PhilVoel** [comment]
Thank you
