### ISSUE TITLE
How to have diagnostics show on the line?

### ISSUE THREAD

**Issue by staycreativedesign** [VonHeikemen/lsp-zero.nvim#19]
Currently it shows in a pop up window , now can I have it automatically show on the line?

**Comment by VonHeikemen** [comment]
Sure. You can do with the function `vim.diagnostic.config`, you call it after `.setup()` to override `lsp-zero`'s config.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.setup()

vim.diagnostic.config({
  virtual_text = true
})
```
