### ISSUE TITLE
Disable syntax highlighting

### ISSUE THREAD

**Issue by ggcr** [VonHeikemen/lsp-zero.nvim#196]
Hey,

First of all congratulations. I've never seen an LSP working this good out of the box.

Is it possible to disable all syntax highlighting? For low-end machines there is a couple of mili-seconds whenever you open a file in which the text gets highlighted, that is kind of annoying to me so I thought of disabling the syntax highlighting. However, the completitions are relevant and I still need them.

Any thoughts?

Thanks

**Comment by VonHeikemen** [comment]
You can use the command `syntax off`, like this.

```lua
vim.cmd('syntax off')
```

**Comment by ggcr** [comment]
It worked! How great!

Yes, I am using `nvim v0.9` and I had no idea of that new feature. I will check it out.

Also, is there a way to sponsor your work? @VonHeikemen through GH Sponsors maybe?

Gracias.
