### ISSUE TITLE
Proposal: Integrate more LSP/Linting Functionality

### ISSUE THREAD

**Issue by danlikestocode** [VonHeikemen/lsp-zero.nvim#199]
Hello!

I love the work that has been done here but there is only one problem that I have with it. It is pretty hard to setup Linting/Formatting support if the LSP does not have its own formatting option. You will often get errors when trying to format via `vim.lsp.buf.format()` if trying to format with the LSP. The solution to this is pretty simple! [null-ls-mason](https://github.com/jay-babu/mason-null-ls.nvim) lets you do this by making use of null-ls in combination with its own logic to setup linters and formatters!

This would be great to add for people who just want one click install within Mason to setup some extra linting/formatting.

**Comment by VonHeikemen** [comment]
Oh I know about that plugin, I have a [section in the docs showing some configurations](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v2.x/doc/md/guides/integrate-with-null-ls.md#adding-mason-null-lsnvim).

I'm not sure what kind of integration is needed.

**Comment by danlikestocode** [comment]
> Oh I know about that plugin, I have a [section in the docs showing some configurations](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v2.x/doc/md/guides/integrate-with-null-ls.md#adding-mason-null-lsnvim).
> 
> I'm not sure what kind of integration is needed.

There is only some configuration needed at the moment. One issue is selecting which formatting option is going to be used. Say you install an LSP and a formatter for the same file type. By default Null-LS will override `vim.lsp.buf.format()` and use the formatter that you have installed via Mason. The problem is, sometimes you want to use the LSP's formatting capabilities instead of the Null-LS, if they both have capabilities for said filetype. 

Overall it would be *really* simple to setup Null-LS with this whole LSP-zero setup. The only piece of the puzzle that is missing with LSP-Zero is formatting options, and shipping them by default.
