### ISSUE TITLE
`<Tab>` is used when `set_lsp_keymaps = false`

### ISSUE THREAD

**Issue by bpingris** [VonHeikemen/lsp-zero.nvim#2]
Hello,
I like to keep the default vim behavior regarding `<Tab>, <C-n> & <C-p>`, but it seems `<Tab>` is set to cycle through the list even when I setup lsp_zero with this:
```lua
lsp.set_preferences({
  suggest_lsp_servers = true,
  setup_servers_on_start = true,
  set_lsp_keymaps = false,
  configure_diagnostics = true,
  cmp_capabilities = true,
  manage_nvim_cmp = true,
  sign_icons = {
    error = '✘',
    warn = '▲',
    hint = '⚑',
    info = ''
  }
})
```

Am I missing something ? ~~I can fix by overwriting my keybinding after I setup lsp_zero but I dont believe it is the expected behavior.~~
Tried to reset the keymap with `:unmap <Tab>` but it does not work.

Thanks!

**Comment by VonHeikemen** [comment]
The behavior of `tab` belongs in the `nvim-cmp` configuration. You have to override the whole mappings for `nvim-cmp`.

Right now you could hack it a little bit. This should work.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

-- Not part of the public api
local cmp_mapping = require('lsp-zero.nvim-cmp-setup').default_mappings()

-- "unmap <Tab>"
cmp_mapping['<Tab>'] = nil

lsp.setup_nvim_cmp({
  mapping = cmp_mapping
})

lsp.setup()
```

If this works, I guess it would be useful to expose `.default_mappings`.

**Comment by bpingris** [comment]
I confirm it works with your solution!
