### ISSUE TITLE
cmp.mapping.complete() mapped to return key?

### ISSUE THREAD

**Issue by mvolkmann** [VonHeikemen/lsp-zero.nvim#200]
Is it possible to map the return key to trigger `cmp.mapping.complete()` when the completion menu is visible?

**Comment by VonHeikemen** [comment]
I'm not sure I understand what you are trying to do. `cmp.mapping.complete()` is the one that triggers the completion menu, it doesn't do anything when the completion menu is already active.

**Comment by mvolkmann** [comment]
Sorry, I listed the wrong function. What I want is to use the return key instead of pressing <Ctrl-y> to select a suggested completion. My question is more about defining neovim key mappings than it is about LSP Zero. But do you know if it is possible to define a key mapping for the return key?

**Comment by VonHeikemen** [comment]
You want to use the return key to confirm the completion without selecting it? It is possible. I think this should do it.

```lua
local cmp = require('cmp')

cmp.setup({
  mapping = {
    ['<CR>'] = cmp.mapping.confirm({select = true})
  }
})
```

**Comment by mvolkmann** [comment]
That's exactly what I needed. Thanks!
