### ISSUE TITLE
How to load cmp_action when using lazy.nvim

### ISSUE THREAD

**Issue by chuan137** [VonHeikemen/lsp-zero.nvim#202]
In the snippet of lazy loading with lazy.nvim, cmp_action is not defined. When adding like the other examples to the config function of `nvim-cmp`, then error on opening telescope

> loop or previous error loading module 'lsp-zero'

Here is my snippet

```lua
  {
    'hrsh7th/nvim-cmp',
    event = 'InsertEnter',
    dependencies = {
      { 'L3MON4D3/LuaSnip' },
      { "rafamadriz/friendly-snippets" },
    },
    config = function()
      require('lsp-zero.cmp').extend({})
      local cmp = require('cmp')
      local cmp_action = require('lsp-zero').cmp_action()
   end,
  }
```

**Comment by VonHeikemen** [comment]
Oh, I forgot about that. 

Its fixed now. You can call `.action()` function now.

```lua
local cmp_action = require('lsp-zero.cmp').action()
```
