### ISSUE TITLE
lsp.format_on_save does not work

### ISSUE THREAD

**Issue by guoliang** [VonHeikemen/lsp-zero.nvim#204]
I have the following setup and thought format on save would work. However it doesn't

```lua
lsp.format_on_save({
	servers = {
		["null-ls"] = { "html", "javascript", "typescript" },
	},
})

lsp.setup()
```

Instead I have to configure the auto format on save with the following

```lua
-- null-ls setup
local null_ls = require("null-ls")
local null_opts = lsp.build_options("null-ls", {})
local augroup = vim.api.nvim_create_augroup("LspFormatting", {})

null_ls.setup({
	on_attach = function(client, bufnr)
		null_opts.on_attach(client, bufnr)
		---
		-- you can add other stuff here....
		---

		-- Auto format on save
		if client.supports_method("textDocument/formatting") then
			vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
			vim.api.nvim_create_autocmd("BufWritePre", {
				group = augroup,
				buffer = bufnr,
				callback = function()
					vim.lsp.buf.format({ bufnr = bufnr })
				end,
			})
		end
	end,
	sources = {
		-- Replace these with the tools you have installed
		null_ls.builtins.formatting.prettier,
		null_ls.builtins.diagnostics.eslint_d,
		null_ls.builtins.formatting.stylua,
	},
})

```

Do I get some clash when I'm using `null-ls` together with `lsp-zero`? Or do I miss something in my configuration?

**Comment by VonHeikemen** [comment]
Have you updated lsp-zero recently?

I released a new branch for version 2 of lsp-zero: [v2.x](https://github.com/VonHeikemen/lsp-zero.nvim/tree/v2.x).

If you are using the `main` branch of this repository, you are using version 1 of lsp-zero.

**Comment by guoliang** [comment]
Thanks, that was the issue I was using `v1.x` and when changing to `v2.x` everything auto format on save works now :)
