### ISSUE TITLE
Hit enter to autocomplete with selected suggestion stopped to work in v2.x

### ISSUE THREAD

**Issue by guoliang** [VonHeikemen/lsp-zero.nvim#205]
Hi, I was trying to find out why it stopped to autocomplete with selected suggestion. And it it turns out it is due to `v2.x`.

When I switch back to `v1.x` then autocomplete works as expected. What am I missing to make it work with v2.x as well?

My current settings for lsp-zero can be found here
https://github.com/guoliang/dotfiles/blob/main/nvim/.config/nvim/lua/plugins/lsp/init.lua

https://user-images.githubusercontent.com/542598/230737532-e5cb4f57-762d-46cd-a943-4e571c4699df.mov

**Comment by guoliang** [comment]
Okay, so I read the README.md and saw that it is now with `<C-y>` to go with the selection. So my question is instead, how can I change it back to `enter`?

**Comment by VonHeikemen** [comment]
You can find the details in the documentation: [Use Enter to confirm completion](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v2.x/doc/md/autocomplete.md#use-enter-to-confirm-completion).

**Comment by lelukeonfly** [comment]
thank you :) this drove me crazy
