### ISSUE TITLE
How to pass `window.completion` option to enabled bordered completion menu

### ISSUE THREAD

**Issue by MomePP** [VonHeikemen/lsp-zero.nvim#21]
Hi,
I want to pass `cmp.config.window.bordered` to enable bordered completion menu. Currently I saw it was not expose for configured.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/13793017/173236182-f5b66e35-fb9c-47cd-868a-63f9ddb7039a.png">
From the snapshot, I think it would be nicer if we expose `window` instead of `window.documentation` or there is the other way round to getting this working.

Thanks for this awesome lsp plugin 🎉

**Comment by VonHeikemen** [comment]
I have to be honest, I don't want to expose more options of `nvim-cmp`. I want to minimize the posibilities of breaking changes in the configuration of this plugin. What I can offer is an escape hatch, a function that returns the entire default configuration for `nvim-cmp`, so you can modify it however you like.

Update `lsp-zero`. You would want to change the preset to `lsp-compe`. After that, you can handle the config for `nvim-cmp` any way you see fit.

```lua
local lsp = require('lsp-zero')
lsp.preset('lsp-compe')

lsp.setup()

local cmp = require('cmp')
local cmp_config = lsp.defaults.cmp_config()

cmp_config.window.completion = cmp.config.window.bordered()

cmp.setup(cmp_config)
```

**Comment by MomePP** [comment]
Oh, I missed the `defaults.cmp_config()` and Yes, I agree with breaking changes issue. but I just want to clarify about the cmp configs, others cmp configs that users can customize actually it's the same level of config (snippet, formatting, completion, sources, mapping) except `documentation` that specific to `window.documentation` config. So, I suggested to expose `window` for more generalized, if you agree, I can open a PR to making this works.

Anyway, This issue can be closed. It answered my question by now. Thanks 😀
