### ISSUE TITLE
Run rust-analyzer with different env vars based on project

### ISSUE THREAD

**Issue by gustavobat** [VonHeikemen/lsp-zero.nvim#212]
Hi! I'm currently working with multiple rust toolchains (embedded vs desktop applications) that require environment variables to be set correctly for compiling/running  `rust-analyzer`.
I wonder if there's a way to, given a project `root_pattern`, whether:
1. Set environment variables,
2. Set a **pre**-rust-analyzer command so I can `source` my environment variables correctly.

I read the discussion at https://github.com/VonHeikemen/lsp-zero.nvim/issues/210, but in my case I want to the run the same LSP server with different configs.

Thanks in advance

**Comment by VonHeikemen** [comment]
Maybe the `on_new_config` function could work for you.

```lua
local lspconfig = require('lspconfig')
local root_pattern = lspconfig.util.root_pattern

lspconfig.rust_analyzer.setup({
  on_new_config = function(config, root_dir)
    local some_pattern = root_pattern('somefile')
    if some_pattern(root_dir) then
      vim.env.THINGS = 'nice'
    end
  end,
})
```

**Comment by gustavobat** [comment]
That did it! Thanks a lot 😃
