### ISSUE TITLE
How to configure formatting

### ISSUE THREAD

**Issue by Mithrandir2k18** [VonHeikemen/lsp-zero.nvim#224]
How can I configure the behaviour of `vim.lsp.buf.format`? Specifically I'd like to default to add an empty trailing newline at the end of each file, the current default seems to be to make sure the last line of the file isn't empty.

**Comment by VonHeikemen** [comment]
You can pass arguments using a lua table. You can find the list of arguments in Neovim's documentation, see [:help vim.lsp.buf.format()](https://neovim.io/doc/user/lsp.html#vim.lsp.buf.format())

For your specific case you can try this.

```lua
vim.lsp.buf.format({
  formatting_options = {
    insertFinalNewline = true,
  }
})
```

Is worth mention this really depends on your language server. If it doesn't work then probably your LSP doesn't support that configuration.

If you want to force a new line, you can try using a blocking request to the server, then use lua to insert the line after the LSP is done.

```lua
-- Blocking formatting request
vim.lsp.buf.format({
  async = false,
  timeout_ms = 10000,
})

-- append new line
vim.fn.append(vim.fn.line("$"), '')
```
