### ISSUE TITLE
Question about lua_ls in the docs

### ISSUE THREAD

**Issue by smartinellimarco** [VonHeikemen/lsp-zero.nvim#230]
Hello and thanks in advance for taking the time to help me.
I have read the doc, which is great by the way, but I couldn't understand why is _lua_ls_ setup like this in the README example:

```lua
local lsp = require('lsp-zero').preset({})

lsp.on_attach(function(client, bufnr)
  lsp.default_keymaps({buffer = bufnr})
end)

-- (Optional) Configure lua language server for neovim
require('lspconfig').lua_ls.setup(lsp.nvim_lua_ls())

lsp.setup()
```
The docs for 'nvim_lua_ls' say:

> nvim_lua_ls({opts}): ~
>     Returns settings specific to Neovim for the lua language server, lua_ls.
>     If you provide the {opts} table it'll merge it with the defaults,
>     this way you can extend or change the values easily.

What does this mean?

Is it the same than doing this?
```lua
local lsp = require('lsp-zero').preset({})

lsp.on_attach(function(_, bufnr)
  lsp.default_keymaps({buffer = bufnr})
end)

lsp.ensure_installed({
  'lua_ls',
})

lsp.setup()
```
Greetings!

**Comment by smartinellimarco** [comment]
I tested this against my nvim config file in lua, and many of them disappear when 'nvim_lua_ls' is used. 
So I guess this prevents the LSP from triggering false positives on neovim's specific syntax for lua.

**Comment by VonHeikemen** [comment]
It tells lua_ls that `vim` is global variable. And also, tells the server to analyze the runtime files and your config files.

`.nvim_lua_ls()` applies these settings to the language server.

```lua
{
  settings = {
    Lua = {
      -- Disable telemetry
      telemetry = {enable = false},
      runtime = {
        -- Tell the language server which version of Lua you're using
        -- (most likely LuaJIT in the case of Neovim)
        version = 'LuaJIT',
        path = runtime_path,
      },
      diagnostics = {
        -- Get the language server to recognize the `vim` global
        globals = {'vim'}
      },
      workspace = {
        checkThirdParty = false,
        library = {
          -- Make the server aware of Neovim runtime files
          vim.fn.expand('$VIMRUNTIME/lua'),
          vim.fn.stdpath('config') .. '/lua'
        }
      }
    }
  }
}
```
