### ISSUE TITLE
Setting configuration with set_server_config appears to have no effect

### ISSUE THREAD

**Issue by jsonc0** [VonHeikemen/lsp-zero.nvim#231]
I'm trying to enable folding capabilities using `set_server_config` as per the [API reference ](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v2.x/doc/md/api-reference.md#set_server_configopts)for my LSPs however `foldingRange` doesn't appear to be present when validating with `lsp-zero.check`.

e.g. 
`:lua require('lsp-zero.check').inspect_server_config('yamlls')`

I've been able to to configure using `lsp.configure` however I want to configure with `set_server_config` so it would be applied to all LSPs

```
lsp.configure("yamlls", {
  capabilities = {
    textDocument = {
      foldingRange = {
        dynamicRegistration = false,
        lineFoldingOnly = true
      }
    }
  }
})
```

Looking into the [table merge](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v2.x/lua/lsp-zero/server.lua#L339), I noticed that as `foldingRange` wasn't in the original configuration, `old_val[k]` would evaluate to nil and cause an index issue and stops the merge.

I added a check `if old_val[k] == nil` to `tbl_merge` and now `foldingRange` appears to be present when validating with `lsp-zero.check`

```
function s.tbl_merge(old_val, new_val)
  for k, v in pairs(new_val) do
    if type(v) == 'table' and not vim.tbl_islist(v) the
        if old_val[k] == nil then
          old_val[k] = {}
        end
      s.tbl_merge(old_val[k], v)
    else
      old_val[k] = v
    end
  end
end
```

Just wondering if this is a bug or have I misconfigured something when using `set_server_config`.

Thanks

**Comment by VonHeikemen** [comment]
Yeah, it was a bug. Its fixed now.

**Comment by jsonc0** [comment]
working now, thanks!
