### ISSUE TITLE
LSPs able to jump to symbol definition but cannot see all the references of the symbol

### ISSUE THREAD

**Issue by V4G4X** [VonHeikemen/lsp-zero.nvim#232]
Tried this on python and golang projects.  

LSPs:
golang: gopls
python: jedi-language-server

When I press `Ctrl+>` or [`gd`](https://github.com/VonHeikemen/lsp-zero.nvim#keybindings) when the cursor in on a symbol it will jump to where the function or variable is defined.  

But when I try pressing `Ctrl+}` again or [`gi`](https://github.com/VonHeikemen/lsp-zero.nvim#keybindings) to see a list of the places where a certain function or variable might be being used, it doesn't give me anything.   
I see the following output instead:
```
method textDocument/implementation is not supported by any of the servers registered for the current buffer
```

The only similar thing that works is  `gr`. But that opens up another window(a  QuickFix List). The interface of which is very slow to me.  There is no way to "peek" at the location of where the reference happens, If I select a call to see the implementation, I have to switch windows to be able to scroll through the other implementations. Overall it's a headache.

Is there no way to cycle through the implementations with a smaller hovering window the way auto-suggest works?  
Or even something bigger like telescope's `find-files` command? 

Similarly are there any commands that open up a search box that leads to Symbol definitions(both across the file and across the project)?

**Comment by V4G4X** [comment]
Turns out for some people this same command does show a small preview/hovering window the way I wanted it.  
![Desired gif](https://github.com/scalameta/nvim-metals/discussions/279#discussioncomment-1752027)

Any idea what's missing in my config?

**Comment by VonHeikemen** [comment]
> Turns out for some people this same command does show a small preview/hovering window the way I wanted it. ![Desired gif](https://github.com/scalameta/nvim-metals/discussions/279#discussioncomment-1752027)
> 
> Any idea what's missing in my config?

That looks like a plugin. One that modifies the quickfixlist. Probably this [nvim-bqf](https://github.com/kevinhwang91/nvim-bqf).

**Comment by V4G4X** [comment]
Yeah I got it now. Thanks a lot. Closing.
