### ISSUE TITLE
tsserver behavior

### ISSUE THREAD

**Issue by AlexXi19** [VonHeikemen/lsp-zero.nvim#235]
When working with a ts/tsx project, he tsserver would show up in `:LspInfo` but not be attached to the buffer. However, it can be attached after using `:LspStart`. Is there any special configurations that I need to do with tsserver specifically?

```
 Other clients that match the filetype: typescript
 
 Config: tsserver
 	filetypes:         javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	root directory:    /Users/alexxi/<redacted>
 	cmd:               typescript-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
```

**Comment by VonHeikemen** [comment]
It should have attached to the buffer. It has the filetype, and the root directory.

**Comment by AlexXi19** [comment]
Thanks for the reply! Do you have some pointers for me on how to start debugging this?

**Comment by VonHeikemen** [comment]
I would start messing around with the root directory function. Figure out what is the path.

```lua
local lsp = require('lsp-zero').preset({})

lsp.on_attach(function(client, bufnr)
  lsp.default_keymaps({buffer = bufnr})
end)

local lspconfig = require('lspconfig')

lspconfig.tsserver.setup({
  root_dir = function(fname)
    local defaults = lspconfig.tsserver.document_config.default_config
    local dir = defaults.root_dir(fname)

    print(dir)

    return dir
  end
})

lsp.setup()
```

**Comment by fbontin** [comment]
@AlexXi19 did you ever resolve this? I'm having the exact same issue, and can't solve it. I've tried the suggested printing of the root directory, but I'm getting the same as for a regular typescript file (where the lsp attaches automatically)

**Comment by AlexXi19** [comment]
@fbontin i probably did resolve it, but I don't remember what i did :(. I tried digging through my dot files but i couldn't find anything. Maybe it was solved with a reinstall or something 😢 . 

https://github.com/AlexXi19/dotfiles/tree/main/.config/nvim

**Comment by fbontin** [comment]
Thanks for responding! No worries, it's a while ago! I'll see if I can find a solution 😄

**Comment by fbontin** [comment]
So if anyone is reading this with the same issue later, what solved it for me was removing the lazy loading of lsp-zero, mason, etc :-)

Full commit here: https://github.com/fbontin/dotfiles/commit/aeef81e7a46e1fd74f7568350a4e7eff5395cca1
