### ISSUE TITLE
Lsp stays attached when switching to Netrw

### ISSUE THREAD

**Issue by leath-dub** [VonHeikemen/lsp-zero.nvim#237]
Weird, issue here, when I open lua for example, it attaches lua_ls and everything works, but when I switch back to netrw the lsp stays attached and I get syntax errors, etc. Here is my setup:
lsp.lua file
```lua
local M = {}

M.lazy = {
  {
    'VonHeikemen/lsp-zero.nvim',
    branch = 'v2.x',
    dependencies = {
      -- LSP Support
      {'neovim/nvim-lspconfig'},             -- Required
      {                                      -- Optional
        'williamboman/mason.nvim',
        build = function()
          pcall(vim.cmd, 'MasonUpdate')
        end,
      },
      {'williamboman/mason-lspconfig.nvim'}, -- Optional

      -- Autocompletion
      {'hrsh7th/nvim-cmp'},     -- Required
      {'hrsh7th/cmp-nvim-lsp'}, -- Required
      {'L3MON4D3/LuaSnip'},     -- Required
    }
  }
}

M.setup = function ()
  local lsp = require("lsp-zero").preset({})

  lsp.on_attach(function (client, bufnr)
    lsp.default_keymaps({buffer = bufnr})
  end)

  lsp.ensure_installed({"lua_ls"})

  lsp.setup()
end

return M
```

init.lua
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  require("dev.plugin.telescope"),
  require("dev.plugin.colorscheme"),
  require("dev.plugin.nvim-colorizer"),
  require("dev.plugin.harpoon"),
  require("dev.plugin.treesitter"),
  require("dev.plugin.lsp").lazy,
})

-- setup lsp
require("dev.plugin.lsp").setup()
```
as you can see it is just calling the setup and reading lazy fields from lsp.lua

Weirdly running `:lua vim.cmd.Ex()` works without the issue but having a keybind `vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)` does not

**Comment by VonHeikemen** [comment]
This certainly looks like a bug in Neovim (or maybe just netrw). My guess is something is wrong with the value of the filetype. 

I suggest using neovim v0.9.

**Comment by VAggrippino** [comment]
I'm having the same problem on a nightly build:
NVIM v0.10.0-dev-278+ga72e795ed

It's easy to reproduce. Just open a file with Netrw then return to Netrw with `:Ex`. It'll apply the same language server to the Netrw page that was used for the file that was opened.

Pressing `<C-g>` while on the Netrw page indicates `"[No Name]"` before opening any file and indicates the name of the file that *was* open after returning with `:Ex`.

Others are having the same problem: https://www.reddit.com/r/neovim/comments/12ye5rc/lsp_errors_in_netrw_windows/

**Comment by leath-dub** [comment]
Yeah I am gonna try and see if it was an issue outside of lsp-zero, I dont remember this from my old config.
