### ISSUE TITLE
In the branch 'v2.x' doesn't appear the snippets from 'luasnip'

### ISSUE THREAD

**Issue by frankenstein291294** [VonHeikemen/lsp-zero.nvim#239]
### I just changed from branch 'v1.x' to 'v2.x' but i can to enable  snippets from 'luasnip', i have been searching in differents websites but i do not find any solution.

**Comment by frankenstein291294** [comment]
First of all, i thank you by support me, here i attachment the link of my config of lsp.
Actually to  configure this i saw a video tutorial in  youtube

Repository config:
https://github.com/frankenstein291294/nvim/blob/packer-lsp-lua-nvim/lua/plugins/lsp.lua

I would appreciate you help

**Comment by VonHeikemen** [comment]
You need to add these plugins in your packer config. In the `requires` property you have on lsp-zero.

```lua
{'hrsh7th/cmp-buffer'},
{'hrsh7th/cmp-path'},
{'saadparwaiz1/cmp_luasnip'},
{'rafamadriz/friendly-snippets'},
```

And then add the luasnip loader in your `lsp.lua` script.

```lua
require('luasnip.loaders.from_vscode').lazy_load()
```

**Comment by frankenstein291294** [comment]
Thanks by you support, it's works. Thanks again
