### ISSUE TITLE
Error when opening Neovim on newest update

### ISSUE THREAD

**Issue by niknik3610** [VonHeikemen/lsp-zero.nvim#243]
![screenshot_010](https://github.com/VonHeikemen/lsp-zero.nvim/assets/29252611/b77c9d5d-adc6-4345-b557-618c96f60188)

Started happening after the newest update today. Troubleshooting steps I have tried:
- Replacing the contents of my lsp.lua file with the example one from the Readme.md 
- Moving this example config to my init.lua
- Reinstalling Zero-Lsp, both through deleting the files in .local/share and through editing my init.lua
- Using git checkout to use my config from two weeks ago (where it was working fine)

It is important to mention that the LSP works fine after skipping the error message, even having all the customization within my config. 
You can see my config here: https://github.com/niknik3610/nvim-setup

Im not sure if this is the right place to post this, I am sorry if it is not. I have never had an issue with Neovim that Google hasn't been able to fix, so any feedback would be appreciated.

**Comment by VonHeikemen** [comment]
The stacktrace indicates that something went wrong in lspconfig. The specific line it shows is trying to get the command to start the LSP server.

You can try to check which server is failing. Try with this.

```lua
local lsp = require('lsp-zero').preset({})

lsp.on_attach(function(client, bufnr)
	lsp.default_keymaps({buffer = bufnr})
end)

local installed = require('mason-lspconfig').get_installed_servers()

for _, name in ipairs(installed) do
  local server = require('lspconfig')[name]
  local ok = pcall(server.setup, {})
  if not ok then
    print('failed to setup' .. name)
  end
end

lsp.setup()
```

**Comment by niknik3610** [comment]
It was being caused by one of the servers I had installed (not sure which). I purged my LSP servers of everything that wasn't strictly necessary and it fixed the issue, so closing this issue.
