### ISSUE TITLE
`nvim_lua_ls` a nil value

### ISSUE THREAD

**Issue by danieluhl** [VonHeikemen/lsp-zero.nvim#247]
I'm getting: 
`attempt to call field 'nvim_lua_ls' (a nil value)`

from this line:
`require("lspconfig").lua_ls.setup(lsp.nvim_lua_ls())`

I verified `lsp` is `local lsp = require("lsp-zero")` and noticed many other `lsp-zero` functions do exist on that table. I'm not sure how to debug further.

This issue started this morning (May 12, 2023)

**Comment by VonHeikemen** [comment]
What version of lsp-zero are you using? version 1 doesn't have that function.

(You can check the help page, use the command `:help lsp-zero-version`)

**Comment by danieluhl** [comment]
Nailed it, thanks!
