### ISSUE TITLE
How do I tell which formatter is being used?

### ISSUE THREAD

**Issue by after-ephemera** [VonHeikemen/lsp-zero.nvim#248]
Sometimes I'm not aware of what formatter is being used and I'd like to know. Is there a way to check?

**Comment by VonHeikemen** [comment]
This is why lsp-zero has [.format_on_save()](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v2.x/doc/md/api-reference.md#format_on_saveopts) and [.format_mapping()](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v2.x/doc/md/api-reference.md#format_mappingkey-opts). With those you'll know what you are using. With format on save you can inspect the autocommand it creates, `:autocommand lsp_zero_format`. And for the keymap you can use `:map gq` (where `gq` is the mapping you used in the function). The LSP server being used to format will be in the description of the autocommand or keymap.

Now, the keymap `<F3>` in lsp-zero just uses [vim.lsp.buf.format()](https://neovim.io/doc/user/lsp.html#vim.lsp.buf.format()) without any special config. This will call every active language server with formatting capabilities. What you can do in this case is create a command that prints the name of those servers.

```lua
vim.api.nvim_create_user_command('ListFormatters', function()
  local clients = vim.lsp.get_active_clients({bufnr = vim.api.nvim_get_current_buf()})

  local formatters = vim.tbl_filter(function(c)
    return c.supports_method('textDocument/formatting')
  end, clients)

  formatters = vim.tbl_map(function(c) return c.name end, formatters)

  if #formatters > 0 then
    print(vim.inspect(formatters))
  else
    print('No formatters active in current buffer')
  end
end, {})
```
