### ISSUE TITLE
Default settings beeing attached, even though the lsp.default_keymaps() function is never called.

### ISSUE THREAD

**Issue by Weiberle17** [VonHeikemen/lsp-zero.nvim#250]
My on_attach function is the following:
```lua
lsp.on_attach(function(client, bufnr)
  whichkey.register({
    ["<leader>"] = {
      k = {
        name = "LSP",
        a = { vim.lsp.buf.code_action, "Code Action", },
        b = { vim.lsp.buf.hover, "Show LSP Info", },
        c = { vim.lsp.buf.rename, "Rename using LSP", },
        d = { vim.lsp.buf.definition, "Open LSP Definition", },
        f = { function() vim.lsp.buf.format({ async = false, timeout_ms = 10000, }) end, "Format", },
        i = { vim.lsp.buf.implementation, "Open LSP Implementation", },
        n = { vim.diagnostic.goto_next, "Goto next LSP Diagnostic", },
        p = { vim.diagnostic.goto_prev, "Goto previous LSP Diagnostic", },
        r = { require('telescope.builtin').lsp_references, "Show LSP References", },
        t = { "<cmd>Telescope diagnostics<cr>", "Show LSP diagnostics", },
      },
    },
  })
end)
```
The way I understand it this shouldn't apply the default keymaps, only if I were to add the 
```lua
lsp.default_keymaps({buffer = bufnr})
``` 
line in my attach function. However at the moment it applys the default keymaps as soon as a server attaches.
Either there seems to be a bug where the default keymaps are set either way, or I don't understand how the
```
To disable all keybindings just delete the call to .default_keymaps()
```
part in the documentation is supposed to be understood. I am also sure this worked the way I expected it to before my last update.
Maybe I am in the wrong here since english isn't my first language.

**Comment by VonHeikemen** [comment]
Are you using `lsp.preset("recommended")` anywhere in your config?

**Comment by Weiberle17** [comment]
Yes I am and deleting that also removed my problem. So I guess I did mess it up.
I still had that set from before updating to the second branch.
Sorry for the inconvenience.

**Comment by VonHeikemen** [comment]
No problem.
