### ISSUE TITLE
Formatting (<F3>) brakes Treesitter folding

### ISSUE THREAD

**Issue by dominicmeyer** [VonHeikemen/lsp-zero.nvim#253]
Hi I'm very new to nvim so maybe this question is maybe not that big of a deal.
I've got lsp-zero set up and functioning and got folding configured like this:
```
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
```
Now whenever I format the buffer with F3 the folding breaks and I have to reopen the file, to get the folding back.

Is there a way to let lsp-zero make the folding or something else to prevent this?

**Comment by VonHeikemen** [comment]
This is not specific to lsp-zero. `<F3>` uses a Neovim function called [vim.lsp.buf.format()](https://neovim.io/doc/user/lsp.html#vim.lsp.buf.format()). The question really is: how to preserve the folds after calling `vim.lsp.buf.format()`?

Best suggestion I could find was reloading the file after formatting. Doesn't really "preserves" the folds, is more like it resets everything. This requires formatting to synchronous. You could try something like this.

```lua
local lsp = require('lsp-zero').preset({})

lsp.on_attach(function(client, bufnr)
  lsp.default_keymaps({buffer = bufnr})

  vim.keymap.set('n', '<F3>', '<cmd>lua vim.lsp.buf.format({async = false})<cr><cmd>update | edit!<cr>', {buffer = true})
end)

lsp.setup()
```

**Comment by dominicmeyer** [comment]
Thanks a lot!
As you said, it didn't fix it entirely, but it's surely more convenient then before.
And sorry I assumed it's something about lsp-zero that's causing this.
