### ISSUE TITLE
How do I get the same documentation window appearance for nvim-cmp and lspconfig?

### ISSUE THREAD

**Issue by pedrobarco** [VonHeikemen/lsp-zero.nvim#255]
Hey, I'm trying to migrate to `v2.x` and I'm having a hard time getting the same configuration as I had in `v1.x`. I don't know why the  documentation window appearance differs from `nvim-cmp` completion menu and `lspconfig`'s `vim.lsp.buf.hover`.
```lua
neodev.setup()

lsp.preset({
	name = "minimal",
})

lspconfig.lua_ls.setup(lsp.nvim_lua_ls())
lspconfig.gopls.setup({
	settings = {
		gopls = {
			buildFlags = { "-tags=wireinject,integration" },
		},
	},
})

lsp.setup()

cmp.setup({
	sources = {
		{ name = "path" },
		{ name = "nvim_lsp" },
		{ name = "nvim_lua" },
		{ name = "luasnip", keyword_length = 2 },
		{ name = "buffer", keyword_length = 3 },
	},
})
```

`nvim-cmp` |  `vim.lsp.buf.hover`
:-------------------------:|:-------------------------:
![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/11519164/8c894019-f0b7-4a22-8484-d7b160949a26) | ![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/11519164/d1f0720c-9a60-4128-ab38-9477d5c31479)

**Comment by VonHeikemen** [comment]
Add this to your nvim-cmp config.

```lua
  window = {
    completion = cmp.config.window.bordered(),
    documentation = cmp.config.window.bordered(),
  }
```

**Comment by VonHeikemen** [comment]
Well... that's how you get borders in nvim-cmp. Don't know about the highlights or the markdown thing.
