### ISSUE TITLE
csharp-ls vim.lsp.buf.definition() index out of range

### ISSUE THREAD

**Issue by ztx-lyghters** [VonHeikemen/lsp-zero.nvim#256]
Hello. I'm new to vim plugins, as well as I am new to C# language. I'm trying to set up a C# environment in NeoVim and I'm having troubles with the `csharp-ls` engine. First of all, it's difficult for me to understand to which repo I should really write this issue, so do excuse me if I chose wrong and please let me know where should I post this instead.

I just created a new webapi preset via `dotnet new webapi` and opened Program.cs file in NeoVim.
When I hover over almost anything, like, for example, `WebApplication.CreateBuilder(args)`, no matter which part of it exactly, and when I press `gd` in normal mode I get this error message:

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.
lua:1828: index out of range
stack traceback:
        [C]: in function '_str_byteindex_enc'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1828: in function 'locations_to_items'
        /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:398: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1394: in function 'cb'
        vim/_editor.lua:263: in function <vim/_editor.lua:262>
```

I have no idea how can I even start debugging this. Here the link to my current nvim config files:
https://git.sr.ht/~ztx/nix-cfg/tree/bedrock-pc/item/files/home/.config/nvim

I did try to uninstall all other plugins, as well as I tried to reinstall everything several times, the result is always the same.
Any suggestions on what's going on?

**Comment by VonHeikemen** [comment]
You can try reproduce the bug with a minimal config (without lsp-zero). Something like this.

```lua
require('mason').setup()
require('mason-lspconfig').setup()

require('lspconfig').csharp_ls.setup({
  on_attach = function(client, bufnr)
    vim.keymap.set('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<cr>', {buffer = bufnr})
  end
})
```

And then maybe file an issue on the Neovim repo.

You can also try to search the [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) repo issues. See if anyone is having the same problem.

**Comment by ztx-lyghters** [comment]
> You can try reproduce the bug with a minimal config (without lsp-zero). Something like this.
> 
> ```lua
> require('mason').setup()
> require('mason-lspconfig').setup()
> 
> require('lspconfig').csharp_ls.setup({
>   on_attach = function(client, bufnr)
>     vim.keymap.set('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<cr>', {buffer = bufnr})
>   end
> })
> ```
> 
> And then maybe file an issue on the Neovim repo. The function that is failing is built-in Neovim function.
> 
> You can also try to search the [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) repo issues. See if anyone is having the same problem.
> 
> If you are using neovim nightly, try download the latest stable version (v0.9) and test the minimal config.

Thanks for the answer, the minimal config you've provided didn't fix the problem, so I guess I'm gonna file an issue on NeoVim repository. Thank you for your help!
