### ISSUE TITLE
how i fix this: The language server eslint triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless

### ISSUE THREAD

**Issue by dobbbri** [VonHeikemen/lsp-zero.nvim#258]
how i fix this:
[WARN][2023-05-19 06:48:41] ...lsp/handlers.lua:137	"The language server eslint triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"

**Comment by VonHeikemen** [comment]
I don't think you can. This is just eslint doing unnecessary work. The only thing you can do is "Report upstream", which means "report this to the people who work on the eslint LSP".

**Comment by dobbbri** [comment]
👍👍
