### ISSUE TITLE
Lsp configuration dosnt work

### ISSUE THREAD

**Issue by mahan1122** [VonHeikemen/lsp-zero.nvim#263]
im trying to pass some config options to astro lsp but lsp zero dosnt pass the options(vanilla lsp working fine)

neovim version 0.91
lsp-zero 2.x branch

my config:

---------------------------------------------------------------------
`local lsp = require('lsp-zero').preset({})

lsp.configure("astro", {
    init_options = {
        typescript = {
           serverPath = vim.fs.normalize '/home/sky/.nvm/versions/node/v20.1.0/lib/node_modules/typescript/lib/tsserverlibrary.js'
        }
    }
})

lsp.preset("recommended")

lsp.ensure_installed({
  'tsserver',
  'eslint',
  'rust_analyzer',
  'gopls',
  'astro',
  'pyright'
})

lsp.nvim_workspace()

local cmp = require('cmp')
local cmp_select = {behavior = cmp.SelectBehavior.Select}
local cmp_mappings = lsp.defaults.cmp_mappings({
  ....
})

cmp_mappings['<Tab>'] = nil
cmp_mappings['<S-Tab>'] = nil

lsp.setup_nvim_cmp({
  mapping = cmp_mappings
})

lsp.set_preferences({
    ...
})

lsp.on_attach(function(client, bufnr)
 ...
end)

lsp.setup()

vim.diagnostic.config({
    virtual_text = true
})`
---------------------------------------------------------------------

i triend the require("lspconfig").setup... syntax too and the same issue

**Comment by VonHeikemen** [comment]
If you are on the `v2.x` branch you should stop using the `recommended` preset. Also, `setup_nvim_cmp()` has been marked as deprecated, use the `cmp` module after lsp-zero if you want to customize the autocomplete behavior.

Try this.

```lua
local lsp = require('lsp-zero').preset({})

lsp.on_attach(function(client, bufnr)
  --- ........
end)

require('lspconfig').lua_ls.setup(lsp.nvim_lua_ls())

require('lspconfig').astro.setup({
  init_options = {
    typescript = {
      serverPath = vim.fs.normalize '/home/sky/.nvm/versions/node/v20.1.0/lib/node_modules/typescript/lib/tsserverlibrary.js'
    }
  }
})

lsp.setup()

local cmp = require('cmp')

cmp.setup({
  mapping = {
    --- add your mappings here
  },
})
```

If this doesn't work, maybe you have another configuration file trying to initialize the astro lsp.

**Comment by mahan1122** [comment]
thank you for answer but the problem hadn't solved

my config after changes looks like this :
`
local lsp = require('lsp-zero').preset({})

lsp.on_attach(function(client, bufnr)
  local opts = {buffer = bufnr, remap = false}

  vim.keymap.set("n", "gd", function() vim.lsp.buf.definition() end, opts)
  vim.keymap.set("n", "K", function() vim.lsp.buf.hover() end, opts)
  vim.keymap.set("n", "<leader>vws", function() vim.lsp.buf.workspace_symbol() end, opts)
  vim.keymap.set("n", "<leader>vd", function() vim.diagnostic.open_float() end, opts)
  vim.keymap.set("n", "[d", function() vim.diagnostic.goto_next() end, opts)
  vim.keymap.set("n", "]d", function() vim.diagnostic.goto_prev() end, opts)
  vim.keymap.set("n", "<leader>vca", function() vim.lsp.buf.code_action() end, opts)
  vim.keymap.set("n", "<leader>vrr", function() vim.lsp.buf.references() end, opts)
  vim.keymap.set("n", "<leader>vrn", function() vim.lsp.buf.rename() end, opts)
  vim.keymap.set("i", "<C-h>", function() vim.lsp.buf.signature_help() end, opts)
end)

require("lspconfig").astro.setup({
    init_options = {
        typescript = {
           serverPath = vim.fs.normalize '/home/sky/.nvm/versions/node/v20.1.0/lib/node_modules/typescript/lib/tsserverlibrary.js'
        }
    }
})

lsp.ensure_installed({
  'tsserver',
  'eslint',
  'rust_analyzer',
  'gopls',
  'astro',
  'pyright'
})

require('lspconfig').lua_ls.setup(lsp.nvim_lua_ls())

local cmp = require('cmp')
local cmp_select = {behavior = cmp.SelectBehavior.Select}
local cmp_mappings = lsp.defaults.cmp_mappings({
  ['<C-p>'] = cmp.mapping.select_prev_item(cmp_select),
  ['<C-n>'] = cmp.mapping.select_next_item(cmp_select),
  ['<C-y>'] = cmp.mapping.confirm({ select = true }),
  ["<C-Space>"] = cmp.mapping.complete(),
})

cmp_mappings['<Tab>'] = nil
cmp_mappings['<S-Tab>'] = nil

cmp.setup({
  mapping = cmp_mappings
})

lsp.set_preferences({
    suggest_lsp_servers = false,
    sign_icons = {
        error = 'E',
        warn = 'W',
        hint = 'H',
        info = 'I'
    }
})


lsp.setup()

vim.diagnostic.config({
    virtual_text = true
})
`

i cant run the inspect_server_config because without serverPath astro lsp crashes

and no other config is trying to init astro, when i delete all lsp-zero configs from file it works fine
the config without lsp-zero:

`
require("lspconfig").astro.setup({
    init_options = {
        typescript = {
           serverPath = vim.fs.normalize '/home/sky/.nvm/versions/node/v20.1.0/lib/node_modules/typescript/lib/tsserverlibrary.js'
        }
    }
})
`

i even checked(printed) the initialize_options from nvim lsp runtime and it doesn't change when lsp-zero is active.

**Comment by VonHeikemen** [comment]
This looks like an issue with the new version of the astro lsp, version 2.0. I could not make it work even without lsp-zero.

Try to downgrade the LSP to a previous version. Execute this command in neovim.

```vim
:MasonInstall astro-language-server@1.0.8
```

**Comment by mahan1122** [comment]
that was indeed the lsp issue im gonna open an issue in astro lsp repo

thank you for answer
