### ISSUE TITLE
Add a version of `luasnip_supertab` that doesn't trigger snippets if the completion menu isn't visible

### ISSUE THREAD

**Issue by bertin0** [VonHeikemen/lsp-zero.nvim#264]
Having `cmp_action.luasnip_supertab` also call the fallback function (could be added as a separate `cmp_action` if needed, maybe `luasnip_supertab_or_fallback`) would be nice to enable compatibility with [abecodes/tabout.nvim](https://github.com/abecodes/tabout.nvim) ootb.

**Comment by VonHeikemen** [comment]
In tabout.nvim documentation they mention this

> For example nvim-cmp mappings can be created using a function that accepts a callback. When the fallback is called tabout.nvim is working out of the box and there is no need for special configurations.

It looks like tabout should work just fine without adding anything to lsp-zero.

---

Now the supertab thing. Can you test this mapping in your config? To see if it has the behavior you want.

```lua
  cmp.mapping(function(fallback)
    local col = vim.fn.col('.') - 1

    if cmp.visible() then
      cmp.select_next_item(select_opts)
    elseif require('luasnip').jumpable(1) then
      require('luasnip').jump(1)
    elseif col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
      fallback()
    else
      cmp.complete()
    end
  end, {'i', 's'})
```

**Comment by bertin0** [comment]
> In tabout.nvim documentation they mention this
> 
> > For example nvim-cmp mappings can be created using a function that accepts a callback. When the fallback is called tabout.nvim is working out of the box and there is no need for special configurations.
> 
> It looks like tabout should work just fine without adding anything to lsp-zero.
> 
> Now the supertab thing. Can you test this mapping in your config? To see if it has the behavior you want.
> 
> ```lua
>   cmp.mapping(function(fallback)
>     local col = vim.fn.col('.') - 1
> 
>     if cmp.visible() then
>       cmp.select_next_item(select_opts)
>     elseif require('luasnip').jumpable(1) then
>       require('luasnip').jump(1)
>     elseif col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
>       fallback()
>     else
>       cmp.complete()
>     end
>   end, {'i', 's'})
> ```

Not really. The mapping I resorted to using is this:
```lua

                    ['<Tab>'] = cmp.mapping(function(fallback)
                        if cmp.visible() then
                            cmp.select_next_item()
                        elseif luasnip.expand_or_jumpable() then
                            luasnip.expand_or_jump()
                        else
                            fallback()
                        end
                    end, { 'i', 's' }),
```

**Comment by VonHeikemen** [comment]
Okay. I've added `luasnip_next()` and `luasnip_next_or_expand()`.

**Comment by bertin0** [comment]
Thanks!

**Comment by smartinellimarco** [comment]
@bertin0 How is the mapping with these new added functions? I'm using the supertab

**Comment by VonHeikemen** [comment]
@smartinellimarco You would call `.cmp_action()` to get the module with the cmp helper functions, then use the new functions like a regular mapping in `cmp`.

```lua
local cmp = require('cmp')
local cmp_action = require('lsp-zero').cmp_action()

cmp.setup({
  mapping = cmp.mapping.preset.insert({
    ['<Tab>'] = cmp_action.luasnip_next_or_expand(),
  })
})
```
