### ISSUE TITLE
[ERROR] on startup

### ISSUE THREAD

**Issue by ryannewcomer** [VonHeikemen/lsp-zero.nvim#265]
hi. 

when i open neovim, this was show:
![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/88273136/c9af7d62-d827-428c-a9d9-7ec3c0dee4cc)

my lsp-zero.rc.lua is a put in after/plugin:
```lua
local lsp = require("lsp-zero").preset({})

lsp.on_attach(function(client, bufnr)
	lsp.default_keymaps({ buffer = bufnr })
end)

lsp.format_on_save({
	format_opts = {
		async = false,
		timeout_ms = 10000,
	},
	servers = {
		["null-ls"] = { "javascript", "typescript", "lua", "python", "rust", "html", "javascriptreact" },
	},
})

lsp.setup()

local null_ls = require("null-ls")

null_ls.setup({
	sources = {
		--- Replace these with the tools you have installed
		null_ls.builtins.formatting.stylua,
		null_ls.builtins.formatting.prettier,
		null_ls.builtins.formatting.prettierd,
		null_ls.builtins.formatting.python - lsp - server,
		null_ls.builtins.formatting.quick - lint - js,
		null_ls.builtins.formatting.rome,
		null_ls.builtins.formatting.rustfmt,
		null_ls.builtins.formatting.djlint,
		null_ls.builtins.formatting.fixjson,
		null_ls.builtins.formatting.lua - language - server,
		null_ls.builtins.formatting.black,
		null_ls.builtins.formatting.prettierd,
		null_ls.builtins.formatting.html - lsp,
		null_ls.builtins.formatting.custom - elements - languageserver,
	},
}
```
have i done enything worng? i am on window 11
and my mason:
![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/88273136/58b82a02-1bfb-4cba-b13d-d58d52569299)

**Comment by VonHeikemen** [comment]
The error is in your null-ls setup. This is the first one error:

```
		null_ls.builtins.formatting.python - lsp - server,
```

`python - lsp - server` is not a valid name for a formatter. Same goes for every other source that has a `-`.

You can't just add the name of any tool to `null_ls.builtins.formatting`, you need to read the documentation and see what are the names you can use. Here is a link to the formatters supported by null-ls: [Built-in sources - formatting](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#formatting)

**Comment by ryannewcomer** [comment]
Thanks!
