### ISSUE TITLE
lsp-zero + null-ls formatting issues

### ISSUE THREAD

**Issue by helderberto** [VonHeikemen/lsp-zero.nvim#267]
## Context

I've updated my configs to use lsp-zero, and configure to save on formatting with null-ls (enabling Prettier), but for some reason I'm dealing with this specific issue:

https://github.com/VonHeikemen/lsp-zero.nvim/assets/862575/5c50dce3-ea7d-4032-8f34-1bd1f4357a64

I don't know if it's an issue regarding to the `null-ls` or `lsp-zero` configs.

## Issue

It follows all the `.prettierrc` rules perfect, the only behaviour that's weird is adding spaces to empty functions, as shown in the video above.

## My configs

You can see my lsp definitions [here](https://github.com/helderberto/dotfiles/blob/main/nvim/.config/nvim/after/plugin/lsp.lua), and specific configurations of `null-ls` [here](https://github.com/helderberto/dotfiles/blob/main/nvim/.config/nvim/after/plugin/lsp.lua#L163-L192).

**Comment by VonHeikemen** [comment]
`vim.lsp.buf.format()` will use every active server with formatting capabilities. So maybe `tsserver` is doing that.

Try format with this command.

```vim
:lua vim.lsp.buf.format({name = 'null-ls'})<cr>
```

That should format the file using only null-ls.

**Comment by helderberto** [comment]
> `vim.lsp.buf.format()` will use every active server with formatting capabilities. So maybe `tsserver` is doing that.
> 
> Try format with this command.
> 
> ```viml
> :lua vim.lsp.buf.format({name = 'null-ls'})<cr>
> ```
> 
> That should format the file using only null-ls.

I did the follow update using the approach you mentioned:
```lua
local null_opts = lsp.build_options('null-ls', {
  on_attach = function(client)
    if client.server_capabilities.documentFormattingProvider then
      vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.format({ name = 'null-ls' })") -- using null-ls directly here :)
    end
  end,
})
```

It worked like a charm. Thanks @VonHeikemen!
