### ISSUE TITLE
Lazy installation snippet warning

### ISSUE THREAD

**Issue by nicolasdumitru** [VonHeikemen/lsp-zero.nvim#270]
when using the default snippet to install LSP Zero (the one provided in the [tutorial](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v2.x/doc/md/tutorial.md#setup-lsp-zero)), the lsp gives a warning.
More specifically, on the line:
`pcall(vim.cmd, 'MasonUpdate')`
the error is:
> Cannor assign 'function|table' to parameter ...

Everything works as expected (or at least seems to), but it's unpleasant and confusing to install the LSP by copy-pasting the tutorial, restart neovim and then have the LSP tell you that you installed it... the wrong way.

**Comment by VonHeikemen** [comment]
The first parameter of `pcall` expects a function but `vim.cmd` can be a function or a table. The thing works, its just the lsp telling you to be careful.

I think you can make the warning go away by writing it like this.

```lua
pcall(function() vim.cmd('MasonUpdate') end)
```

**Comment by nicolasdumitru** [comment]
Got it. I just tested your snippet and writing it like that indeed makes the warning go away.
