### ISSUE TITLE
highlighting of variables problem

### ISSUE THREAD

**Issue by jabuxas** [VonHeikemen/lsp-zero.nvim#274]
first of all this should be more of asking for help instead of an issue

with my colorscheme, variables should be white and functions blue, but lsp/cmp is somehow making my variables blue. when i start neovim, they're white for a split second, then blue.

this is my code https://bpa.st/NYAJO

what could be the issue?

**Comment by VonHeikemen** [comment]
Probably semantic highlights. There is a section that shows [how to disable it](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v2.x/doc/md/lsp.md#disable-semantic-highlights).

**Comment by jabuxas** [comment]
thank you, that really was my problem.
