### ISSUE TITLE
Failed to update VonHeikemen/lsp-zero.nvim/v2.x - Packer

### ISSUE THREAD

**Issue by joshuahicks** [VonHeikemen/lsp-zero.nvim#276]
Hello,

I'm attempting to update to branch 'v2.x' using Packer, and I'm receiving the following error. 

![Screen Shot 2023-06-28 at 8 40 23 PM](https://github.com/VonHeikemen/lsp-zero.nvim/assets/13204883/8233c3d5-62fe-405e-8bac-33c2d6c5b194)

I understand I'm not giving a ton of information, but this is all the information I have. Does anyone know if Packer writes to a log somewhere that I can look at for more information on the error?

**Comment by VonHeikemen** [comment]
I have no idea what could be the issue, but I would just delete the plugin manually then execute `:PackerSync` again.

**Comment by joshuahicks** [comment]
Sounds good, I'll just manually delete, and then re-install with Packer. Thanks
