### ISSUE TITLE
Non-neovim lua projects

### ISSUE THREAD

**Issue by thraidh** [VonHeikemen/lsp-zero.nvim#285]
I'm working both with neovim lua files, but also non-neovim lua files.
To handle the former I'm using `.nvim_workspace`, but when I try to edit non-neovim lua files, that configuration is still picked up and confuses the language server.

I have a `.luarc.json` in my other project with a custom library path. According to the log the language server reads its configuration from the client (which is the nvim_workspace config) and `.luarc.json` and merges both.

I would like to have nvim_workspace only being used for neovim related files/projects, but since I'm new to neovim, I have no idea how that could be accomplished.

**Comment by VonHeikemen** [comment]
I think the easiest thing to do is delete the function `.nvim_workspace` from your config and make `.luarc.json` in your Neovim config folder.

```json
{
  "runtime.version": "LuaJIT",
  "runtime.path": [
    "lua/?.lua",
    "lua/?/init.lua"
  ],
  "diagnostics.globals": ["vim"],
  "workspace.checkThirdParty": false,
  "workspace.library": [
    "/usr/share/nvim/runtime/lua",
    "/home/dev/.config/nvim/lua"
  ]
}
```

Remember to change the paths in `workspace.library`, the path to your config folder and neovim's runtime files.

You can get the path to neovim's runtime executing this command in neovim:

```
:echo $VIMRUNTIME
```

**Comment by thraidh** [comment]
Thanks! That works beautifully!
