### ISSUE TITLE
Switching from nvim-lsp-installer to mason.nvim

### ISSUE THREAD

**Issue by TWB0109** [VonHeikemen/lsp-zero.nvim#29]
It appears the developer of nvim-lsp-installer, [William Boman](https://github.com/williamboman) is no longer going to maintain nvim-lsp-installer, instead, he's developing [mason](https://github.com/williamboman/mason.nvim). 

More details can be found [here](https://github.com/williamboman/nvim-lsp-installer/discussions/876)

Just putting it out here in case @VonHeikemen didn't see the post on Reddit. Just wondering if lsp-zero will switch or not, would like to help, but setting up LSP is a pain haha.

**Comment by VonHeikemen** [comment]
I will make the switch. It'll be optional at first. Give people time to migrate.

**Comment by TWB0109** [comment]
Awesome!
