### ISSUE TITLE
Add delay?

### ISSUE THREAD

**Issue by 9mm** [VonHeikemen/lsp-zero.nvim#299]
Sorry for the 2nd issue, I searched and did not see anything.

Is it possible to add a delay before issuing diagnostics?

I really loved the behavior of vim-ale which waited until you entered normal mode, but even on top of that, it would wait an additional 250ms or so.

I notice there is a large amount of "jank" where, even if `update_in_insert = false` I will simply switch to normal mode and it will flash errors for about 100ms and then they disappear. It is extremely distracting, and I assume is some kind of race condition.

**Comment by VonHeikemen** [comment]
Sadly there is an option to add delay to diagnostics. I'm sure if you know enough about the low level features of the LSP client you can hack something.

I have a thing in my config that behaves like `update_in_insert = false` but slightly better. Maybe it would help?

```lua
  local autocmd = vim.api.nvim_create_autocmd
  local group = augroup('diagnostic_cmds', {clear = true})

  autocmd('ModeChanged', {
    group = group,
    pattern = {'n:i', 'v:s'},
    desc = 'Disable diagnostics while typing',
    callback = function() vim.diagnostic.disable(0) end
  })

  autocmd('ModeChanged', {
    group = group,
    pattern = 'i:n',
    desc = 'Enable diagnostics when leaving insert mode',
    callback = function() vim.diagnostic.enable(0) end
  })
```

**Comment by 9mm** [comment]
Thank you much, I will give that a shot
