### ISSUE TITLE
Externally installed LSP servers

### ISSUE THREAD

**Issue by mightyiam** [VonHeikemen/lsp-zero.nvim#3]
Following up from [this tweet](https://twitter.com/VonHeikemen_/status/1503420397701771267).

So, I shouldn't bother trying if I currently intend to provide the servers myself?

**Comment by VonHeikemen** [comment]
Would mind testing the new branch `feat-lsp-system`? It is not going to be "zero config", but is still easy.

The setup would look like this.

```lua
local lsp = require('lsp-zero')
lsp.preset('system-lsp')

-- provide the list of servers here...
lsp.setup_servers({
  'html',
  'cssls',
})

lsp.setup()
```

You'll need to use either `.setup_servers` or `.configure` to initialize your language servers.

**Comment by mightyiam** [comment]
I sure will.

**Comment by mightyiam** [comment]
I would like to be able to configure some of the servers.

**Comment by mightyiam** [comment]
I see. `.configure`.

**Comment by mightyiam** [comment]
Seems like that branch still depends on `nvim-lsp-installer`. Could that `require` call be omitted?

**Comment by VonHeikemen** [comment]
Well, yes. I've updated the branch. `nvim-lsp-installer` is only called when needed. If you can confirm this update works I can merge the branch with `main`.

**Comment by mightyiam** [comment]
Yup, works without `nvim-lsp-installer`.

**Comment by VonHeikemen** [comment]
The new preset is now on `main`.

**Comment by mightyiam** [comment]
Thank you, @VonHeikemen .
