### ISSUE TITLE
Using LSP-ZERO, not getting inline diagnostics.

### ISSUE THREAD

**Issue by zykron1** [VonHeikemen/lsp-zero.nvim#306]
I am using the latest version of lsp-zero and am using this config:

```
local lsp = require('lsp-zero').preset("recommended")
lsp.setup()
```
How could you achieve results such as in the photo below with inline diagnostics instead of this?

What I want:

<img src="https://preview.redd.it/neovim-lsp-diagnostic-inline-not-showing-v0-m85cf0djgzka1.png?width=1340&format=png&auto=webp&s=7561d3e655e0296d35108b058a7ff19419cc41ad">

What I get(after pressing gl):
<img src="https://preview.redd.it/neovim-lsp-diagnostic-inline-not-showing-v0-k58915adgzka1.png?width=911&format=png&auto=webp&s=e1d888fd0c4dca4e8fe2b548aaf1b6b52b114e3b">

**Comment by VonHeikemen** [comment]
Versions in lsp-zero have different branches. Make sure you are using the `v2.x` branch. You can check the version using the command `:help lsp-zero-version`.

**Comment by zykron1** [comment]
I have version 2.x installed. I did some more searching and I found someone with a similar problem, you gave them this as a solution:
```
If you happen to use a plugin called lsp-zero then add vim.diagnostic.config after the setup function of lsp-zero. 
```

Could you elaborate my saying what you mean by this when I tried putting this in my config it changed nothing.

**Comment by zykron1** [comment]
Oh nvm turns out after i upgraded to version 2.x it fixed it and i just didn't reload the editor
