### ISSUE TITLE
CCLS

### ISSUE THREAD

**Issue by TheFloatingBrain** [VonHeikemen/lsp-zero.nvim#308]
CCLS is a C/C++/Objective-C language server that can be [used with lsp-config](https://github.com/MaskRay/ccls/wiki/nvim-lspconfig) (which I understand that lsp-zero is built using). If I run `LspInstall` it only gives me `clangd` (when though there are other C++ language servers/related things (formatters/linters) available on Mason (clang-format, codelldb, cpplint, cpptools soralint-language-server) tagged as being C++ servers, but they dont show up in the list. If I try to use `lsp.setup_servers({'ccls', force = true})` nothing seems to happen. I wanted to know: since lsp-zero builds on lsp-config, is there a work-around to get it to support CCLS? In addition, could CCLS be added?

**Comment by TheFloatingBrain** [comment]
I tried a slight variation on the default config: 

```lua
local lspconfig = require('lspconfig')
lspconfig.ccls.setup {
  init_options = {
    compilationDatabaseDirectory = "build";
    cache = {
      directory = ".ccls-cache";
    };
  }
}
```

Seems to work, but no auto complete, it is saying that it cant find the nvim-cmp module.

**Comment by VonHeikemen** [comment]
Does autocomplete work with any other language server?

**Comment by TheFloatingBrain** [comment]
Yes, I got it to work with python-language-server.

**Comment by VonHeikemen** [comment]
So it seems you don't have nvim-cmp installed, or is not loading correctly. So whatever completions you do have working they are not configured by lsp-zero. 

If you don't need nvim-cmp, you can delete the code that uses the `cmp` module from your config.

If you want lsp-zero to handle the autocomplete configuration, make sure you have all these plugins installed:

* [hrsh7th/nvim-cmp](https://github.com/hrsh7th/nvim-cmp) 
* [hrsh7th/cmp-nvim-lsp](https://github.com/hrsh7th/cmp-nvim-lsp) 
* [L3MON4D3/LuaSnip](https://github.com/L3MON4D3/LuaSnip)
