### ISSUE TITLE
Issue with keybindings, lazy loading and session managers

### ISSUE THREAD

**Issue by serranomorante** [VonHeikemen/lsp-zero.nvim#312]
# Update (fewer steps to replicate)

---

The replication steps on the original post are quite cumbersome, you can replicate the same problem just by doing `:LspRestart` on any of the buffers in the vsplit view (without using auto-sessions at all).

1. Repeat the 3rd step on the original issue below: Add your custom keybinding to `gr`.
2. Open 2 **different** buffers in a vsplit view and check that your lsp servers are attached.
3. Execute `:LspRestart` on 1 of your buffers.
4. Now do `:nmap gr` on each buffer and check if they refer to your custom keymap (from step 1) or the default lsp keybindings from lsp-zero.

# Original issue (more steps to replicate)

---

![t-rec_13](https://github.com/VonHeikemen/lsp-zero.nvim/assets/43413954/98f22be9-f428-47ac-b369-cd2fed9f61b6)

When restoring a saved session (with ANY session manager plugin), my custom keybindings act weird. At least 1 buffer have the correct keybinding while the others use the default keybindings provided by lsp-zero.

You can notice in the screenshot that I'm doing `:nmap gr` and for the buffer on the right it shows my custom keymap ✅ but for the buffer on the left it shows the default keymap ❌

The lsp servers work as expected, the issue is with the custom keymaps only.

## Version

lsp-zero: dev-v3
lazy.nvim: latest

## Steps to replicate

1. Add a session manager plugin to your config, for lazy:

> .../plugins/auto-session.lua

Don't worry, the following spec is configured to never do any kind of auto-saving... everything is manual.

```lua
return {
	"rmagatti/auto-session",
	opts = {
		log_level = "error",
		auto_session_root_dir = vim.fn.stdpath("data") .. "/sessions/",
		auto_session_suppress_dirs = { os.getenv("HOME") },
		auto_session_enable_last_session = false,
		auto_session_enabled = false,
		auto_session_create_enabled = false,
		auto_save_enabled = false,
		auto_restore_enabled = false,
		auto_session_use_git_branch = false,
	},
	event = "VeryLazy"
}
```

2. Add these sessionoptions:

```lua
vim.o.sessionoptions = "buffers,curdir,folds,globals,tabpages,winpos,winsize"
```

3. Add your custom keybinding to `gr`.

> .../plugins/lsp-zero.lua

For the following snippets I used these guides:
[LSP: Creating new keybindings](https://github.com/VonHeikemen/lsp-zero.nvim/blob/dev-v3/doc/md/lsp.md#creating-new-keybindings)
[References and guides: Lazy loading with lazy.nvim](https://github.com/VonHeikemen/lsp-zero.nvim/blob/dev-v3/doc/md/guides/lazy-loading-with-lazy-nvim.md)

Notice the `lazy = false` in the `neovim/nvim-lspconfig` spec. Either with `true` or `false` the problem persist.

```lua
return {
   ...
	{
		"VonHeikemen/lsp-zero.nvim",
		branch = "dev-v3",
		lazy = true,
		config = false,
         ...

	{
		"neovim/nvim-lspconfig",
		lazy = false,
		cmd = { "LspInfo", "LspInstall", "LspStart" },
		event = { "BufReadPre", "BufNewFile" },
                ...
		config = function()
			local lsp = require("lsp-zero")
			lsp.extend_lspconfig()

			lsp.on_attach(function(_, bufnr)
				-- Disable some keybindings
				-- See: https://github.com/VonHeikemen/lsp-zero.nvim/blob/dev-v3/doc/md/lsp.md#disable-keybindings
				lsp.default_keymaps({ buffer = bufnr, exclude = { "<F2>", "<F3>" } })

				-- Add new keybindings
				-- See: https://github.com/VonHeikemen/lsp-zero.nvim/blob/dev-v3/doc/md/lsp.md#creating-new-keybindings
				vim.keymap.set("n", "gr", function()
					-- require("telescope.builtin").lsp_references()
                                        vim.print("my custom keybinding!")
				end, { buffer = true })
                                ....
...
```

4. Now that your setup is complete, open 2 **different** buffers in a vsplit view and save a new session with `:SessionSave` (please make sure to close any tree plugin before saving the session... nerd-tree, neo-tree, etc)

5. Now quit and reopen vim `:qa` and then `nvim` **in the same directory** (the session in saved by directory). Your session will not be restored automatically, this is normal.

6. Manually restore your session with `SessionRestore`. You should see your same buffers in a vsplit view.

7. Now do `:nmap gr` on each buffer and check if they refer to your custom keymap or the default lsp keybindings.

### Clean up

Clean the saved session with `:Autosession delete`

## Expected result

I did several tests with different session managers and this problem is present in all of them (that is because all of those plugins use the builtin neovim session functionality). It would be amazing to have a solution in which I'm able to restore a session without losing my custom keymaps for lsp-zero.

## References

These are my [dotfiles](https://github.com/serranomorante/.dotfiles)

**Comment by serranomorante** [comment]
I ended up migrating to my own lsp setup and both of my problems dissapeared (session managers and `:LspRestart`). Thank you so much for this guide: [You might not need lsp-zero](https://github.com/VonHeikemen/lsp-zero.nvim/blob/dev-v3/doc/md/guides/you-might-not-need-lsp-zero.md) and for this one: [lsp-zero under the hood](https://github.com/VonHeikemen/lsp-zero.nvim/blob/dev-v3/doc/md/guides/under-the-hood.md)

Here are the [commits](https://github.com/serranomorante/.dotfiles/pull/1) of my migration in case anyone is interested.

I opted for doing the server setups in the `lspconfig` plugin instead of doing them in `mason-lspconfig`, maybe that was the culprit of the problem but I'm not really sure.

**Comment by VonHeikemen** [comment]
I could not reproduce the issue.

And I have no clue what could be the cause. `default_keymaps()` is not doing anything special.

**Comment by serranomorante** [comment]
> I could not reproduce the issue.
> 
> 
> 
> And I have no clue what could be the cause. `default_keymaps()` is not doing anything special.

Thank you for your reply! I'm sorry you couldn't replicate the issue. I'm willing to debug this a little bit further. I will create a minimal git repo that you can clone y and test the issue there, would that be ok?

**Comment by VonHeikemen** [comment]
Okay. I manage to reproduce the issue with another config. I think the problem is that Neovim assigns your custom keybinding only to one buffer because you have `{buffer = true}`.

Try to use the variable `bufnr` when making your custom keybinding (`{buffer = bufnr}`). This should work.

```lua
vim.keymap.set("n", "gr", function()
  vim.print("my custom keybinding!")
end, { buffer = bufnr })
```

**Comment by serranomorante** [comment]
> Okay. I manage to reproduce the issue with another config. I think the problem is that Neovim assigns your custom keybinding only to one buffer because you have `{buffer = true}`.
> 
> Try to use the variable `bufnr` when making your custom keybinding (`{buffer = bufnr}`). This should work.
> 
> ```lua
> vim.keymap.set("n", "gr", function()
>   vim.print("my custom keybinding!")
> end, { buffer = bufnr })
> ```

I totally missed that!! This solves the issue. Thank you so much and sorry about that :sad:
