### ISSUE TITLE
(v3.x) Errors when lazy-loading 

### ISSUE THREAD

**Issue by NStefan002** [VonHeikemen/lsp-zero.nvim#314]
I followed [this](https://github.com/VonHeikemen/lsp-zero.nvim/blob/dev-v3/doc/md/guides/lazy-loading-with-lazy-nvim.md) explanation on how to lazy-load lsp-zero (v3.x) with lazy.nvim. When I'm using the latest stable version (0.9.2 when I'm writing this), I get the flashing error on startup (see the video) and everything works fine after that. When I use nightly:
```
NVIM v0.10.0-dev-1031+gc431d820e
Build type: RelWithDebInfo
LuaJIT 2.1.1693350652
```
Neovim either displays an error (see screenshot) or more commonly crashes instantly (`Error: Process exited with error code 139`).
[Screencast from 2023-09-08 01-06-17.webm](https://github.com/VonHeikemen/lsp-zero.nvim/assets/100767853/05c325b6-b89e-40ce-b05b-452838d9df8c)
![Screenshot from 2023-09-08 01-04-33](https://github.com/VonHeikemen/lsp-zero.nvim/assets/100767853/68846f25-7e29-442b-9408-66f0cf5644fa)

When I swap `lazy = true` with `lazy = false` all the errors go away.

I apologize if this was not the right place to open an issue.

**Comment by VonHeikemen** [comment]
I've updated the `dev-v3` branch to solve a few issues with lazy-loading. I've also updated the guide in your link. Try updating lsp-zero and update your lazy.nvim config with the new settings.

**Comment by VonHeikemen** [comment]
lsp-zero doesn't have an `event` property like nvim-lspconfig or nvim-cmp. By adding `lazy = true` to lsp-zero it will be loaded the first time `require('lsp-zero')` is executed. This way you don't have to declare it as a dependency in nvim-lspconfig and nvim-cmp.

Mason.nvim has lazy = false to make sure is loaded on startup. With mason.nvim the order of execution matters, it needs to be configured before you use any of its tools. So its just a way to prevent errors if its loaded too late.

One last thing, the stable branch for version 3 was created. You can now change the `dev-v3` branch with `v3.x`.

**Comment by NStefan002** [comment]
Nice, thanks!
