### ISSUE TITLE
Lsp Zero breaks after commit eaff24b on dev-v3

### ISSUE THREAD

**Issue by Sawansunar56** [VonHeikemen/lsp-zero.nvim#315]
After yesterdays update, my lsp breaks down on a certain situation. If I start neovim and use telescope, it produces an error.  but if I do not start telescope and open a file randomly, the lsp works fine and telescope works fine after lsp is loaded. I think it is related to the way the plugins are being loaded but everything was working perfectly fine till yesterday before I updated to the latest version. 

Some sort of help or guidance would be pretty helpful for me. 

Neovim Version:
NVIM v0.10.0-dev-1041+g2ef7b6a43

Error Image:
![Screenshot 2023-09-08 143918](https://github.com/VonHeikemen/lsp-zero.nvim/assets/62794662/e78462a1-5d08-4171-ad6e-7e738a33308c)

**Comment by VonHeikemen** [comment]
Are you using the `dev-v3` branch?

**Comment by Sawansunar56** [comment]
@VonHeikemen Sorry for taking so long to reply, something came up in my personal life. 

For your question, yes I was using the latest branch of the dev-v3 but the later commits fixed it. Maybe, it is my fault for not waiting and creating an issue too early.

**Comment by VonHeikemen** [comment]
No problem.

By the way, the stable branch for version 3 has been created. Use the branch `v3.x` instead of `dev-v3`.
