### ISSUE TITLE
Enter to select completion

### ISSUE THREAD

**Issue by AndreiSva** [VonHeikemen/lsp-zero.nvim#316]
I know this is probably not the right place to post this but I've been wondering if there's any way to get nvim-cmp to enter the selected completion when I hit enter? With the default bindings it seems like pressing enter just creates a new line.

**Comment by VonHeikemen** [comment]
There is a way. You can find the details in the documentation: [Use Enter to confirm completion](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v2.x/doc/md/autocomplete.md#use-enter-to-confirm-completion)

**Comment by AndreiSva** [comment]
this is exactly what i was looking for! thanks!
