### ISSUE TITLE
How to disable "textDocument/hover" and "textDocument/signatureHelp" in lsp-zero config

### ISSUE THREAD

**Issue by SuperBo** [VonHeikemen/lsp-zero.nvim#320]
When using lsp-zero with noice, I had this warning because lsp-zero try to setup "textDocument/hover" and "textDocument/signatureHelp". 

How can I disable these config in lsp-zero lazy setup?

<img width="755" alt="Screenshot 2023-09-27 at 9 26 50 AM" src="https://github.com/VonHeikemen/lsp-zero.nvim/assets/2666479/afedf519-6b36-42bf-a0a9-7dcb54ef439a">

**Comment by SuperBo** [comment]
I found a solution. 
Set `vim.g.lsp_zero_ui_float_border = 0` before `require('lps-zero')` solve this warning.

**Comment by VonHeikemen** [comment]
Add this line before you use lsp-zero.

```lua
vim.g.lsp_zero_ui_float_border = 0
```

If you are usign lazy.nvim as your plugin manager, add that line in the `init` hook.

```lua
{
  'VonHeikemen/lsp-zero.nvim',
  branch = 'v3.x',
  init = function()
    vim.g.lsp_zero_ui_float_border = 0
  end,
},
```

**Comment by SuperBo** [comment]
Thank you @VonHeikemen, very quick response. Now my config look nicer :D
