### ISSUE TITLE
`default_setup` client is not attaching to the buffer

### ISSUE THREAD

**Issue by vague2k** [VonHeikemen/lsp-zero.nvim#321]
`default_setup` client is not attaching to the buffer. If i put a custom server setup like this for example

```
require('lspconfig').lua_ls.setup {
    -- ... other configs
    settings = {
        Lua = {
            diagnostics = {
                globals = { 'vim' }
            }
        }
    }
}
```
then the client will be attached, otherwise nothing, 

The following attached below is my `lsp.lua` file along with `:LspInfo`

It could be possible I goofed up somewhere, i've checked the docs and doubled checked to make sure everything was spelled correctly but still having this problem. if everything i've shown so far is **_supposed to work_**, then this could possibly be a bug?

<img width="1440" alt="Screen Shot 2023-09-27 at 1 04 34 AM" src="https://github.com/VonHeikemen/lsp-zero.nvim/assets/121782036/5b3e3b89-906e-4c7d-8e3b-fca6047026b8">

<img width="1440" alt="Screen Shot 2023-09-27 at 1 58 12 AM" src="https://github.com/VonHeikemen/lsp-zero.nvim/assets/121782036/eb9b45e3-7a43-4d96-a7a6-78cc1ce4c583">

**Comment by VonHeikemen** [comment]
You can test `.default_setup()` is being called by mason-lspconfig. Maybe something like this.

```lua
require('mason').setup({})
require('mason-lspconfig').setup({
  handlers = {
    function(server)
      vim.print({server})
      lsp_zero.default_setup(server)
    end,
  },
})
```

**Comment by vague2k** [comment]
After running the test function, on both my windows machine and macbook everything works as intended even with just the original line `lsp_zero.default_setup`.

I doubled checked just in case it was an error on my part but it seems like calling `default_server` standalone without passing servers first was an issue. 

If anymore problems arise I'll post another issue thanks for helping!
