### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by Nicals** [VonHeikemen/lsp-zero.nvim#326]
In the [Documentation](https://github.com/VonHeikemen/lsp-zero.nvim#documentation) part of the readme, the *Disable a language server* link leads to an [anchor that does not exist](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v3.x/doc/md/lsp.md#disable-a-language-server).

**Comment by VonHeikemen** [comment]
Thank you for letting me know. I changed the link, now it goes to [Exclude a language server from the automatic setup](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v3.x/doc/md/guides/integrate-with-mason-nvim.md#exclude-a-language-server-from-the-automatic-setup).
