### ISSUE TITLE
Missing `curl` requirement

### ISSUE THREAD

**Issue by griloHBG** [VonHeikemen/lsp-zero.nvim#329]
Hi all!

I was following the tutorial https://github.com/VonHeikemen/lsp-zero.nvim/blob/v3.x/doc/md/tutorial.md from within an Alpine container (version 3.18.3 - using tag latest).

Here is my humble Dockerfile, built and tagged as `alpine-nvim-lsp-zero-test`:

<details><summary>Dockerfile</summary>
<p>

```
FROM alpine:latest

RUN apk update && apk add \
        curl \
	git \
	neovim \
	neovim-doc

RUN adduser -D  --uid 1000 user && \
    chmod o-rx /home/user

USER user

WORKDIR /home/user
```

</p>
</details> 

It was launched like this (the bind mount helps me to keep the configuration between l[a]unches :stuck_out_tongue_closed_eyes:  ):

```
docker run --rm -it -v /home/<user>/lsp-zero-test/:/home/user/ alpine-nvim-lsp-zero-test:latest
```

Then at this specific point:

> Now you will have access to a command called :LspInstall. If you execute that command while you have a file opened mason-lspconfig.nvim will suggest a language server compatible with that type of file.
> Note that after you install a language server you need to restart Neovim so it can be configured properly.

Mason couldn't fetch the registry:

![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/13663866/7d285331-e7bd-4fcb-88be-dfee46a629e3)

After adding `curl` to the Dockerfile, I was able to perform the LSP installation:

<details><summary>updated Dockerfile</summary>
<p>

```
FROM alpine:latest

RUN apk update && apk add \
        curl \
	git \
	neovim \
	neovim-doc

RUN adduser -D  --uid 1000 user && \
    chmod o-rx /home/user

USER user

WORKDIR /home/user
```

</p>
</details> 

![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/13663866/bfc45e43-7bba-495c-9d51-06a16b87ffd0)

So I think `curl` is missing as a requirement in this tutorial (https://github.com/VonHeikemen/lsp-zero.nvim/blob/v3.x/doc/md/tutorial.md#requirements).

And thanks for the great tool and tutorial(s)!

**Comment by griloHBG** [comment]
Btw, seems like `bash` is also a requirement...

**Comment by VonHeikemen** [comment]
Fair enough. I've added a link to mason.nvim's requirements to the tutorial.
