### ISSUE TITLE
V1 to V3 transition problems

### ISSUE THREAD

**Issue by lescuer97** [VonHeikemen/lsp-zero.nvim#332]
I followed more or less the prime 0 to Lsp but wanted to transition to  V3. I'm getting a couple of problems with my new config. 

1. autocomplete is not completing the parenthesis and arguments (very noticeable in rust-analyzer)
2- autocomplete bindings are off and haven't been able to fix them. Before I would select the autocomplete with the enterkey and navigate with the tab or arrow keys. 

This are the two big configuration problems that I've been having. I don't know if this is the best place to say this but I hope it is hahaha. 

<details>
<summary>new V3 Config</summary>
local nnoremap = require("keymap").nnoremap
local inoremap = require("keymap").inoremap

vim.opt.signcolumn = 'yes'

local lsp_zero = require('lsp-zero')

lsp_zero.set_sign_icons({
  error = '✘',
  warn = '▲',
  hint = '⚑',
  info = ''
})

vim.diagnostic.config({
  virtual_text = true,
  severity_sort = true,
  float = {
    style = 'minimal',
    border = 'rounded',
    source = 'always',
    header = '',
    prefix = '',
  },
})

lsp_zero.on_attach(function(client, bufnr)
  local opts = {buffer = bufnr, remap = false}
    nnoremap("gD", function() vim.lsp.buf.declaration() end, opts)

    nnoremap("gd", function() vim.lsp.buf.definition() end, opts)
    -- nnoremap("<leader>gd", ':vsplit | lua vim.lsp.buf.definition()<CR>')
    -- nnoremap("gd", function()vim.tab.split(); vim.lsp.buf.definition() end, opts)
    nnoremap("K", function() vim.lsp.buf.hover() end, opts)
    nnoremap("<leader>vws", function() vim.lsp.buf.workspace_symbol() end, opts)
    nnoremap("<leader>vd", function() vim.diagnostic.open_float() end, opts)
    nnoremap("[d", function() vim.diagnostic.goto_next() end, opts)
    nnoremap("]d", function() vim.diagnostic.goto_prev() end, opts)
    nnoremap("<leader>vca", function() vim.lsp.buf.code_action() end, opts)
    nnoremap("<leader>vco", function() vim.lsp.buf.code_action({
        filter = function(code_action)
            if not code_action or not code_action.data then
                return false
            end

            local data = code_action.data.id
            return string.sub(data, #data - 1, #data) == ":0"
        end,
        apply = true
    }) end, opts)
    nnoremap("<leader>vrr", function() vim.lsp.buf.references() end, opts)
    nnoremap("<leader>vrn", function() vim.lsp.buf.rename() end, opts)
    inoremap("<C-h>", function() vim.lsp.buf.signature_help() end, opts)
end)

require('mason').setup({})

require('mason-lspconfig').setup({
  ensure_installed = {
    'tsserver',
    'lua_ls',
    'rust_analyzer',
    'denols',
    'cssls',
    'html',
    'gopls',
    },
handlers = {
    lsp_zero.default_setup,
    lua_ls = function()
      local lua_opts = lsp_zero.nvim_lua_ls()
      require('lspconfig').lua_ls.setup(lua_opts)
    end,
  },
})

local cmp = require('cmp')
local cmp_select = {behavior = cmp.SelectBehavior.Select}
local cmp_action = lsp_zero.cmp_action()
require('luasnip.loaders.from_vscode').lazy_load()

-- vim.trim
vim.opt.completeopt = {'menu', 'menuone', 'noselect'}

cmp.setup({
  preselect = 'item',
  completion = {
    completeopt = 'menu,menuone,noinsert'
  },
  sources = {
    {name = 'path'},
    {name = 'nvim_lsp'},
    {name = 'nvim_lua'},
    {name = 'buffer', keyword_length = 3},
    {name = 'luasnip', keyword_length = 2},
  },
  formatting = lsp_zero.cmp_format(),
  mapping = cmp.mapping.preset.insert({
    ['<C-p>'] = cmp.mapping.select_prev_item(cmp_select),
    ['<C-n>'] = cmp.mapping.select_next_item(cmp_select),
    ['<C-y>'] = cmp.mapping.confirm({ select = false }),
    ['<C-Space>'] = cmp.mapping.complete(),
})
})

</details>

<details>
<summary>Old V1 config</summary>

local nnoremap = require("keymap").nnoremap
local inoremap = require("keymap").inoremap

-- local lsp = require("lsp-zero")

vim.opt.signcolumn = 'yes'

local lsp = require('lsp-zero').preset({
  name = 'minimal',
  set_lsp_keymaps = true,
  manage_nvim_cmp = true,
  suggest_lsp_servers = false,
})

-- (Optional) Configure lua language server for neovim
lsp.nvim_workspace()

-- Fix Undefined global 'vim'
lsp.configure('lua_ls', {
    settings = {
        Lua = {
            diagnostics = {
                globals = { 'vim' }
            }
        }
    }
})

 lsp.configure('rust_analyzer', {
     settings = {
         ["rust-analyzer"] = {
         cargo = {
            features = {"jwt", "totp"},
        },
        procMacro = {
                enable = true
            },
    },
     },
 })

lsp.configure('tsserver', {
  single_file_support = false,
  root_dir = require('lspconfig.util').root_pattern('package.json')
})
lsp.configure('denols', {
  root_dir = require('lspconfig.util').root_pattern("deno.json", "deno.jsonc"),
})
     lsp.configure('elmls', {
  root_dir = require('lspconfig.util').root_pattern("elm.json", "elm.js"),
})

lsp.on_attach(function(client, bufnr)
    local opts = {buffer = bufnr, remap = false}

    nnoremap("gD", function() vim.lsp.buf.declaration() end, opts)

    nnoremap("gd", function() vim.lsp.buf.definition() end, opts)
    -- nnoremap("<leader>gd", ':vsplit | lua vim.lsp.buf.definition()<CR>')
    -- nnoremap("gd", function()vim.tab.split(); vim.lsp.buf.definition() end, opts)
    nnoremap("K", function() vim.lsp.buf.hover() end, opts)
    nnoremap("<leader>vws", function() vim.lsp.buf.workspace_symbol() end, opts)
    nnoremap("<leader>vd", function() vim.diagnostic.open_float() end, opts)
    nnoremap("[d", function() vim.diagnostic.goto_next() end, opts)
    nnoremap("]d", function() vim.diagnostic.goto_prev() end, opts)
    nnoremap("<leader>vca", function() vim.lsp.buf.code_action() end, opts)
    nnoremap("<leader>vco", function() vim.lsp.buf.code_action({
        filter = function(code_action)
            if not code_action or not code_action.data then
                return false
            end

            local data = code_action.data.id
            return string.sub(data, #data - 1, #data) == ":0"
        end,
        apply = true
    }) end, opts)
    nnoremap("<leader>vrr", function() vim.lsp.buf.references() end, opts)
    nnoremap("<leader>vrn", function() vim.lsp.buf.rename() end, opts)
    inoremap("<C-h>", function() vim.lsp.buf.signature_help() end, opts)
end)

lsp.setup()

vim.diagnostic.config({
    virtual_text = true,
})

</details>

Video of old behaviour: 

https://github.com/VonHeikemen/lsp-zero.nvim/assets/47948594/63279c1c-34c4-4e83-9070-0e6d60faecfd

Video of new Behaviour:

https://github.com/VonHeikemen/lsp-zero.nvim/assets/47948594/5b39796a-33c2-4fee-888c-7c3dba7c2c03

Thank you!
Sorry! for some reason is not allowing me to make code block inside the details tag

**Comment by VonHeikemen** [comment]
In your old config you had some settings for rust-analyzer. Try to add that in your new config. You can add a new handler in mason-lspconfig and configure rust-analyzer.

Add this in the `handlers` property of mason-lspconfig.

```lua
rust_analyzer = function()
  require('lspconfig').rust_analyzer.setup({
    settings = {
      ["rust-analyzer"] = {
        cargo = {
          features = { "jwt", "totp" },
        },
        procMacro = {
          enable = true,
        },
      },
    },
  })
end
```

For the autocompletion, you are missing the keymaps for the `tab` key and the `enter` key. Add this in the `mapping` property of cmp.setup.

```lua
['<CR>'] = cmp.mapping.confirm({select = false}),
['<Tab>'] = cmp_action.tab_complete(),
['<S-Tab>'] = cmp.mapping.select_prev_item(),
```

**Comment by lescuer97** [comment]
Thank you for the quick response!

the keybindings worked. 

but the rust analyzer not completing as it should is still not working, any ideas what could be the issue?

**Comment by VonHeikemen** [comment]
I know what's happening. The rust_analyzer configuration is overriding lsp-zero's defaults.

This should make it work.

```lua
require('lspconfig').rust_analyzer.setup({
  capabilities = lsp_zero.get_capabilities()
})
```

**Comment by lescuer97** [comment]
Thank you! this worked perfectly!

**Comment by antidotejack** [comment]
The only way I could get this working was by rolling back to v1.x

**Comment by VonHeikemen** [comment]
This should be fixed now in `v2.x` and `v3.x`.

**Comment by lescuer97** [comment]
> This should be fixed now in `v2.x` and `v3.x`.
 so I shouldn't need to do the capabiliies thing anymore?

**Comment by VonHeikemen** [comment]
@lescuer97 correct. You don't have to specify the capabilities anymore.
