### ISSUE TITLE
Indentation brakes when lsp servers are not attach

### ISSUE THREAD

**Issue by antidotejack** [VonHeikemen/lsp-zero.nvim#336]
# Indentation brakes when lsp servers are not attach

I really appreciate the effort this community puts in these plugging, but its to many plugging and this causes a lot of conflict. I've downloaded lsps for lua, JS, and PHP and the only thing that seems to be working are the lua snippets. and for some reason indentation is not working for PHP files and it is related to this plugging or dependency.

**Comment by VonHeikemen** [comment]
Can you be more specific? Indentation brakes how?

I must say, indentation for php files has always been broken for me.
