### ISSUE TITLE
Prettierd as formatter

### ISSUE THREAD

**Issue by arbezerra** [VonHeikemen/lsp-zero.nvim#337]
Hi,

When i format a typescript file, i get the tsserver styles instead of the prettier's.
So, i tried to ensure the prettier style with this config:

```lua
lsp_zero.format_mapping('<leader>f', {
  format_opts = {
    async = false,
    timeout_ms = 10000,
  },
  servers = {
    ['prettierd'] = {'javascript', 'typescript'},
    ['rust_analyzer'] = {'rust'},
  }
})
```
[My config](https://github.com/arbezerra/init.lua/blob/master/after/plugin/lsp.lua)

But it ignores my .prettierrc config file.
What do I need to make it work?

**Comment by VonHeikemen** [comment]
The main problem here is that `prettierd` is not a language server. So you need some sort of adapter thing.

If you really, really, really want to make it work with Neovim's LSP client you can install [efm-langserver](https://github.com/mattn/efm-langserver). This is a language server that can communicate with other external tools that don't follow the LSP protocol.

Here an example config.

```lua
local prettierd = {
  formatCommand = "prettierd '${INPUT}' ${--range-start=charStart} ${--range-end=charEnd}",
  formatCanRange = true,
  formatStdin = true,
  rootMarkers = {
    '.prettierrc',
    '.prettierrc.json',
    '.prettierrc.js',
    '.prettierrc.yml',
    '.prettierrc.yaml',
    '.prettierrc.json5',
    '.prettierrc.mjs',
    '.prettierrc.cjs',
    '.prettierrc.toml',
  },
}

require('lspconfig').efm.setup({
  init_options = {
    documentFormatting = true,
    documentRangeFormatting = true,
  },
  settings = {
    rootMarkers = {'.git/'},
    languages = {
      javascript = {prettierd},
      typescript = {prettierd},
    }
  }
})

require('lspconfig').tsserver.setup({
  on_attach = function(client)
    -- disable tsserver as a formatter
    client.server_capabilities.documentFormattingProvider = false
    client.server_capabilities.documentFormattingRangeProvider = false
  end,
})
```

After you have everything setup you can add `efm` in the `format_mapping` function.

```lua
  servers = {
    ['efm'] = {'javascript', 'typescript'},
    ['rust_analyzer'] = {'rust'},
  }
```

**Comment by arbezerra** [comment]
Thanks @VonHeikemen,

Now I understand why they used null-ls.
As an alternative, it can also be done with [nvimtools/none-ls](https://github.com/nvimtools/none-ls.nvim).
