### ISSUE TITLE
Inlay hint and error/warning display

### ISSUE THREAD

**Issue by LuckyMika** [VonHeikemen/lsp-zero.nvim#340]
I've set up LSP-Zero with a very slightly modified kickstart.lua configuration and it's working almost perfectly. I only have 2 main "issues" when using it with rust-analyzer:
1. Errors, warnings, etc. are only displayed when the buffer is saved to disk, but I would like it to display those every time I enter normal mode. Is there any setting/idiomatic way to achieve this?
2. Inlay hints for e.g. type annotations of variables or functions simply do not work, even when configuring them explicitly in the settings. Does Lsp-Zero not support those and how do I get it working?

**Comment by VonHeikemen** [comment]
For the first issue, there is no good way of solving that. There are hacky ways. `rust-analyzer` can only check files saved on disk, apparently is a known limitation.

You could setup an autocommand that saves the file when you enter `normal mode`.

For the second issue. Inlay hints are not supported in the current stable version of Neovim (v.0.9). You can get them if you use a plugin. See [Enable inlay hints with lsp-inlayhints.nvim](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v3.x/doc/md/guides/quick-recipes.md#enable-inlay-hints-with-lsp-inlayhintsnvim)

If you are using Neovim v0.10 you can enable inlay hints using the function `vim.lsp.inlay_hint`. You'll need to call that function in the files where rust-analyzer is active. Something like this.

```lua
require('rust-tools').setup({
  on_attach = function(client, bufnr)
    vim.lsp.inlay_hint(bufnr, true)
  end,
  tools = {
    inlay_hints = {
      auto = false
    }
  }
})
```
