### ISSUE TITLE
Cannot reuse lsp

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [VonHeikemen/lsp-zero.nvim#341]
![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/74532770/c72b38e6-a969-4a2e-9e6e-d394350b6383)
I have VsCode with https://ionide.io/ extension installed and wand to reuse it's lsp to use in Neovim
I didn't find any info oh how to do it
![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/74532770/8ab64190-cea5-48b9-b499-1b2883950351)
Please help
![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/74532770/4c70e832-689c-4cc6-9b8e-bd35cbabe014)

**Comment by VonHeikemen** [comment]
The error message says that Neovim can't find the executable for `fsautocomplete`.

What you can do is inspect the variable PATH. Use this command.

```lua
:lua = vim.env.PATH
```

Then make sure the executable for `fsautocomplete` is one of those folders.

An alternative solution is to modify the PATH variable and add the folder where `fsautocomplete` is. You can do this in your shell or Neovim.

**Comment by ildar-shaymukhametov** [comment]
In the end, I had to install lsp specifically for neovim
Could not figure out how to reuse the Ionide's
Paths didn't help
Thanks anyway
