### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by LuckyMika** [VonHeikemen/lsp-zero.nvim#342]
In the documentation to [setup lsp-zero with rust-tools](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v2.x/doc/md/guides/quick-recipes.md#setup-with-rust-tools), it says to use the `skip_server_setup` function, but when starting neovim, lsp-zero warns that the function has been removed.

**Comment by VonHeikemen** [comment]
The link you posted points to the `v2.x` branch.

This is documentation for `v3.x`:

https://github.com/VonHeikemen/lsp-zero.nvim/blob/v3.x/doc/md/guides/quick-recipes.md#setup-with-rust-tools
