### ISSUE TITLE
question: how can i format some text selection?

### ISSUE THREAD

**Issue by nicolimo86** [VonHeikemen/lsp-zero.nvim#343]
Right now I can only format the whole buffer. I would like to be more precise and just format the selected lines.

My current config:

```
local function lsp_keymaps(bufnr)
    local opts = { noremap = true, silent = true }
    local keymap = vim.api.nvim_buf_set_keymap
   ...
    keymap(bufnr, "n", "<leader>lf", "<cmd>lua vim.lsp.buf.format{ async = true }<cr>", opts)
    ...
end

lsp.on_attach(function(client, bufnr)
    local opts = { buffer = bufnr, remap = false }

    lsp.default_keymaps({ buffer = bufnr })
    lsp_keymaps(bufnr)
end)
```

Adding a new key mapping in visual mode doesn't seem to work:

```
local function lsp_keymaps(bufnr)
    local opts = { noremap = true, silent = true }
    local keymap = vim.api.nvim_buf_set_keymap
   ...
    keymap(bufnr, "n", "<leader>lf", "<cmd>lua vim.lsp.buf.format{ async = true }<cr>", opts)
    keymap(bufnr, "v", "lf", "<cmd>lua vim.lsp.buf.format{ async = true }<cr>", opts)  <-- new mapping
    ...
end

lsp.on_attach(function(client, bufnr)
    local opts = { buffer = bufnr, remap = false }

    lsp.default_keymaps({ buffer = bufnr })
    lsp_keymaps(bufnr)
end)
```

Can you please share your solution?

**Comment by VonHeikemen** [comment]
Your new keymap should work. I tested in my own config.

What language server are you using to format?

**Comment by nicolimo86** [comment]
I tested on a terraform file (.tf). I have 2 language servers attached to the buffer:

```
 Client: terraformls (id: 1, bufnr: [1])
 Client: tflint (id: 2, bufnr: [1])
```

I have the same behaviour (pressing `lf` after a selection does nothing) on bash file with `bashls` language server attached to the buffer.

**Comment by nicolimo86** [comment]
It works on python and lua files! This means that the language servers i'm using for terraform and bash don't support range formatting i guess.
