### ISSUE TITLE
Client 1 quit with exit code 1 and signal 15

### ISSUE THREAD

**Issue by Paladynee** [VonHeikemen/lsp-zero.nvim#349]
### Description

You probably noticed that this is in fact not a bug but a "I fucked up bad and I need help" issue.

I was following [ThePrimeagen's Neovim setup video](https://www.youtube.com/watch?v=w7i4amO_zaE) but I've noticed lsp-zero had changed and the video was not up to date, I tried deriving some code but I probably failed miserably. I'm running mason, treesitter, packer, harpoon, telescope if that makes any sense for this this issue. Here's my `lsp.lua` file:
```lua
local lsp = require('lsp-zero')

lsp.on_attach(function(client, bufnr)
    local opts = { buffer = bufnr, remap = false }

    vim.keymap.set("n", "gd", function() vim.lsp.buf.definition() end, opts)
    vim.keymap.set("n", "K", function() vim.lsp.buf.hover() end, opts)
    vim.keymap.set("n", "<leader>vws", function() vim.lsp.buf.workspace_symbol() end, opts)
    vim.keymap.set("n", "<leader>vd", function() vim.diagnostic.open_float() end, opts)
    vim.keymap.set("n", "[d", function() vim.diagnostic.goto_next() end, opts)
    vim.keymap.set("n", "]d", function() vim.diagnostic.goto_prev() end, opts)
    vim.keymap.set("n", "<leader>vca", function() vim.lsp.buf.code_action() end, opts)
    vim.keymap.set("n", "<leader>vrr", function() vim.lsp.buf.references() end, opts)
    vim.keymap.set("n", "<leader>vrn", function() vim.lsp.buf.rename() end, opts)
    vim.keymap.set("i", "<C-h>", function() vim.lsp.buf.signature_help() end, opts)

    -- see :help lsp-zero-keybindings
    -- to learn the available actions
    lsp.default_keymaps({ buffer = bufnr })
end)

require('mason').setup({})
require('mason-lspconfig').setup({
    -- Replace the language servers listed here
    -- with the ones you want to install
    ensure_installed = { 'tsserver', 'rust_analyzer' },
    handlers = {
        lsp.default_setup,
        lua_ls = function()
            local lua_opts = lsp.nvim_lua_ls()
            require('lspconfig').lua_ls.setup(lua_opts)
        end,
    },
})

local cmp = require('cmp')
local cmp_select = { behavior = cmp.SelectBehavior.Select }
local cmp_format = lsp.cmp_format()

cmp.setup({
    formatting = cmp_format,
    window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
    },
    sources = {
        name = 'nvim_lsp'
    },
    mapping = cmp.mapping.preset.insert({
        ['<C-p>'] = cmp.mapping.select_prev_item(cmp_select),
        ['<C-n>'] = cmp.mapping.select_next_item(cmp_select),
        ['<C-y>'] = cmp.mapping.confirm({ select = true }),
        ['<C-Space>'] = cmp.mapping.complete(),

    })
})

lsp.set_preferences({
    sign_icons = {}
})


lsp.setup()
```

Whenever I run `:so` I get an error stating `Client 1 quit with exit code 1 and signal 15` where the `Client 1` number changes depending on how many times I run `:so`.

My language server is not functional at the moment. I'm a beginner in using Neovim and Lua so I'm really lost here. I'd appreciate any help.

### Neovim version

```NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.1696883897
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

        sistem vimrc dosyası: "$VIM\sysinit.vim"
       $VIM öntanımlı konumu: "C:/Program Files (x86)/nvim/share/nvim"
```

### Operating system and version

Windows 10 x64 22H2

### Affected language servers

all

### Steps to reproduce

1. Run nvim
2. go to your lsp-zero configuration lua script
3. run `:so`

### Actual behavior

Client {N} quit with exit code 1 and signal 15

### Expected behavior

lsp starts running successfully on supported filetypes

### LSP log

https://gist.github.com/Paladynee/87d2e45a690d4915904d8f3ada765317

**Comment by VonHeikemen** [comment]
I wouldn't expect the language server to work right after installation. Is also not reliable to execute that code after neovim sets the filetype for the current buffer.

lsp-zero's configuration should run at startup.

If you open neovim with a lua file and execute the command `:LspInfo`, what do you get?

**Comment by Paladynee** [comment]
```Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: C:\Users\PC\AppData\Local\nvim-data\lsp.log
 Detected filetype:   
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: tsserver, lua_ls, rust_analyzer```

**Comment by VonHeikemen** [comment]
`Detected filetype` empty is a bad sign. Did you run `:LspInfo` in a lua file?

If neovim doesn't detect the filetype the language server doesn't start.

**Comment by Paladynee** [comment]
> `Detected filetype` empty is a bad sign. Did you run `:LspInfo` in a lua file?
> 
> If neovim doesn't detect the filetype the language server doesn't start.

oh, I misinterpreted "open neovim with a lua file" as "open neovim with your configuration".
Here's the output while observing a `init.lua` file: ```
 Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: C:\Users\PC\AppData\Local\nvim-data\lsp.log
 Detected filetype:   lua
 
 1 client(s) attached to this buffer: 
 
 Client: lua_ls (id: 1, bufnr: [12])
 	filetypes:       lua
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             C:\Users\PC\AppData\Local\nvim-data\mason\bin\lua-language-server.CMD
 
 Configured servers list: lua_ls, tsserver, rust_analyzer ```

Here's the output while observing a `main.rs` file: ```
 Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: C:\Users\PC\AppData\Local\nvim-data\lsp.log
 Detected filetype:   rust
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: rust
 
 Config: rust_analyzer
 	filetypes:         rust
 	root directory:    Not found.
 	cmd:               C:\Users\PC\AppData\Local\nvim-data\mason\bin\rust-analyzer.CMD
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: tsserver, rust_analyzer, lua_ls ```
 
 There are some other errors as well: 
![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/62181440/71997950-7168-45d5-aa81-a432d10dffbc)
