### ISSUE TITLE
Cannot add laravel-dev-tools

### ISSUE THREAD

**Issue by t0mri** [VonHeikemen/lsp-zero.nvim#355]
Unable to add [laravel-dev-tools](https://github.com/haringsrob/laravel-dev-tools). im using lazy.nvim

```lua
local lsp_configurations = require("lspconfig.configs")

if not lsp_configurations.blade then
	lsp_configurations.blade = {
		default_config = {
			name = "blade",
			cmd = { "blade" },
			filetypes = { "blade" },
			root_dir = require("lspconfig.util").root_pattern("~/.local/share/nvim/laravel-dev-tools"),
		},
	}
end
require("lspconfig").my_new_lsp.setup({})
```

When i reopen my init.lua i get:
![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/123792488/0dccdaa3-8148-4962-9cfb-5d9684fd25e5)

**Comment by VonHeikemen** [comment]
You have to replace `my_new_lsp` with `blade` in the setup function.

Replace this

```lua
require("lspconfig").my_new_lsp.setup({})
```

With this

```lua
require("lspconfig").blade.setup({})
```

`root_dir` is not the path to the executable. The `root_pattern` function expects a list of files lspconfig is going to look for. You probably want to use something like `composer.json` or some other laravel specific file.

```lua
root_dir = require("lspconfig.util").root_pattern("composer.json"),
```

And according to the link you have there, the command to start the language server is this

```lua
cmd = { "laravel-dev-generators", "lsp" },
```

**Comment by t0mri** [comment]
i genuinely apologize for wasting your time. i didn't know what i was doing after hours frustrating tries. im really sorry. i noticed that youve updated the doc, i appreciate it too. thanks and sorry.
