### ISSUE TITLE
add file paths to tutorial examples

### ISSUE THREAD

**Issue by Duclearc** [VonHeikemen/lsp-zero.nvim#359]
It'd be appreciated if the tutorial's code snippets included the path of the file they're supposed to be in, since novices often get confused between what's all the same file, or what goes in the `plugins/` folder or the `after/` folder.

**Comment by VonHeikemen** [comment]
Do you mean [this tutorial](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v3.x/doc/md/tutorial.md)?

**Comment by Duclearc** [comment]
Yes.
I imagine you intended for it all to be in the `init.lua` file, but most configurations online indicate they should ideally be in different places so `init.lua` doesn't grow too long.

Since you marked this as a tutorial for `lazy.nvim`, it'd be very helpful to see where could we place those snippets when not on `init.lua`.

**Comment by VonHeikemen** [comment]
Between neovim's runtimepath, lua modules and lazy.nvim's options there's too many possibilities.

**Comment by Duclearc** [comment]
Maybe then just option other than `init.lua`?

I for one am still not sure when something goes in `config` or `opts` for settings in the plugin import within `lua/plugins/init.lua`.

Or if I should put only the import in there and keep settings for it under `lua/plugins/after` (not even sure that path is correct).

This is what I mean. One other alternative would be a very welcome help.

**Comment by Duclearc** [comment]
Since your Tutorial is specifically using `lazy.nvim`, I'd use that as the "alternative to one long `init.lua` in the examples.

**Comment by VonHeikemen** [comment]
> Since your Tutorial is specifically using lazy.nvim, I'd use that as the "alternative to one long init.lua in the examples.

This is exactly why I don't include any details about a modular config in the tutorial. Using lazy.nvim's mechanism would be the "obvious" choice here, but that still allows too much freedom. I would have to explain the details of some options and why you should choose one over the other.

Neovim's runtimepath is easier to explain. Problem is, theprimeagen's tutorial uses the `after` folder (for no good reason), and at this point that thing is way too popular. Most configurations (of lsp-zero) I see online are a copy/paste of that. So I would feel the need to explain why the `after` folder is unnecessary.

Anyway, I will probably make a separate blogpost explaining how to make a modular config with lazy.nvim, and then add a link to that in the tutorial.

**Comment by Duclearc** [comment]
I am one of those people who actively needs this blog post!

Right now the confusion around the lsp and language-features setup is the _only_ reason I'm not using neovim at work.

There's a lot of confusion out there and I'm one of those currently lost. If there's not a config I can copy/paste I'm lost because I don't understand the steps. Like, right now I'm looking for php, typescript and react and they're not all easy to find.

**Comment by VonHeikemen** [comment]
Here's that blog post, [lazy.nvim: plugin configuration](https://dev.to/vonheikemen/lazynvim-plugin-configuration-3opi).

**Comment by Duclearc** [comment]
Perfect. This helped me a lot and I've managed to successfully configure 2 plugins since reading it. Thanks @VonHeikemen!
