### ISSUE TITLE
Diagnostic signs in Neovim v0.10.0 and `vim.diagnostic.config()`

### ISSUE THREAD

**Issue by olimorris** [VonHeikemen/lsp-zero.nvim#360]
More of a heads up rather than an issue...

As per https://github.com/neovim/neovim/pull/26618, diagnostic signs should be configured with `vim.diagnostic.config()` in Neovim v0.10.0 rather than `vim.fn.sign_define` as per [server.lua](https://github.com/VonHeikemen/lsp-zero.nvim/blob/b9044716e675354357ab8269ccf7bd0fcdc0991e/lua/lsp-zero/server.lua#L132).

Right now it's only a soft deprecation so everything will still work as intended until v0.11.0.

**Comment by VonHeikemen** [comment]
So with the new api is this enough?

```lua
vim.diagnostic.config({
  signs = {
    text = {
      [vim.diagnostic.severity.ERROR] = '✘',
      [vim.diagnostic.severity.WARN] = '▲',
      [vim.diagnostic.severity.HINT] = '⚑',
      [vim.diagnostic.severity.INFO] = '»',
    },
  },
})
```

I tested in nightly for a little while, seems to be good. But I was using the default colorscheme. I don't know if I should set the highlight groups too.

**Comment by olimorris** [comment]
Yep that's my understanding
