### ISSUE TITLE
suggestions overlap with each other

### ISSUE THREAD

**Issue by soufrabi** [VonHeikemen/lsp-zero.nvim#363]
Some lsp suggestions are getting hidden
![2023-12-27_12-12](https://github.com/VonHeikemen/lsp-zero.nvim/assets/116617392/eedc8763-ade2-4ad5-abb5-d2f0fe97f211)

**Comment by soufrabi** [comment]
my config files are at github.com/soufrabi/config-nvim

**Comment by VonHeikemen** [comment]
lsp-zero doesn't trigger the type hint floating window. Do you have a plugin for that?

**Comment by VonHeikemen** [comment]
I'm not sure what's going in on here. But if that floating window is in fact nvim-cmp's documentation window, you can try to set a "max width" for the text in the completion item.

```lua
local cmp_format = require('lsp-zero').cmp_format({max_width = 50})

local cmp = require('cmp')
cmp.setup({
  formatting = cmp_format,
  --- other cmp options ....
})
```
