### ISSUE TITLE
Add 'linewidth' parameter to 'formatting_options'

### ISSUE THREAD

**Issue by pronvis** [VonHeikemen/lsp-zero.nvim#364]
`vim.lsp.buf.format` ignores `vim.opt.textwidth` value. Also, I could not specify line width with [formatting options](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#formattingOptions). Please add that ability

**Comment by VonHeikemen** [comment]
`vim.lsp.buf.format()` is a Neovim function. You should open an issue in Neovim's repository.

**Comment by pronvis** [comment]
Okay, sorry
