### ISSUE TITLE
lsp_zero.cmp_format() hides important information for rust_analyzer

### ISSUE THREAD

**Issue by richardstrnad** [VonHeikemen/lsp-zero.nvim#375]
Hi all,

First, thanks for this great module. It makes life with Neovim way easier! :)
I noticed that the default `lsp_zero.cmp_format()` completely overwrites the `menu` field.

In rust_analyzer, the menu field sometimes contains essential information, e.g., from which crate a struct would be imported. Without this information, you are occasionally left with multiple identical entries.

```
local cmp_format = lsp_zero.cmp_format()

cmp.setup({
  formatting = cmp_format,
..
}
```
<img width="343" alt="image" src="https://github.com/VonHeikemen/lsp-zero.nvim/assets/8568786/bca9bc4e-ec4c-4695-a745-8c9f5fa31d58">

On the other hand, without configured formatting, I get the expected information.

![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/8568786/fde3f22c-4daa-4174-8b66-ec4564d787b6)

Could this be documented/mentioned somewhere? Or is this related to something else, and should the `menu` not contain this information?

**Comment by VonHeikemen** [comment]
Okay. I've added an extra option in `.cmp_format()` to show that information. Now you can do this.

```lua
local cmp_format = lsp_zero.cmp_format({details = true})
```

The default behavior will stay the same, but I've added a note in the documentation.

**Comment by richardstrnad** [comment]
That was quick, thanks!
<img width="985" alt="image" src="https://github.com/VonHeikemen/lsp-zero.nvim/assets/8568786/0bcf532b-61ad-41fe-8bda-03c3378a2ca1">
