### ISSUE TITLE
Add docs or possible fix for Volar 2?

### ISSUE THREAD

**Issue by StevenJPx2** [VonHeikemen/lsp-zero.nvim#381]
https://github.com/williamboman/mason-lspconfig.nvim/issues/371#issuecomment-1988153959

For reference this is problem currently with the latest Volar.

This was my fix using `lsp-zero`:

```lua
lsp.configure("tsserver", {
  init_options = {
    plugins = {
      {
	name = "@vue/typescript-plugin",
	location = "/opt/homebrew/lib/node_modules/@vue/typescript-plugin",
	languages = { "javascript", "typescript", "vue" },
      },
    },
  },
  filetypes = {
    "javascript",
    "typescript",
    "vue",
  },
})
```

Is there documentation you could add, or is it something that Mason should handle?

**Comment by VonHeikemen** [comment]
I have added this guide to the docs: [Configure volar 2.0](https://lsp-zero.netlify.app/v3.x/guide/configure-volar-v2.html)

**Comment by StevenJPx2** [comment]
Absolute LEGEND. I did not even know most of what you've shown here. However, adding collar was not necessary for me, I just needed to add it to Mason.

**Comment by StevenJPx2** [comment]
Seems like it's being changed again apparently. https://github.com/williamboman/mason-lspconfig.nvim/issues/371#issuecomment-2016587935

Don't know what is going on with Vue tooling

**Comment by VonHeikemen** [comment]
Oh. I tested with `vue-language-server` 2.0.7 and `typescript-language-server` 4.3.3, and it seems like it works. Did they released a new version?
