### ISSUE TITLE
method textDocument/definition is not supported by any of the servers registered for the current buffer

### ISSUE THREAD

**Issue by wreckitral** [VonHeikemen/lsp-zero.nvim#383]
so i got this problem, im not able to go to definition or hover, the error message said,

method textDocument/definition is not supported by any of the servers registered for the current buffer,
btw im using theprimeagen's config, 

lsp_zero.on_attach(function(client, bufnr)
  local opts = {buffer = bufnr, remap = false}

  vim.keymap.set("n", "gd", function() vim.lsp.buf.definition() end, opts)
  vim.keymap.set("n", "K", function() vim.lsp.buf.hover() end, opts)
  vim.keymap.set("n", "<leader>vws", function() vim.lsp.buf.workspace_symbol() end, opts)
  vim.keymap.set("n", "<leader>vd", function() vim.diagnostic.open_float() end, opts)
  vim.keymap.set("n", "[d", function() vim.diagnostic.goto_next() end, opts)
  vim.keymap.set("n", "]d", function() vim.diagnostic.goto_prev() end, opts)
  vim.keymap.set("n", "<leader>vca", function() vim.lsp.buf.code_action() end, opts)
  vim.keymap.set("n", "<leader>vrr", function() vim.lsp.buf.references() end, opts)
  vim.keymap.set("n", "<leader>vrn", function() vim.lsp.buf.rename() end, opts)
  vim.keymap.set("i", "<C-h>", function() vim.lsp.buf.signature_help() end, opts)
**end)******

**Comment by VonHeikemen** [comment]
What language servers are you using?

**Comment by wreckitral** [comment]
im using mason, nvim_lsp

**Comment by VonHeikemen** [comment]
> im using mason, nvim_lsp

Those are Neovim plugins. You need language servers. Did you install any language server using [one these methods](https://lsp-zero.netlify.app/v3.x/language-server-configuration.html#install-new-language-servers)?

**Comment by wreckitral** [comment]
i did, i used the automatic method, i installed, ‘tsserver’, ‘rust_analyzer’, ‘ typos_lsp’

**Comment by VonHeikemen** [comment]
Okay. So what types of files give you the error? You can go open one of those files, and then execute the command `:LspInfo`. That shows a floating window with information about the language servers attached to the buffer.

**Comment by wreckitral** [comment]
oh yeah, turns out i havent installed the language server, thank u so much
