### ISSUE TITLE
Undercurls to display errors

### ISSUE THREAD

**Issue by zerogtiger** [VonHeikemen/lsp-zero.nvim#385]
Hello, I couldn't find a setting to change diagnostic error underlines to undercurls. Any pointers?

**Comment by VonHeikemen** [comment]
That's controlled by your colorscheme. And I believe your terminal emulator has to support it too.

You can change that using the command `:highlight`. This is a vimscript command, so if you want to use it in lua you'll need to learn about `vim.cmd`.

Long story short: you could do something like this after you setup your colorscheme.

```lua
vim.cmd.highlight('DiagnosticUnderlineError', 'gui=undercurl')
```

Tip: if you enter command mode and start typing `:highlight DiagnosticUnderline` then press tab, you'll get a list of valid highlight groups.

**Comment by zerogtiger** [comment]
Got it working. Thanks!
