### ISSUE TITLE
Cannot get auto complete to work

### ISSUE THREAD

**Issue by patri9ck** [VonHeikemen/lsp-zero.nvim#387]
I followed the tutorial, this is what I ended up with:

```
return {
	'VonHeikemen/lsp-zero.nvim',
	lazy = false,
	dependencies = {
		"neovim/nvim-lspconfig",
		"hrsh7th/cmp-nvim-lsp",
		"hrsh7th/nvim-cmp",
		"L3MON4D3/LuaSnip",
		"williamboman/mason.nvim",
		"williamboman/mason-lspconfig.nvim",
		"zbirenbaum/copilot.lua",
		"zbirenbaum/copilot-cmp"
	},
	config = function()
		local lsp_zero = require("lsp-zero")

		lsp_zero.on_attach(function(client, bufnr)
			lsp_zero.default_keymaps({ buffer = bufnr })
		end)

		require("mason").setup()
		require("mason-lspconfig").setup({
			handlers = { lsp_zero.default_setup }
		})

		require('copilot').setup({
			suggestion = { enabled = false },
			panel = { enabled = false }
		})

		require('copilot_cmp').setup()

		local cmp = require('cmp')

		cmp.setup({
			sources = {
				{ name = "copilot" },
				{ name = "nvim_lsp" },
			},

			mapping = cmp.mapping.preset.insert({
				['<CR>'] = cmp.mapping.confirm({
					behavior = cmp.ConfirmBehavior.Replace,
					select = false,
				})
			})
		})
	end
}
```

The return value gets passed to lazy. How can I get auto complete to work like shown in this video: https://lsp-zero.netlify.app/v3.x/introduction.html#what-does-it-do

I test it directly in the Neovim Lua configuration files, lua_ls is installed using Mason.

**Comment by VonHeikemen** [comment]
There is a couple of things you can check.

Use the command `:LspInfo` in a lua file, make sure it says `lua_ls` is attached to the buffer.

Another thing you can do is this: open a lua file, enter insert mode, then use the command `:CmpStatus`. This should show `nvim_lsp:lua_ls` as a "ready source".

**Comment by patri9ck** [comment]
`:LspInfo` is indeed only showing copilot, not mentioning `lua_ls`.

`:CmpStatus` displays:
```
# ready source names
- copilot

# unknown source names
- nvim_lsp
```

Mason on the other hand tells that `lua-language server lua_ls` is installed.

**Comment by VonHeikemen** [comment]
Not really. `.preset()` and `.setup()` don't do anything in the current version of lsp-zero, which is `v3.x`.

If you do `:help lsp-zero-version` what do you get?

**Comment by patri9ck** [comment]
Yep, I somehow installed `v1.x`, not sure how. Updated it and it  works, thank you!
