### ISSUE TITLE
Duplicate prefixes

### ISSUE THREAD

**Issue by qbnil** [VonHeikemen/lsp-zero.nvim#389]
Is there any way i can only leave one prefix sign all the time. Right now there are cases when these are getting multiplied for some reason like here 
![image](https://github.com/VonHeikemen/lsp-zero.nvim/assets/130576530/c54cd7dc-7e3b-4f69-a2de-906b92487e88)
And the main thing, the signs are not getting highlighted. It'd be cool if i either get everything highlighted or only leave one sign icon..

**Comment by VonHeikemen** [comment]
I don't use virtual text so I'm not sure how to do it. I do know you can configure virtual text using [vim.diagnostic.config()](https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.config()). And here are the properties `virtual_text` supports [opts.VirtualText](https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.Opts.VirtualText).

So, call vim.diagnostic.config and setup the `virtual_text` property.

```lua
vim.diagnostic.config({
  virtual_text = {
     ---
     -- here you configure whatever options you have available.
     ---
  }
})
```
