### ISSUE TITLE
Function signature helper

### ISSUE THREAD

**Issue by andersonjoseph** [VonHeikemen/lsp-zero.nvim#391]
Hello! I just switched from coc.nvim and the experience has been pretty straightforward. Thanks for this project!

I was wondering if there's a way to achieve function signature helper on insert mode. Something similar to [this](https://github.com/ray-x/lsp_signature.nvim) but with the dependencies that lsp-zero already has.

**Comment by VonHeikemen** [comment]
I don't think so. The closest thing would be to call Neovim's  [vim.lsp.buf.signature_help()](https://neovim.io/doc/user/lsp.html#vim.lsp.buf.signature_help()) function with a keymap in insert mode.

Something like this.

```lua
vim.keymap.set('i', '<c-k>', '<cmd>lua vim.lsp.buf.signature_help()<cr>')
```
