### ISSUE TITLE
Question: Doc site

### ISSUE THREAD

**Issue by dan-myles** [VonHeikemen/lsp-zero.nvim#393]
Hey! I really love your new docs site, I was wondering if it was some sort of SSG framework under the hood? (Or maybe docusaurus?)
I'm in need propping up a docs site soon, and yours looks great.

**Comment by VonHeikemen** [comment]
Yes, it is a SSG framework. It's [vitepress](https://vitepress.dev/). It was created to make documentation sites. And I'm using the default theme.

**Comment by dan-myles** [comment]
> Yes, it is a SSG framework. It's [vitepress](https://vitepress.dev/). It was created to make documentation sites. And I'm using the default theme.

thanks so much!
