### ISSUE TITLE
lua-lsp is not working

### ISSUE THREAD

**Issue by fe2-Nyxar** [VonHeikemen/lsp-zero.nvim#398]
![Screenshot_20240526_163644](https://github.com/VonHeikemen/lsp-zero.nvim/assets/153492661/0cf6c162-bd58-4fc5-b2ab-90425a725733)

:LspLog's results are:
  ```  
[start][date] LSP logging initiated
[Error][date] ../vim/lsp/rcp.lua "rcp"  "/home/.../.local/share/nvim/mason/bin/lua-language-server   stderr  "/home/.../.local/share/nvim/mason/packages/lua-language-server/libexec/bin/lua-language-server"  stderr   "/home/.../.local/share/nvim/mason/packages/lua-language-server/libexec/bin/lua-language-server/libexec/bin/lua-language-server" cannot execute: required file not found \n 
```

**Comment by VonHeikemen** [comment]
That looks like permission issues. For some reason the script can't read the modules in the language server source code? Or something like that.

Maybe something went wrong during the install.
