### ISSUE TITLE
No autocompletion

### ISSUE THREAD

**Issue by tuffgniuz** [VonHeikemen/lsp-zero.nvim#399]
```lua
local lsp_zero = require('lsp-zero')

lsp_zero.on_attach(function(client, bufnr)
  lsp_zero.default_keymaps({buffer = bufnr})
end)

require('mason').setup({})
require('mason-lspconfig').setup({
  ensure_installed = {},
  handlers = {
    function(server_name)
      require('lspconfig')[server_name].setup({})
    end,
  },
})
```
I have set up `lsp-zero` with the above configuration. While the diagnostics are working fine, I am not receiving any autocompletion suggestions. Here are a few additional details:

- I have confirmed that the language server is installed and running.
- Diagnostics are displayed correctly, indicating that the server is at least partially functional.
- I am using the latest version of lsp-zero, mason, and mason-lspconfig.

### Steps Taken
- Verified the installation of the language server.
- Checked the logs for any errors but found none related to autocompletion.

### Request for Assistance
Could someone please guide me on what might be missing or misconfigured in my setup? Are there any specific steps I should take to troubleshoot and resolve the issue with autocompletion not working?

Thank you!

**Comment by VonHeikemen** [comment]
You can check the command `:CmpStatus`. If you execute that command after you enter insert mode and type a few character, it should give you this output.

```
# ready source names
- nvim_lsp:lua_ls
```

**Comment by tuffgniuz** [comment]
@VonHeikemen Thanks for the quick reply. But I have to say it was completely my stupidity. I didn't install the dependencies. I am using `rocks.nvim` for plugin management and thought for some reason it would all dependencies for `lsp-zero`. So after installing `nvim-cmp` it works fine.
