### ISSUE TITLE
How to configure html lsp?

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [VonHeikemen/lsp-zero.nvim#403]
![image](https://github.com/user-attachments/assets/d50d6e35-e579-4eee-b800-17a1f7f91b04)
![image](https://github.com/user-attachments/assets/f535c434-59e8-4ef4-8db6-9ad41bcc8b0b)

Html lsp has come settings, but I do not know how to use them?
Can you provide an example how to configure html lsp?

**Comment by VonHeikemen** [comment]
In the same way you do the lua settings. Add `settings` property to `lspconfig`, and keep in mind each dot is a nested lua table.

Here is an example.

```lua
require('lspconfig').html.setup({
  settings = {
    html = {
      autoClosingTags = false,
      autoCreateQuotes = false,
    }
  }
})
```

**Comment by ildar-shaymukhametov** [comment]
Thank you! It worked!

**Comment by ildar-shaymukhametov** [comment]
![image](https://github.com/user-attachments/assets/28daaac2-e2e4-4e23-8698-7c9e40af0101)
Please help integrate this settings!

**Comment by VonHeikemen** [comment]
You don't have to add those settings, lsp-zero is doing that for you.

If for some reason you still want to do it, just add the `capabilities` property following the path it says.

```lua
require('lspconfig').html.setup({
  capabilities = {
    textDocument = {
      completion = {
        completionItem = {
          snippetSupport = true,
        }
      }
    }
  },
  settings = {
    ---
    -- some code....
    ---  
  },
})
```

**Comment by ildar-shaymukhametov** [comment]
Thanks!
