### ISSUE TITLE
Autocompletion brakes after selecting next item after upgrading to 4.x

### ISSUE THREAD

**Issue by laycookie** [VonHeikemen/lsp-zero.nvim#409]
Hello, I adapted my config to work with 4.x, and for whatever reasons when I try to select the next item in the menu now it changes from lsp autocomplete to I'm not sure what here are the pictures. Does anyone know what might be the issue?
My neovim config, the keymaps are in `lua/core/keymaps.lua` and the autocomplete with the lsp is in `lua/plugins/lspzero.lua`
https://github.com/laycookie/dotfiles/tree/main/themes/Dennis/programs/nvim/config

![20240901_03h38m46s_grim](https://github.com/user-attachments/assets/9be2b94e-783b-4a43-8874-7c667a17b45d)
![20240901_03h38m56s_grim](https://github.com/user-attachments/assets/e6618932-3ffb-41a8-8a9e-a7fcaf36c727)

**Comment by laycookie** [comment]
That's right I export keymaps from `core.keymap` and nothing else. I'm not sure what you mean by " property `autocompletion`" I wasn't able to find any mention of it in the documentation.

**Comment by VonHeikemen** [comment]
You are using the wrong variable in the setup function of nvim-cmp. [lspzero.lua, line 53](https://github.com/laycookie/dotfiles/blob/f283a9273706aaf22a318494ce3695247cab9639/themes/Dennis/programs/nvim/config/lua/plugins/lspzero.lua#L53)

**Comment by laycookie** [comment]
Ohh, my apologies. Didn't make this type of mistake in a while lol
