### ISSUE TITLE
Luvref functions not in lsp

### ISSUE THREAD

**Issue by searleser97** [VonHeikemen/lsp-zero.nvim#412]
nvim_lua_ls does not provide the functions from LUvref like "vim.loop.cwd()"

https://neovim.io/doc/user/luvref.html

**Comment by VonHeikemen** [comment]
This was bound to happen some day.

You can download this repo [Bilal2453/luvit-meta](https://github.com/Bilal2453/luvit-meta), it has definition files for libuv. Add those to lua_ls config. Like this.

```lua
local lsp_zero = require('lsp-zero')
local lua_opts = lsp_zero.nvim_lua_ls({})

lua_opts.settings.Lua.workspace.library = {
    vim.env.VIMRUNTIME,
    '/path/to/luvit-meta/library'
}

require('lspconfig').lua_ls.setup(lua_opts)
```
