### ISSUE TITLE
How to configure formatters?

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [VonHeikemen/lsp-zero.nvim#415]
In files `*.templ`, I have two lsps attached: `templ` and `html`
When I format the file it seems to be applying all the formatters at once, with bad results
I want to restrict `*.templ` files to use only `templ` formatter
Please help me do it. I know there is `vim.lsp.buf.format`, but I'm not sure how to use it

![image](https://github.com/user-attachments/assets/1e271b7e-6279-401b-9e44-7f3a967393ef)

**Comment by VonHeikemen** [comment]
With `vim.lsp.buf.format()` you can specify the name of a language server. Something like this.

```lua
vim.lsp.buf.format({name = 'templ'})
```

To use this you would have to create a custom keymap or command.

An alternative would be using lsp-zero's [format_mapping()](https://lsp-zero.netlify.app/docs/reference/lua-api.html#format-mapping-key-opts) function.

```lua
local lsp_zero = require('lsp-zero')

-- don't add this function in the `LspAttach` autocommand.
-- `format_mapping` should run only once.
lsp_zero.format_mapping('gq', {
  format_opts = {
    async = false,
    timeout_ms = 10000,
  },
  servers = {
    ['templ'] = {'templ'},
    ['ts_ls'] = {'javascript', 'typescript'},
  }
})
```

Here `gq` will be the keymap used to format.
