### ISSUE TITLE
How to attach additional LSP client?

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [VonHeikemen/lsp-zero.nvim#416]
I want to attach `javascript` lsp to `*.templ` files, because `.*templ` files is a mix of `html`, `go` and `javascript`. It must work alongside already attached LSPs. By default, this is not happening. How to do it?
![image](https://github.com/user-attachments/assets/7220ee92-86f5-4630-b661-4b8aa920aeb6)

**Comment by VonHeikemen** [comment]
> I want to attach javascript lsp to *.templ files

This is possible but there is no guarantee the javascript language server will work.

You have to add **all** the filetypes to `lspconfig` setup function. For example, with `ts_ls` you would do this.

```lua
require('lspconfig').ts_ls.setup({
  filetypes = {
    'javascript',
    'javascriptreact',
    'javascript.jsx',
    'typescript',
    'typescriptreact',
    'typescript.tsx',
    'templ',
  },
})
```

**Comment by ildar-shaymukhametov** [comment]
Thanks for the help!
Yep, I managed to attach `ts_ls` (which what I wanted)
But it doesn't really work xDDD
Thanks anyway
