### ISSUE TITLE
Server install suggestions with mason still uses LspInstall

### ISSUE THREAD

**Issue by tedkulp** [VonHeikemen/lsp-zero.nvim#42]
As seen [here](https://github.com/VonHeikemen/lsp-zero.nvim/blob/fbbd6a267919babe9e91ba5e7b6f8df845aa55cd/lua/lsp-zero.lua#L326).  However, I believe this is further complicated by the fact that you can't just run `:MasonInstall` without an argument for a particular server.

This may be something that has to wait until it's available upstream to be able to do something like `:MasonInstall lsp` or something to have it suggest the correct server for the current filetype, since calculating that is WAY too out of scope for this plugin. Maybe just having it split out some text that says to run the `:Mason` UI yourself or something so people aren't too confused?

Thank you for this plugin! It saved me hours of frustration after starting a Neovim config from scratch this week.

**Comment by VonHeikemen** [comment]
Glad you liked the plugin.

When using mason.nvim `LspInstall` is created by the extension [mason-lspconfig.nvim](https://github.com/williamboman/mason-lspconfig.nvim). And it works just like nvim-lsp-installer.

**Comment by tedkulp** [comment]
Yup, I just realized that right now and was going to close it. I didn't have mason-lspconfig running it's setup().  I'll close this and show myself out.  :)

Thanks again.
