### ISSUE TITLE
LSPs aren't turning on

### ISSUE THREAD

**Issue by laycookie** [VonHeikemen/lsp-zero.nvim#420]
Hello, I have configured LSP zero with accordance to the documentation but for some reason the only LSP that works is the rust one (my assumption is because I'm handling from a different plugin.)
I have runned LspInfo in typescript, and C files and in both cases clangd, and denols where not attached, can anyone help me out with that?
Here is my config for Lsp zero: https://github.com/laycookie/dotfiles/blob/main/themes/Dennis/programs/nvim/config/lua/plugins/lspzero.lua

**Comment by VonHeikemen** [comment]
You forgot to call `lspconfig` in the handlers of `mason-lspconfig`. Something like this:

```lua
require('mason-lspconfig').setup({
  handlers = {
    function(server_name)
      require('lspconfig')[server_name].setup({})
    end,
  },
})
```

---

In [line 122](https://github.com/laycookie/dotfiles/blob/2a4c9a11200515bf235bf836b54e2f053233e1fe/themes/Dennis/programs/nvim/config/lua/plugins/lspzero.lua#L122), you are missing a `-` to comment out the word `Typescript`.

The `lsp.on_attach` callback overrides the `lsp_attach` property that you added in `lsp.extend_lspconfig`. You can use one of them but not both.
