### ISSUE TITLE
Make larger diagnostic

### ISSUE THREAD

**Issue by laycookie** [VonHeikemen/lsp-zero.nvim#421]
Hello, I would like to see full diagnostic info but by default lsp zero only shows an error in minimal style.
![20241103_13h44m43s_grim](https://github.com/user-attachments/assets/f589d123-43bd-4713-bf20-983d61dcf31c)

Is it possible for me to see the full error that would look something like this?
![20241103_13h44m33s_grim](https://github.com/user-attachments/assets/ef5b315b-97ce-4586-ab31-f96824488b79)

If it is possible I feel like it will be really helpful if the documentation will mention it somewhere here: https://lsp-zero.netlify.app/docs/guide/migrate-from-v1-branch.html#configure-diagnostics

**Comment by VonHeikemen** [comment]
I'm not aware of any method that can do that.

**Comment by lespea** [comment]
Does this work for you?  https://github.com/rachartier/tiny-inline-diagnostic.nvim
