### ISSUE TITLE
[Features] Add capabilities to extend nvim_cmp mapping

### ISSUE THREAD

**Issue by SuperBo** [VonHeikemen/lsp-zero.nvim#43]
I want to extend the default mapping of nvim-cmp.

Now I have to do something like this
```lua
local cmp_mapping = lsp.defaults.cmp_mappings()
cmp_mapping['<C-p>'] = cmp.mapping.select_prev_item()
cmp_mapping['<C-n>'] = cmp.mapping.select_next_item()
lsp.setup_nvim_cmp {
  mapping = cmp_mapping
}
```

Can you provide capabilities to extend the default mapping just like in nvim-cmp. Something like this will be better.

```lua
lsp.setup_nvim_cmp {
  mapping = lsp.defaults.cmp_mappings.insert({
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
  })
}
```

Thank you

**Comment by VonHeikemen** [comment]
Why not? It's been added in [ad01bf6](https://github.com/VonHeikemen/lsp-zero.nvim/commit/ad01bf60fc559b82f9f194d38167552715d94edc). 

Just pass an argument to `cmp_mappings`.

```lua
lsp.setup_nvim_cmp({
  mapping = lsp.defaults.cmp_mappings({
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
  })
})
```

**Comment by SuperBo** [comment]
Thank you. My config file looks better now! :D
