### ISSUE TITLE
DartLS attaching twice to buffer

### ISSUE THREAD

**Issue by StevenJPx2** [VonHeikemen/lsp-zero.nvim#45]
This has been happening quite frequently.
<img width="1158" alt="Screenshot 2022-09-02 at 3 11 01 PM" src="https://user-images.githubusercontent.com/33600496/188112157-df09b2f0-f4cc-4360-9931-e29a4b7a2d0b.png">

I do see that the commands are different, but what do I do from lsp-zero?

**Comment by VonHeikemen** [comment]
Are you using `flutter-tools.nvim`?

**Comment by StevenJPx2** [comment]
Yes I am! Should I do something there? Weirdly enough, before I asked you about the dartls not setting up I still had flutter tools, but I didn't work until you added the force setup update.

**Comment by VonHeikemen** [comment]
If you only use `dartls` for flutter I think this should work.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.setup()

local dart_lsp = lsp.build_options('dartls', {})
require('flutter-tools').setup({lsp = dart_lsp})
```

**Comment by StevenJPx2** [comment]
Works like a glove!
