### ISSUE TITLE
Trigger completion for imports

### ISSUE THREAD

**Issue by maxnoe** [VonHeikemen/lsp-zero.nvim#51]
When using the recommended preset, there are no completions for imports in python
for this statemet:

```
from foo import <Tab>
```
which just inputs the tab character.

Edit: sorry, c++ includes actually work...

**Comment by VonHeikemen** [comment]
When using `<Tab>` you need at least one character before the cursor. In this case you can use `<Ctrl-e>` to trigger completions manually.
