### ISSUE TITLE
Override individual diagnostic config setting?

### ISSUE THREAD

**Issue by zeitchef** [VonHeikemen/lsp-zero.nvim#56]
Hi there,

I'm trying to remove underlines from diagnostics. Before I just did `vim.diagnostic.config { underline = false }` and I thought I would be able to do something similar inside `lsp.set_preferences` but I can't seem to figure out how. 

I was able to do what I want by setting `configure_diagnostics` to `false`, but then I need to manually configure everything. How can I just set `underline = false`?

Thanks!

**Comment by VonHeikemen** [comment]
So, the diagnostics are configured when the first LSP server is setup. If you are using the `recommended` preset you should be able to override the diagnostic config after the call to `lsp.setup()`.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.setup()

vim.diagnostic.config({
  underline = false
})
```
