### ISSUE TITLE
Default mapping for vim.lsp.buf.range_code_action()

### ISSUE THREAD

**Issue by mightyiam** [VonHeikemen/lsp-zero.nvim#6]
Would probably be helpful to have. Could it be the same as for `vim.lsp.buf.code_action()` but in mode `x`?

**Comment by VonHeikemen** [comment]
It has been added in [9381d55](https://github.com/VonHeikemen/lsp-zero.nvim/commit/9381d55dd704d10ea9fcfdaf2bfaeb1d49631f6c). It is `<F4>` in visual mode.

**Comment by mightyiam** [comment]
Thank you, @VonHeikemen !
