### ISSUE TITLE
Do you intent to integrate with null-ls

### ISSUE THREAD

**Issue by hieutran21198** [VonHeikemen/lsp-zero.nvim#60]
I want to integrate with null-ls plugins to handle linting & formatting buffer. But when I passed the on_attach function (below), all the keybindings has gone. So can you export the default on_attach before setup?
 
```lua
function(client, bufnr)
	client.server_capabilities.documentRangeFormattingProvider = false

	if client.supports_method "textDocument/formatting" then
		vim.api.nvim_clear_autocmds { group = augroup, buffer = bufnr }
		vim.api.nvim_create_autocmd("BufWritePre", {
			group = augroup,
			buffer = bufnr,
			callback = function()
				vim.lsp.buf.format {
					bufnr = bufnr,
					filter = function(filtered_client)
						return filtered_client.name == "null-ls"
					end,
				}
			end,
		})
	end
end
```

**Comment by hieutran21198** [comment]
Oh, sorry. I find out the answer.

**Comment by yoramdelangen** [comment]
I think it is important to note, that having the `null-ls` imports after `lsp.setup()`! Otherwise Mason will not be initialised and null-ls will overwrite the on_attach handlers.
