### ISSUE TITLE
snippet for Ruby `if else` matches when typing `else` and hitting enter for newline creates it

### ISSUE THREAD

**Issue by technicalpickles** [VonHeikemen/lsp-zero.nvim#61]
I'm not sure which plugin to attribute this behavior to, but hoping to get some guidance.

I'm working in ruby, and go to write an if/else statement, but I don't use the snippet. I can do the `if` fine like this, but as soon as I go to do the `else`, the `if else` snippet starts matching. If I press enter, then that snippet is triggered, and it ends up creating a second if statement instead of let

![CleanShot 2022-11-22 at 11 11 30](https://user-images.githubusercontent.com/159/203364468-8299c02d-4ed4-4bc7-b671-b1199d7eed09.gif)

It seems like typing `else` should only match snippets that match `else`, rather than ones that end in it.

My configuration:

```lua
local lsp = require("lsp-zero")
local lspkind = require("lspkind")

lsp.preset("recommended")
lsp.nvim_workspace()

lsp.setup_nvim_cmp({
	formatting = {
		format = lspkind.cmp_format({
			mode = "symbol_text",
			menu = {
				buffer = "[Buffer]",
				nvim_lsp = "[LSP]",
				luasnip = "[LuaSnip]",
				nvim_lua = "[Lua]",
				latex_symbols = "[Latex]",
			},
		}),
	},
	sources = {
		{ name = "nvim_lsp_signature_help" },
		{ name = "path" },
		{ name = "fish" },
		{ name = "nvim_lsp", keyword_length = 3 },
		{ name = "buffer", keyword_length = 3 },
		{ name = "luasnip", keyword_length = 2 },
	},
})

lsp.configure("sumneko_lua", {
	settings = {
		Lua = {
			runtime = {
				-- Tell the language server which version of Lua you're using (most likely LuaJIT in the case of Neovim)
				version = "LuaJIT",
			},
			diagnostics = {
				-- Get the language server to recognize the `vim` global
				globals = { "vim" },
			},
			workspace = {
				-- Make the server aware of Neovim runtime files
				library = vim.api.nvim_get_runtime_file("", true),
			},
			-- Do not send telemetry data containing a randomized but unique identifier
			telemetry = {
				enable = false,
			},
		},
	},
})

lsp.setup()
```

**Comment by technicalpickles** [comment]
Here is the friendly snippet for it: https://github.com/rafamadriz/friendly-snippets/blob/main/snippets/ruby.json#L84-L93

```json
	"if else": {
		"prefix": "if else",
		"body": [
			"if ${1:test}",
			"\t$0",
			"else",
			"\t",
			"end"
		]
	},
```

The `prefix` gets translated to `trig`: https://github.com/L3MON4D3/LuaSnip/blob/09ce9a70bd787d4ce188f2de1390f656f119347c/lua/luasnip/loaders/from_vscode.lua#L35-L52

I haven't been able to trace where `trig` gets used when deciding if something is expandable yet.

**Comment by VonHeikemen** [comment]
The first item in the completion list is always preselected, that's why pressing `Enter` confirms the snippet. If you want to disable this behaviour add this in your `nvim-cmp` config.

```lua
  preselect = 'none',
  completion = {
    completeopt = 'menu,menuone,noinsert,noselect'
  },
```

**Comment by technicalpickles** [comment]
I think my issue is more that `else` is completing to a snippet named 'if else'. Did some looking around, and it seems that other snippet plugins don't use that convention. Compare to [vim-snippets](https://github.com/honza/vim-snippets) which is a snipmate-style, which uses `ife` for if else:

![CleanShot 2022-11-22 at 12 21 30](https://user-images.githubusercontent.com/159/203380198-8a531c85-b230-443a-9223-e8017d001be8.gif)

Given that, I think it's an issue with luasnip's matching, or [friendly-snippets](https://github.com/rafamadriz/friendly-snippets) 'if else' prefix. 

For anyone curious how to switch to this:


```lua
-- in `packer` block
	-- lsp, linters, formatters, etc
	use({
		"VonHeikemen/lsp-zero.nvim",
		requires = {
			-- LSP Support
			{ "neovim/nvim-lspconfig" },
			{ "williamboman/mason.nvim" },
			{ "williamboman/mason-lspconfig.nvim" },

			-- Autocompletion
			{ "hrsh7th/nvim-cmp" },
			{ "hrsh7th/cmp-buffer" },
			{ "hrsh7th/cmp-path" },
			{ "saadparwaiz1/cmp_luasnip" },
			{ "hrsh7th/cmp-nvim-lsp" },
			{ "hrsh7th/cmp-nvim-lua" },

			-- Snippets
			{ "L3MON4D3/LuaSnip" },
			-- instead of { "rafamadriz/friendly-snippets" },
			{"honza/vim-snippets"},
		},
	})

-- where lsp-zero is configured:
require("luasnip.loaders.from_snipmate").lazy_load()
```

**Comment by technicalpickles** [comment]
I filed it over at https://github.com/rafamadriz/friendly-snippets/issues/209 so can close this now.

Thank @VonHeikemen for the tip re nvim workspace!
