### ISSUE TITLE
Inline Hints

### ISSUE THREAD

**Issue by tsndr** [VonHeikemen/lsp-zero.nvim#65]
Is there a way to enable inline hints like this:

<img width="1061" alt="Screenshot 2022-12-05 at 12 48 22 AM" src="https://user-images.githubusercontent.com/2940127/205523317-4cb6240a-afdd-4459-be25-3dc2bbf31cab.png">

**Comment by VonHeikemen** [comment]
Yes, with the [vim.diagnostic.config](https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.config()) function. Just make sure to call it after setup lsp-zero, so it can override lsp-zero's config.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.setup()

vim.diagnostic.config({
  virtual_text = true
})
```

**Comment by tsndr** [comment]
Thank you ❤️

**Comment by sohooo** [comment]
> Yes, with the [vim.diagnostic.config](https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.config()) function. Just make sure to call it after setup lsp-zero, so it can override lsp-zero's config.
> 
> ```lua
> local lsp = require('lsp-zero')
> lsp.preset('recommended')
> 
> lsp.setup()
> 
> vim.diagnostic.config({
>   virtual_text = true
> })
> ```

For further customization of `virtual_text`, I needed to use "the old way", as `vim.diagnostic.config virtual_text` doesn't seem to support `severity_limit`:

```lua
-- display inline warning/error messages
-- vim.diagnostic.config({
--   virtual_text = {
--     -- prefix = '●', -- Could be '●', '▎', 'x', ■
--     spacing = 4,
--     severity_limit = vim.diagnostic.severity.WARN, -- FIXME: key currently unsupported
--   },
--     underline = false,
--     signs = true, -- signs customized below
--     update_in_insert = true,
-- })

vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
  vim.lsp.diagnostic.on_publish_diagnostics, {
    --virtual_text = false,
    virtual_text = {
      prefix = '⋇', -- Could be '●', '▎', 'x', ■
      spacing = 4,
      severity_limit = 'Warning',
    },
    underline = false,
    signs = true,
    update_in_insert = true,
  }
)
```
