### ISSUE TITLE
Simple way to disable only snippets?

### ISSUE THREAD

**Issue by HugoPeters1024** [VonHeikemen/lsp-zero.nvim#67]
First of all, thanks for the amazing work it is extremely helpful.

I did have one request, while I would like to use `nvim-cmp` in general, I usually have very little interest in the snippets it provides. Would it be possible to have a simple way of expressing that I don't want the snippets without making the setup fully manual? 

Perhaps another solution is the ordering, because the snippet suggestions are often higher in the list of suggestions than fields and methods which is super inconvenient.

**Comment by VonHeikemen** [comment]
I think the easiest way is to uninstall `rafamadriz/friendly-snippets`.

Another way is to setup the sources your self.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.setup_nvim_cmp({
  sources = {
    {name = 'path'},
    {name = 'nvim_lsp', keyword_length = 3},
    {name = 'buffer', keyword_length = 3},
  }
})

lsp.setup()
```

**Comment by HugoPeters1024** [comment]
Thanks for the quick reply, that piece of configuration does not seem to affect anything. I even uninstalled `rafamadriz/friendly-snippets`  but it still recommends a number of snippets as the first suggestions.

**Comment by HugoPeters1024** [comment]
Oh nvm, it must have been confused for a bit, now they are gone! Many thanks :)
