### ISSUE TITLE
LSP Zero auto import C++ (clangd)  

### ISSUE THREAD

**Issue by toziegler** [VonHeikemen/lsp-zero.nvim#68]
Hi, 
thanks for the great tool.

I switched from nvim-lspconfig to LSP-zero and so far, everything works great.
Although there is one missing functionality for me: auto include of dependencies for C++ from the standard library.

For instance, if we create a new empty main.cpp:
```C++
int main (int argc, char *argv[])
{
   std::vec  // no include (#include <vector>) and autocompletion for std::vector 
   return 0;
}
```
Previously with nvim-lspconfig, there has been a suggestion to auto-complete std::vector, triggering the necessary include.
From my understanding, the cmp documentation mentions that this should be possible when the capabilities are set accordingly, which should be the default. 
Unfortunately, this does not seem to have any effect. 

I used the default config, as shown in your Readme.

Thanks so much

**Comment by VonHeikemen** [comment]
do you have `compile_commands.json` in the root of your project?

**Comment by toziegler** [comment]
Actually, no for this single cpp file I haven't.  I thought I would be possible to let clang suggest system includes. But I will look deeper into clangd. Thanks though
