### ISSUE TITLE
Function signatures support

### ISSUE THREAD

**Issue by im-AMS** [VonHeikemen/lsp-zero.nvim#69]
Is it possible to make [github.com/ray-x/lsp_signature.nvim](https://github.com/ray-x/lsp_signature.nvim) this plugin work with Lsp-zero???

If no, can we add support for it?

**Comment by VonHeikemen** [comment]
What a nice issue.

I don't use it, but I believe this should be enough.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

local lsp_signature_config = {
  --- configure lsp_signature here
}

lsp.on_attach(function(client, bufnr)
  require('lsp_signature').on_attach(lsp_signature_config, bufnr)
end)

lsp.setup()
```

**Comment by im-AMS** [comment]
That works!!
Thanks!
