### ISSUE TITLE
How to pass `completion` option through to nvim-cmp

### ISSUE THREAD

**Issue by Aaronik** [VonHeikemen/lsp-zero.nvim#7]
Is there a way to pass the `{ 'completion.autocomplete' }` option through to `cmp`? I'm trying to get a debounce on my completion, which led me to https://github.com/hrsh7th/nvim-cmp/issues/598, which requires a config param (`autocomplete`) be passed in to `cmp` before `cmp.setup()` is called. Looks like `cmp` documents a similar approach to a problem [here](https://github.com/hrsh7th/nvim-cmp#full-managed-completion-behavior).

I see your documentation of [setup_nvim_cmp](https://github.com/VonHeikemen/lsp-zero.nvim#setup_nvim_cmpopts) but I'm not clearly understanding from the docs whether the `completion` list will be passed in, and in my attempts to make it work, it is not working.

P.S. Thank you for making this tool! I'm fresh in the nvim world from vim and this tool has really eased my transition.

**Comment by VonHeikemen** [comment]
`completion` was not exposed. But since [81e3d1f](https://github.com/VonHeikemen/lsp-zero.nvim/commit/81e3d1fe52caf76c6c92c0e9e6b1241ff710e2dc) you can overwrite it if you want.

This should work now.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.setup_nvim_cmp({
  completion = { autocomplete = false }
})

lsp.setup()
```

**Comment by Aaronik** [comment]
Thank you for your lightening fast response!

I've updated your plugin in my setup (Using plug, so I ran :PlugUpdate). I saw that lsp-zero was updated. I also went to the `~/.vim/plugged/lsp-zero` folder and checked the git history, and the `81e3d1f` commit was there, in addition to a couple more.

I have a series of lsp calls in my lua config: `lsp.set_preferences(...), lsp.on_attach(...), lsp.setup_nvim_cmp(...)`. Here is the relevant config:

```lua
local lspz = require('lsp-zero')

lspz.set_preferences({
  suggest_lsp_servers = true,
  setup_servers_on_start = true,
  set_lsp_keymaps = false, -- Toggled b/c the defaults are alright but not great for me.
  configure_diagnostics = true,
  cmp_capabilities = true,
  manage_nvim_cmp = true,
  call_servers = 'local',
  sign_icons = {
    error = '✘',
    warn = '▲',
    hint = '⚑',
    info = ''
  }
})

lspz.on_attach(function()
  local noremap = {noremap = true}
  local map = function(...) vim.api.nvim_buf_set_keymap(0, ...) end

  map('n', '<leader>je', '<cmd>lua vim.lsp.buf.rename()<cr>', noremap)
  map('n', '<leader>jk', '<cmd>lua vim.lsp.buf.hover()<cr>', noremap)
  map('n', '<leader>jd', '<cmd>lua vim.lsp.buf.definition()<cr>', noremap)
  map('n', '<leader>jD', '<cmd>lua vim.lsp.buf.declaration()<cr>', noremap)
  map('n', '<leader>jt', '<cmd>lua vim.lsp.buf.type_definition()<cr>', noremap)
  map('n', '<leader>ji', '<cmd>lua vim.lsp.buf.implementation()<cr>', noremap)
  map('n', '<leader>jr', '<cmd>lua vim.lsp.buf.references()<cr>', noremap)
  map('n', '<leader>js', '<cmd>lua vim.lsp.buf.signature_help()<cr>', noremap)
  map('n', '<leader>ja', '<cmd>lua vim.lsp.buf.code_action()<cr>', noremap)
  map('n', '<leader>jf', '<cmd>lua LspZeroFormat<cr>', noremap)
  map('n', '<leader>jw', '<cmd>lua vim.diagnostic.open_float()<cr>', noremap)
  map('n', '<C-l>', '<cmd>lua vim.diagnostic.goto_prev()<cr>', noremap)
  map('n', '<C-h>', '<cmd>lua vim.diagnostic.goto_next()<cr>', noremap)
end)

lspz.setup_nvim_cmp({
  completion = { autocomplete = false }
})

lspz.setup()
```

However I'm still seeing autocompletion. Am I doing anything obviously wrong?

**Comment by VonHeikemen** [comment]
It works for me.

Could it be another plugin or old configuration code still around?

Side note: `<leader>jf` is not going to work. `LspZeroFormat` is a  vim command not a lua function. You should bind it to `<cmd>lua vim.lsp.buf.formatting()<cr>`.

**Comment by Aaronik** [comment]
Ah oh nice, thank you for the heads up about `jf`, you're right that totally will not work.

I'm not really sure, I'll keep looking into it and if I find an answer I'll come back and post. Thanks for your help!
