### ISSUE TITLE
Question, Find all references in repo or cwd

### ISSUE THREAD

**Issue by phortonssf** [VonHeikemen/lsp-zero.nvim#70]
Is this even possible with the nvim lsp or just the current buffer?  Currently trying to use it for lua.  Everything works, I can use gd to navigate to the definition in a separate buffer but can only find references within the current buffer, not project-wide.  Thanks

**Comment by VonHeikemen** [comment]
You mean `gr` doesn't find other references? For me it does find references in multiple files.

Check with the command `LspInfo`. Make sure `single_file_support` is not there. Also check the root directory.
