### ISSUE TITLE
[Feature Request] support cmp-cmdline

### ISSUE THREAD

**Issue by arabindadora** [VonHeikemen/lsp-zero.nvim#75]
Hello,

Excellent work with this plugin! Greatly minimizes the boilerplate code :) 

Would it be possible to support [cmp-cmdline](https://github.com/hrsh7th/cmp-cmdline)? I tried to use [setup_nvim_cmp](https://github.com/VonHeikemen/lsp-zero.nvim#setup_nvim_cmpopts) but couldn't get it to work.

Thank you!

**Comment by VonHeikemen** [comment]
No need for special support. Install the necesary "cmp source" and set it up like it says on nvim-cmp's documentation.

```lua
local lsp = require('lsp-zero')

lsp.preset('recommended')
lsp.setup()

local cmp = require('cmp')

cmp.setup.cmdline({ '/', '?' }, {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    {name = 'buffer'}
  }
})

cmp.setup.cmdline(':', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = cmp.config.sources({
    {name = 'path'}
  }, {
    {name = 'cmdline'}
  })
})
```

**Comment by arabindadora** [comment]
ah right! thank you! :)
