### ISSUE TITLE
Use local language server

### ISSUE THREAD

**Issue by elferherrera** [VonHeikemen/lsp-zero.nvim#77]
Is there a way to configure the plugin to use the local language server instead of the one installed be Mason?

**Comment by VonHeikemen** [comment]
If it's on your PATH and its [supported by nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md), then yes. Use the function `.configure` then add the option `force_setup = true`.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.configure('dartls', {
  force_setup = true
})

lsp.setup()
```

**Comment by elferherrera** [comment]
I get this error

```
[lspconfig] Cannot access configuration for rust-analyzer. Ensure this server is listed in `server_configurations.md` or added as a custom server.
```

**Comment by VonHeikemen** [comment]
It's `rust_analyzer`, with an underscore.

**Comment by elferherrera** [comment]
Thanks. It works nicely in android.

By the way, what does the `force_setup` do?

**Comment by VonHeikemen** [comment]
Skips the internal checks that makes sure the server is installed. It calls the setup function for the server and hopes for the best.

**Comment by elferherrera** [comment]
I guess I cannot sent parameters to the server, right?

**Comment by VonHeikemen** [comment]
You can. The second argument to `.configure` is passed to `lspconfig`, you can send any valid option to the server.
