### ISSUE TITLE
error with `lsp.setup()` line in lsp.lua config file

### ISSUE THREAD

**Issue by PIesPnuema** [VonHeikemen/lsp-zero.nvim#78]
Hello,
I am receiving a error after installing lsp-zero and configuring the lsp.lua file with your minimum required config. The issue is from the `lsp.setup()` line inside lsp.lua. Any information will help thank you.

lsp.lua entire file contents (location: ~/.config/nvim/after/plugin/lsp.lua)
```
local lsp = require('lsp-zero')

lsp.preset('recommended')
lsp.setup()
```

Full ERROR code:
```
E5108: Error executing lua vim/_meta.lua:597: E474: Invalid argument
stack traceback:
        [C]: in function 'nvim_set_option_value'
        vim/_meta.lua:597: in function 'append'
        ...cker/start/lsp-zero.nvim/lua/lsp-zero/nvim-cmp-setup.lua:152: in function 'call_setup'
        ...im/site/pack/packer/start/lsp-zero.nvim/lua/lsp-zero.lua:32: in function 'setup'
        [string ":source (no file)"]:5: in main chunk
```

This is the function in question inside the file _meta.lua on line 597 
```
a.nvim_set_option_value(self._name, value, {scope = scope})
```
all other code is from the lsp-zero install via packer on ubuntu linux

neovim version:
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

**Comment by VonHeikemen** [comment]
Maybe try out this.

```lua
local lsp = require('lsp-zero')
lsp.preset('lsp-compe')

lsp.setup()

vim.opt.completeopt = {'menu', 'menuone', 'noselect'}

local cmp = require('cmp')
local cmp_config = lsp.defaults.cmp_config({})

cmp.setup(cmp_config)
```

**Comment by PIesPnuema** [comment]
Yes that solved my issue thank you very much! Was that something going on with my configuration with neovim?

**Comment by VonHeikemen** [comment]
I honestly don't know why that happened in your config? I actually can't reproduce the bug.

**Comment by PIesPnuema** [comment]
We'll I am stoked to have it working. Thanks for helping and also releasing the software!
