### ISSUE TITLE
Completion triggers after strings

### ISSUE THREAD

**Issue by ivanesmantovich** [VonHeikemen/lsp-zero.nvim#79]
Completion triggers after strings end 
![image](https://user-images.githubusercontent.com/70603816/208702714-673b1558-43e5-4009-b318-c35c0608857f.png)

Config:
```
local lsp = require('lsp-zero')

lsp.preset('recommended')
lsp.setup()
```

If it is not the right place to ask this question, please point me in the right direction. Thanks!

**Comment by VonHeikemen** [comment]
Don't know how to fix that. 

The plugin that handles autocompletion is [nvim-cmp](https://github.com/hrsh7th/nvim-cmp), maybe you can ask in their repo if there is an option for that.
