### ISSUE TITLE
Add denols's recommended config in recommended lsp.preset

### ISSUE THREAD

**Issue by aslak01** [VonHeikemen/lsp-zero.nvim#85]
Hey, just tried this thing out tonight and found that I'm back to an old problem in my Deno project: A project needing Denols lsp is detected as a tsserver project. Deno has a recommended strategy for dealing with this problem on their website, which is to configure tsserver and denols like so:

```lua
nvim_lsp.denols.setup {
  on_attach = on_attach,
  root_dir = nvim_lsp.util.root_pattern("deno.json"),
  init_options = {
    lint = true,
  },
}

nvim_lsp.tsserver.setup {
  on_attach = on_attach,
  root_dir = nvim_lsp.util.root_pattern("package.json"),
  init_options = {
    lint = true,
  },
}
```

https://deno.land/manual@v1.16.3/getting_started/setup_your_environment

It's not an ideal solution for every case, but it's worked well for me.

**Comment by VonHeikemen** [comment]
Those "root_dir patterns" are already part of the default config.

If you get both servers attached to a buffer is because both have `single_file_support` enabled. Just disable it for one of them.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.configure('tsserver', {
  single_file_support = false
})

lsp.setup()
```

**Comment by aslak01** [comment]
Nice! But adding this line has not solved the problem for me, even when disabling single file support for both.

**Comment by VonHeikemen** [comment]
That's unfortunate. You can still make use of the `root_pattern` function, though.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.configure('tsserver', {
  single_file_support = false
  root_dir = require('lspconfig.util').root_pattern('package.json')
})

lsp.setup()
```

**Comment by aslak01** [comment]
Perfect, that did the trick!
