### ISSUE TITLE
Deattaching 'tsserver' language server, when entering another buffer

### ISSUE THREAD

**Issue by m0xai** [VonHeikemen/lsp-zero.nvim#88]
Hello,

I enjoy using `lsp-zero` with `mason.nvim`, especially on my java projects.

However I have problem with `.tsx` files. When I start nvim and open a `.tsx` file, the typescript language server starts after a couple of seconds.Everything works fine. But if I open another file in another tab or go to another file, the `tsserver` de-attach itself and I have to start it manually with `:LspStart tsserver`. 
This problem doesn't occurs for example on java files. 

So here is my `lsp.lua` file:
```lua
local lsp = require("lsp-zero")

lsp.preset("recommended")

lsp.ensure_installed({
  'jdtls',
  'tsserver',
  'eslint',
  'sumneko_lua',
  'rust_analyzer',
})

-- Fix Undefined global 'vim'
lsp.configure('sumneko_lua', {
    settings = {
        Lua = {
            diagnostics = {
                globals = { 'vim' }
            }
        }
    }
})


local cmp = require('cmp')
local cmp_select = {behavior = cmp.SelectBehavior.Select}
local cmp_mappings = lsp.defaults.cmp_mappings({
  ['<C-p>'] = cmp.mapping.select_prev_item(cmp_select),
  ['<C-n>'] = cmp.mapping.select_next_item(cmp_select),
  ['<C-y>'] = cmp.mapping.confirm({ select = true }),
  ["<C-Space>"] = cmp.mapping.complete(),
})

lsp.setup_nvim_cmp({
  mapping = cmp_mappings
})

lsp.set_preferences({
    suggest_lsp_servers = false,
    sign_icons = {
        error = 'E',
        warn = 'W',
        hint = 'H',
        info = 'I'
    }
})

lsp.on_attach(function(client, bufnr)
  local opts = {buffer = bufnr, remap = false}

  if client.name == "eslint" then
      vim.cmd.LspStop('eslint')
      return
  end

  vim.keymap.set("n", "<leader>gd", vim.lsp.buf.definition, opts)
  vim.keymap.set("n", "<leader>gh", vim.lsp.buf.hover, opts)
  vim.keymap.set("n", "<leader>gcf", vim.lsp.buf.format, opts)
  vim.keymap.set("n", "<leader>vws", vim.lsp.buf.workspace_symbol, opts)
  vim.keymap.set("n", "<leader>gn", vim.diagnostic.open_float, opts)

  vim.keymap.set("n", "[d", vim.diagnostic.goto_next, opts)
  vim.keymap.set("n", "]d", vim.diagnostic.goto_prev, opts)
  vim.keymap.set("n", "<leader>ga", vim.lsp.buf.code_action, opts)
  vim.keymap.set("n", "<leader>vrr", vim.lsp.buf.references, opts)
  vim.keymap.set("n", "<leader>grn", vim.lsp.buf.rename, opts)
  vim.keymap.set("i", "<C-h>", vim.lsp.buf.signature_help, opts)
end)

lsp.setup()

vim.diagnostic.config({
    virtual_text = true,
})
```

However if I remove eslint client, it works just fine. 

Btw, I am noob, so I would be appreciate, if you consider this.

**Comment by VonHeikemen** [comment]
Does it detach from every buffer? Check with the command `:LspInfo`. You can also take a look at the logs from the lsp using `:LspLog`.

**Comment by m0xai** [comment]
Yes it does from every buffer, including the first one, in which starts fine.

I’m sorry but I’m on my way to holiday. But I set a reminder and will post `LspInfo` and `LspLog` on Tuesday.

**Comment by m0xai** [comment]
> Does it detach from every buffer? Check with the command `:LspInfo`. You can also take a look at the logs from the lsp using `:LspLog`.

Hier is my `LspInfo` output, after I opened another Buffer, 
![image](https://user-images.githubusercontent.com/58932692/209581453-cfd4a939-e0ae-43ce-b357-6af2c26ddfd2.png)

and this is how `LspLog` looks like:
![image](https://user-images.githubusercontent.com/58932692/209582032-788a3f91-65a1-4c4f-a259-f9e22cdbe0c2.png)

**Comment by VonHeikemen** [comment]
Sadly I don't see any errors there. If you can reproduce this bug with a minimal config it might be worth opening an issue in [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig).

You can make a new config and use it with the -u flag.

```
nvim -u /path/to/test-config.lua
```

Use this as `test-config.lua`.

```lua
-- exclude default paths/config
vim.opt.runtimepath:remove(vim.fn.expand('~/.config/nvim'))
vim.opt.packpath:remove(vim.fn.expand('~/.local/share/nvim/site'))

-- add new path
local config_dir = '/tmp/nvim-config'

vim.opt.runtimepath:append(config_dir)
vim.opt.packpath:append(config_dir)

-- Install minpac
local install_path = config_dir .. '/pack/minpac/opt/minpac'
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd('!git clone https://github.com/k-takata/minpac ' .. install_path)
  install_plugins = true
end

local pack_init = function()
  vim.cmd('packadd minpac')

  vim.call('minpac#init', {dir = config_dir})
  local Plug = vim.fn['minpac#add']

  -- Plugin manager
  Plug('k-takata/minpac', {type = 'opt'})

  -- LSP Support
  Plug('neovim/nvim-lspconfig')
  Plug('williamboman/mason.nvim')
  Plug('williamboman/mason-lspconfig.nvim')
end

-- Create commands to manage plugins
local command = vim.api.nvim_create_user_command
local pack_cmd = function(action)
  return function() pack_init(); vim.call(action) end
end

command('PackUpdate', pack_cmd('minpac#update'), {desc = 'Update plugins'})
command('PackClean', pack_cmd('minpac#clean'), {desc = 'Remove unlisted plugins'})
command('PackStatus', pack_cmd('minpac#status'), {desc = "Open minpac's progress window"})

if install_plugins then
  vim.cmd('PackUpdate')
  return
end

require('mason').setup({})
require('mason-lspconfig').setup({})

require('lspconfig').tsserver.setup({
  on_attach = function(client, bufnr)
    print('tsserver started')
  end,
})
```

**Comment by nomorechokedboy** [comment]
Looks like you were following theprimeagent as me. I finally find that the code that cause tsserver to detached to the current buffer when navigate. Just comment this
```lua
lsp.on_attach(function(client, bufnr)
  local opts = {buffer = bufnr, remap = false}

  if client.name == "eslint" then
      vim.cmd.LspStop('eslint')
      return
  end

  vim.keymap.set("n", "<leader>gd", vim.lsp.buf.definition, opts)
  vim.keymap.set("n", "<leader>gh", vim.lsp.buf.hover, opts)
  vim.keymap.set("n", "<leader>gcf", vim.lsp.buf.format, opts)
  vim.keymap.set("n", "<leader>vws", vim.lsp.buf.workspace_symbol, opts)
  vim.keymap.set("n", "<leader>gn", vim.diagnostic.open_float, opts)

  vim.keymap.set("n", "[d", vim.diagnostic.goto_next, opts)
  vim.keymap.set("n", "]d", vim.diagnostic.goto_prev, opts)
  vim.keymap.set("n", "<leader>ga", vim.lsp.buf.code_action, opts)
  vim.keymap.set("n", "<leader>vrr", vim.lsp.buf.references, opts)
  vim.keymap.set("n", "<leader>grn", vim.lsp.buf.rename, opts)
  vim.keymap.set("i", "<C-h>", vim.lsp.buf.signature_help, opts)
end)
```

**Comment by VonHeikemen** [comment]
That's interesting.  Not sure if this is bug or not: it looks like `LspStop` stops every LSP server in the buffer. It doesn't matter if the argument is the name of the server or a valid `id` number. You should open an issue in [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/) and ask if this is intended behavior (maybe `LspStop` doesn't take an argument).

In lsp-zero if you want to skip the setup of a server you can use the function `.build_options()`.

```lua
lsp.build_options('eslint')
```

This is mostly an escape hatch to help "integrate" lsp-zero with other LSP plugins (like rust-tools).

**Comment by m0xai** [comment]
> Looks like you were following thePrimeagen as me. I finally find that the code that cause tsserver to detached to the current buffer when navigate. Just comment this
> 
> ```lua
>   if client.name == "eslint" then
>       vim.cmd.LspStop('eslint')
>       return
>   end
> ```
> 
> I don't known why this code cause the issue, will try to understand later

Yeah, this is interesting. If I comment this out, it works as expected. Thank you!
