### ISSUE TITLE
All LSP installs fail with "spawn: npm failed with exit code - and signal -. npm is not executable"

### ISSUE THREAD

**Issue by chasehippen** [VonHeikemen/lsp-zero.nvim#91]
I have the following in my init.lua (using packer):
```
use {
  'VonHeikemen/lsp-zero.nvim',
  requires = {
    -- LSP Support
    {'neovim/nvim-lspconfig'},
    {'williamboman/mason.nvim'},
    {'williamboman/mason-lspconfig.nvim'},

    -- Autocompletion
    {'hrsh7th/nvim-cmp'},
    {'hrsh7th/cmp-buffer'},
    {'hrsh7th/cmp-path'},
    {'saadparwaiz1/cmp_luasnip'},
    {'hrsh7th/cmp-nvim-lsp'},
    {'hrsh7th/cmp-nvim-lua'},

    -- Snippets
    {'L3MON4D3/LuaSnip'},
    {'rafamadriz/friendly-snippets'},
  }
}
```
& the following in my lsp-zero config file:
```
local lsp = require('lsp-zero')

lsp.preset('recommended')
lsp.setup()
```

It let me install the lua-language-server when I first installed it & reopened my init.lua file, but no other language servers have been able to install successfully. All the ones I've tried fail with the message in the title.

**Comment by VonHeikemen** [comment]
Each language server has its own dependencies, `npm` just happens to be very common. Install [nodejs](https://nodejs.org/en/) and `npm` in your system.

**Comment by chasehippen** [comment]
That worked, thanks!
