### ISSUE TITLE
Allow to configure completion window with setup_nvim_cmp()

### ISSUE THREAD

**Issue by kiryl** [VonHeikemen/lsp-zero.nvim#92]
Looks like there's no way to customize `nvim-cmp` completion window appearance with `setup_nvim_cmp()`. I guess you can always hack directly into `nvim-cmp` configuration, but it defeats purpose of `lsp-zero` in my opinion.

I gave it a shot and this patch makes it work for me:

```
diff --git a/lua/lsp-zero/nvim-cmp-setup.lua b/lua/lsp-zero/nvim-cmp-setup.lua
index 040c2e5d2afd..0b85fe3f522e 100644
--- a/lua/lsp-zero/nvim-cmp-setup.lua
+++ b/lua/lsp-zero/nvim-cmp-setup.lua
@@ -181,6 +181,10 @@ M.call_setup = function(opts)
     config.preselect = opts.preselect
   end

+  if type(opts.window) == 'table' then
+    config.window = merge(config.window, opts.window)
+  end
+
   cmp.setup(config)
 end
```
With this patch I can do this:
```
lsp.setup_nvim_cmp({
    window = {
    completion = cmp.config.window.bordered({
      border = 'none',
      side_padding = 0,
      col_offset = -2,
    }),
  },
})

```

Although, I am not sure how it fits with the rest of `setup_nvim_cmp()` interface. Like documentation window already can be customized with `opts.documentation` already that translated into `config.window.documetation` on `nvim-cmp` side.

**Comment by VonHeikemen** [comment]
The `window.completion` option didn't exists when lsp-zero was created, that's why it isnt part of the defaults. So now the role of `setup_nvim_cmp` is just to allow the user to change some defaults, instead of being a mirror of the setup function for nvim-cmp. 

If you want to extend your config for nvim-cmp use the `lsp-compe` preset. You can use the function `.defaults.cmp_config` to expose the default config and then extend it however you like.

```lua
local lsp = require('lsp-zero')
lsp.preset('lsp-compe')

lsp.setup()

vim.opt.completeopt = {'menu', 'menuone', 'noselect'}

local cmp = require('cmp')
local cmp_config = lsp.defaults.cmp_config({
  window = {
    completion = cmp.config.window.bordered()
  }
})

cmp.setup(cmp_config)
```

**Comment by starptr** [comment]
Is it possible to remove a default mapping (added by lsp-zero) using this strategy? I'd like to customize `<C-e>` but in a different configuration file

**Comment by kiryl** [comment]
@VonHeikemen , okay it works. Looks like `setup_nvim_cmp()` doesn't not mix with the proposed fix. Any configuration that is done with `setup_nvim_cmp()` will be ignored.

It is okay with me. But maybe expose somewhere what config `lsp-zero` constructed and passed to `cmp.setup()`, including changes made with `setup_nvim_cmp()`?

**Comment by VonHeikemen** [comment]
@starptr sure.  When using the preset `lsp-compe` you can configure nvim-cmp anywhere you like.

About the mappings... You can technically "delete" a mapping before it gets to the setup function.

```lua
local cmp_config = lsp.defaults.cmp_config({
  window = {
    completion = cmp.config.window.bordered()
  }
})

cmp_config.mapping['<Tab>'] = nil
cmp_config.mapping['<S-Tab>'] = nil

cmp.setup(cmp_config)
```

If you want to override it, you can do it right inside `.defaults.cmp_config`. This has the advantage of keeping the other defaults.
 
```lua
local cmp_config = lsp.defaults.cmp_config({
  window = {
    completion = cmp.config.window.bordered()
  },
  mapping = {
    ['<C-e>'] = cmp.mapping.abort(),
  }
})
```

If you want to delete all default keybindings and make your own, override the `mapping` option outside `.defaults.cmp_config`.

```lua
local cmp_config = lsp.defaults.cmp_config({
  window = {
    completion = cmp.config.window.bordered()
  },
})

cmp_config.mapping = {
  ---
  -- add your own mappings here...
  ---
}
```

**Comment by VonHeikemen** [comment]
@kiryl I mention the avaible options of `.setup_nvim_cmp` [on the readme](https://github.com/VonHeikemen/lsp-zero.nvim#setup_nvim_cmpopts) (also the help page). I also try to explain [how to customize nvim-cmp](https://github.com/VonHeikemen/lsp-zero.nvim/blob/main/advance-usage.md#customizing-nvim-cmp) in the Advance usage page. And there is also [Under the hood ](https://github.com/VonHeikemen/lsp-zero.nvim/wiki/Under-the-hood) section of the wiki, which shows everything lsp-zero configures with the `recommended` preset.
