### ISSUE TITLE
lsp-zero with setup_servers_on_start=true and rust-tools

### ISSUE THREAD

**Issue by meuter** [VonHeikemen/lsp-zero.nvim#93]
Hi,

I'm trying to figure out a way to have lsp-zero with recommended settings (so with `setup_servers_on_start` set to `true`) and `rust-tools` to co-exist in the same config. The problem I'm having seems to be that lsp-zero automatically configures `rust_analyzer` and that somehow, this interferes with `rust-tools`'s configuration. I've tried putting `require("rust-tools").setup {}` before or after `lsp.setup()` but it does not seem to work. If I set `setup_servers_on_start` to `false`, then `rust-tools` works, but then other LSPs are not configured...

Any suggestions? Maybe adding a way to specify a list of LSP that would be excluded from automatic configuration. Then, for these LSP servers, you would have to manually configure them (or let `rust-tools` do it in my case).

Thanks for a *very* cool plugin BTW!

EDIT: typos

**Comment by VonHeikemen** [comment]
In this case you can use [.build_options()](https://github.com/VonHeikemen/lsp-zero.nvim#build_optionsserver-opts), this function will make lsp-zero skip the automatic setup and also expose the options for the setup.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

local rust_lsp = lsp.build_options('rust_analyzer', {})

lsp.setup()

-- Initialize rust_analyzer with rust-tools
require('rust-tools').setup({server = rust_lsp})
```

**Comment by meuter** [comment]
Cool, thanks! That's exactly what I was looking for! Happy holidays 🙂
