### ISSUE TITLE
Not an issue or a bug, just a [Question] - is there a way to display diagnostics upon hover?

### ISSUE THREAD

**Issue by RussianRoulette4Life** [VonHeikemen/lsp-zero.nvim#96]
Hi, i am new to NeoVim and would like to know if it is possible to display diagnostic messages (in case of a warning or an error) upon hover. I have searched the question and didn't find any satisfactory answer.

**Comment by VonHeikemen** [comment]
do you mean like taking the mouse, hover over a word and then display the diagnostic? You can't. It's a terminal thing, I don't think neovim knows anything about the mouse.

Closest thing you could do is making an autocommand with the event `CursorHold`. Executing the function/command to show diagnostic in this event.
